idempiere/idempiere

org.adempiere.base/src/org/compiere/db/PreparedStatementProxy.java, org.adempiere.base/src/org/compiere/db/ProxyFactory.java, org.adempiere.base/src/org/compiere/util/DB.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5509 …
=> IDEMPIERE-5509 Implement readonly query without using Trx

org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd, org.idempiere.parent/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-5461 …
=> IDEMPIERE-5461 Upgrade to zk 9.6.3

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/DateRangePicker.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5443?focusedCommentId=48967
=> IDEMPIERE-5443 Date Range Filter Component - fix Message not found error

migration/iD10/oracle/202211301123_IDEMPIERE-5505.sql, migration/iD10/postgresql/202211301123_IDEMPIERE-5505.sql, org.adempiere.base/src/org/compiere/model/I_GL_Category.java, org.adempiere.base/src/org/compiere/model/X_GL_Category.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5505 …
=> IDEMPIERE-5505 : Add Value and PrintName on GL_Category

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/StatusBarPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5491?focusedCommentId=48968
- Fix status bar not showing correctly on Find Window
=> IDEMPIERE-5491 Info Window - implement Select/DeSelect All buttons (FHCA-4016)

migration/iD10/oracle/202212121023_IDEMPIERE-5517.sql, migration/iD10/postgresql/202212121023_IDEMPIERE-5517.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WTextEditorDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5517 …
=> IDEMPIERE-5517: WTextEditorDialog : prevent user from losing text

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4781
fix by @igorpojzl  …
=> IDEMPIERE-4781 - Fix Key not ending with _ID

org.adempiere.ui/src/org/compiere/print/DrillReportCtl.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5514 …
=> IDEMPIERE-5514 - Drill Assistant Error - Drill key parameter is not set

migration/iD10/oracle/202212231059_IDEMPIERE-5302.sql, migration/iD10/postgresql/202212231059_IDEMPIERE-5302.sql
- Add missing primary keys / IDEMPIERE-5523
=> IDEMPIERE-5302 Drill Assistant Feature

migration/iD10/oracle/202212231121_IDEMPIERE-5295.sql, migration/iD10/postgresql/202212231121_IDEMPIERE-5295.sql, org.adempiere.base/src/org/compiere/report/TrialBalance.java
- Add column T_TrialBalance_UU
=> IDEMPIERE-5295 Trial Balance Report creates wrong Opening Balance

org.adempiere.base/src/org/compiere/print/ReportEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5524 …
=> IDEMPIERE-5524 Slow Rendering of HTML Report

org.adempiere.server-feature/pom.xml
=> IDEMPIERE-5523 Release 10 Peace

org.adempiere.base/src/org/compiere/wf/MWorkflow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5530 …
=> IDEMPIERE-5530 - adding ad_client_id to mworkflow cache key

org.adempiere.base/src/org/compiere/model/MSequence.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5533 …
=> # IDEMPIERE-5533 - Changes MSequence to allow HTTPS on ID centralizer

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WLocationDialog.java
=> IDEMPIERE-5535 - Fixed warning dialog shown wrongly

org.adempiere.base/src/org/compiere/model/MInvoice.java, org.adempiere.base/src/org/compiere/model/MOrder.java
=> IDEMPIERE-5544 - Fix orders being calculated with wrong tax provider

org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/AbstractService.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5543 …
=> IDEMPIERE-5543: Add service type name when role doesn't have access to

migration/iD10/oracle/202212231904_IDEMPIERE-5526.sql, migration/iD10/postgresql/202212231904_IDEMPIERE-5526.sql, org.adempiere.base.process/src/org/compiere/process/BOMVerify.java
- [] I have made corresponding changes to the documentation as follows:
- - [] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a …
=> IDEMPIERE-5526 - Translation Bom Verify Proces

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
=> IDEMPIERE-5531 : Auto save confirmation at onPrint

migration/iD10/oracle/202301131932_IDEMPIERE-5229.sql, migration/iD10/postgresql/202301131932_IDEMPIERE-5229.sql, org.adempiere.base/src/org/compiere/model/I_AD_VerifyMigration.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MVerifyMigration.java, org.adempiere.base/src/org/compiere/model/X_AD_VerifyMigration.java, org.adempiere.base/src/org/idempiere/process/DiscardThisVerifyMigration.java, org.adempiere.base/src/org/idempiere/process/VerifyMigration.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5229
- - [x] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
=> IDEMPIERE-5229 After migrate helper (FHCA-4070)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPDocumentStatus.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DashboardRunnable.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5527
- implement the same when pushing the Refresh button
=> IDEMPIERE-5527 Implement asynchronous rendering of dashboard gadget panel

migration/iD10/oracle/202301062010_IDEMPIERE-5534.sql, migration/iD10/postgresql/202301062010_IDEMPIERE-5534.sql, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java
=> IDEMPIERE-5534 Make configurable the maximum records in lists

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADTabbox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/CompositeADTabbox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridTabRowRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Combobox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Tab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/LoginWindow.java
- Partial fix plus workaround
- Minor clean up and Javadoc fix
- Create dynamic style for Detail Tabs only once
https://idempiere.atlassian.net/browse/IDEMPIERE-5520
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user …
=> IDEMPIERE-5520 Navigation between Tabs leave Detached DOM objects (Leak)

org.adempiere.base/src/org/compiere/util/CLogMgt.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5548
- removed the button Reload Log Props from the About Dialog as is now being reloaded when changing level
=> IDEMPIERE-5548 Issues with Log Management

migration/iD10/oracle/202301261727_IDEMPIERE-5555.sql, migration/iD10/postgresql/202301261727_IDEMPIERE-5555.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocatorEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5555
- Added predefined context variable IgnoreProductInLocatorEditor
=> IDEMPIERE-5555 Locator not showing all options on Product window with only a warehouse

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/CompositeADTabbox.java
- Fix level 0 and 1 tab visible at the same time after zoom to detail
- Minor refinement of bread crumb update
https://idempiere.atlassian.net/browse/IDEMPIERE-5551
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts …
=> IDEMPIERE-5551 Wrong Tab rendering

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5528
- Solve NPE
=> IDEMPIERE-5528 Context parsing on process Parameter not considering tab no

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPaySelect.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5558
=> IDEMPIERE-5558 Payment Selection (manual) unusable when the first bank doesn't have payment rules configured

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Window.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
- Fix navigation error
https://idempiere.atlassian.net/browse/IDEMPIERE-5559
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, …
=> IDEMPIERE-5559 Cannot find current Find Window - NullPointerException

org.adempiere.ui/src/org/compiere/apps/form/PaySelect.java
- fix problem with filling the table before payment rule is set
https://idempiere.atlassian.net/browse/IDEMPIERE-5558?focusedCommentId=49125
=> IDEMPIERE-5558 Payment Selection (manual) unusable

org.adempiere.base/src/org/compiere/model/MSystem.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5566
=> IDEMPIERE-5566 Cross tenant PO writing on AD_System

org.adempiere.base/src/org/compiere/print/DataEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5565
=> IDEMPIERE-5565 Cannot create report with virtual column where reference is table with display column = ID

org.adempiere.base/src/org/compiere/model/MInOut.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5571
=> IDEMPIERE-5571 Shipment created by Drop Ship Material Receipt is not processing workflows

org.adempiere.base/src/org/compiere/model/MOrder.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5568
=> IDEMPIERE-5568 Allow Force in Sales Order Delivery Rule even if the warehouse doesn't accept negatives

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
=> IDEMPIERE-5565 Info Window not working with virtual column where reference is table with display column = ID

org.adempiere.base/src/org/compiere/model/MOrder.java
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5579 …
=> IDEMPIERE-5579 - Missing Period Control When Reactivating Orders

org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5578
=> IDEMPIERE-5578 Data corruption when copying order lines from a closed order

migration/iD11/oracle/202302131520_IDEMPIERE-5573.sql, migration/iD11/postgresql/202302131520_IDEMPIERE-5573.sql, org.adempiere.base/src/org/compiere/model/I_AD_Reference.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MReference.java, org.adempiere.base/src/org/compiere/model/X_AD_Reference.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultInfoFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/IInfoFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoAssetWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoAssignmentWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoBPartnerWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoInOutWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoInvoiceWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoOrderWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoPaymentWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5573 …
=> IDEMPIERE-5573 - Enable Showing Inactive Records through Reference

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WNumberEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/Dialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5581 …
=> IDEMPIERE-5581 : Dialog.askForInput : allow Integer

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultInfoFactory.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5574
=> IDEMPIERE-5574 Drop Ship BPartner must have opposite IsSOTrx logic on Info Window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocationEditor.java
=> IDEMPIERE-5494 : [WLocationEditor] - Enable Zoom - fix NPE

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditorPopupMenu.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5585 …
=> IDEMPIERE-5585 : Drill Assistant image not shown using theme with images

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WDrillReport.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java, org.adempiere.ui/src/org/compiere/print/DrillReportCtl.java
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5593
=> IDEMPIERE-5593 - Drill Rule: Do not render Drill Rules for the same Report

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5596 …
=> IDEMPIERE-5596 Advance Find: List of Tab is wrong for Product > Price

migration/iD11/oracle/202303010819_IDEMPIERE-5592.sql, migration/iD11/postgresql/202303010819_IDEMPIERE-5592.sql
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5592
=> IDEMPIERE-5592 - Add C_Calendar_ID to Period Control Management

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/MenuElementHandler.java
=> IDEMPIERE-5597 : 2pack updating root level menu items failling.

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
=> IDEMPIERE-5599: Use Tab.IsSingleRow when copying a record

org.adempiere.base/src/org/compiere/util/DisplayType.java, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5542 …
=> IDEMPIERE-5542 [DisplayType] - Cache issue

org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5238
=> IDEMPIERE-5238 Record_ID editor - Add safety validation in PO

org.adempiere.base/src/org/compiere/acct/Doc.java, org.adempiere.pipo/src/org/adempiere/pipo2/AbstractElementHandler.java
- fixes for the new cross-tenant validation
https://idempiere.atlassian.net/browse/IDEMPIERE-5238
=> IDEMPIERE-5238 Record_ID editor

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5615
=> IDEMPIERE-5615 Record Info Dialog wrong when open in Detail tab

org.adempiere.install/src/org/compiere/install/ConfigVM.java, org.adempiere.install/src/org/compiere/install/ConfigurationData.java, org.adempiere.install/src/org/compiere/install/ConfigurationPanel.java, org.adempiere.install/src/org/compiere/install/SetupRes.java, org.adempiere.install/src/org/compiere/install/console/ConfigurationConsole.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5617 …
=> IDEMPIERE-5617 Add Java Options field to iDempiere Server Setup dialog

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPPerformance.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DashboardPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5607
=> IDEMPIERE-5607 - Dashboard Process Tenant data rendered in System

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5629
=> IDEMPIERE-5629 Error when using context variables in info window view ID column

org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.base/src/org/compiere/print/PrintDataColumn.java
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5618
=> IDEMPIERE-5618 - Print Format Script Column does not show Data in correct Data Types

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/TimeoutPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5626 …
=> IDEMPIERE-5626 Kil All session, popup strange message

migration/iD11/oracle/202303111206_IDEMPIERE-5624.sql, migration/iD11/postgresql/202303111206_IDEMPIERE-5624.sql, org.adempiere.base/plugin.xml, org.adempiere.base/src/org/adempiere/base/IGridTabExporter.java, org.adempiere.base/src/org/adempiere/impexp/GridTabSQLInsertExporter.java, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/POInfo.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/ExportAction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5624 …
=> IDEMPIERE-5624 Implement export data as SQL insert statement

migration/iD10/oracle/202303131848_IDEMPIERE-5613.sql, migration/iD10/postgresql/202303131848_IDEMPIERE-5613.sql, org.adempiere.base/src/org/adempiere/process/UUIDGenerator.java, org.adempiere.base/src/org/compiere/process/SvrProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5613
=> IDEMPIERE-5613 Make filling of _UU column optional

org.adempiere.base/src/org/compiere/acct/Doc_InOut.java, org.adempiere.base/src/org/compiere/acct/Doc_Inventory.java, org.adempiere.base/src/org/compiere/acct/Doc_MatchInv.java, org.adempiere.base/src/org/compiere/acct/Doc_MatchPO.java, org.adempiere.base/src/org/compiere/acct/Doc_Movement.java, org.adempiere.base/src/org/compiere/acct/FactLine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5616
=> IDEMPIERE-5616 Reverse Shipments don't post because of Not Balanced in special case

org.adempiere.base/src/org/compiere/model/MPasswordRule.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5610 …
=> IDEMPIERE-5610: Improve layout of Password Validator translations

migration/iD10/oracle/202303081200_IDEMPIERE-5611.sql, migration/iD10/postgresql/202303081200_IDEMPIERE-5611.sql, org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
- Fix zoom window on tables that have this field empty and have a window associated
https://idempiere.atlassian.net/browse/IDEMPIERE-5611
=> IDEMPIERE-5611 Record ID Editor doesn't work with House Keeping

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/LayoutUtils.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/DrillCommand.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/event/DrillEvent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/report/HTMLExtension.java, org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/report.js
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5630
=> IDEMPIERE-5630 - Drill rule from dashboard html report never opening

org.idempiere.test/src/org/idempiere/test/base/LogicExpressionTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5632 …
=> IDEMPIERE-5632 Add unit test for regular expression match for contains

org.adempiere.base/src/org/adempiere/base/event/annotations/ModelEventHandler.java
=> IDEMPIERE-5631 - ModelEventHandler findTableName by Model annotation

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/AbstractDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/IDesktop.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5630
Comment: https://idempiere.atlassian.net/browse/IDEMPIERE-5630?focusedCommentId=49267
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the …
=> IDEMPIERE-5630 - Multiple Drill Assistants Opening from Dashboard

org.adempiere.server-feature/idempiere-server.sh
=> Docker standarization

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java
=> IDEMPIERE-5636 - Add Mattermost to the About Tab

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5393
Bug reported by @nmicoud: https://idempiere.atlassian.net/browse/IDEMPIERE-5393?focusedCommentId=49164
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user …
=> IDEMPIERE-5393 - Dashboard panel header disappearing

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WTextEditorDialog.java
- - [X] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [X] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [X] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed.
=> IDEMPIERE-5638 - Fix nullpointer when expanding editor in virtual column

org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordIDEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5633
=> IDEMPIERE-5633 Check tableId <=0 in PO.checkRecordIDCrossTenant()

org.adempiere.base/src/org/adempiere/model/MBroadcastMessage.java
- - [X] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [X] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [X] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed.
=> IDEMPIERE-5640 - Fix Cross Tenant Sending BroadCast Message

org.adempiere.base.process/src/org/compiere/process/ColumnEncryption.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5604
Tested in postgresql and oracle
=> IDEMPIERE-5604 Column Encryption is broken in native postgresql

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/QuickGridTabRowRenderer.java
- - [X] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [X] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [X] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed.
=> IDEMPIERE-5639 - Improve navigation on QuickForm

migration/iD10/oracle/202303071543_IDEMPIERE-5602.sql, migration/iD10/postgresql/202303071543_IDEMPIERE-5602.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutTimeExpense.java, org.adempiere.base/src/org/compiere/model/I_S_TimeExpenseLine.java, org.adempiere.base/src/org/compiere/model/MTimeExpenseLine.java, org.adempiere.base/src/org/compiere/model/X_S_TimeExpenseLine.java
=> IDEMPIERE-5602 : Adding PriceEntered in Expense report

utils_dev/oomph/idempiere.setup
https://idempiere.atlassian.net/browse/IDEMPIERE-5655 …
=> IDEMPIERE-5655 Add setup file for Oomph Import

org.adempiere.base.process/src/org/compiere/process/ColumnEncryption.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5604?focusedCommentId=49352
Test case in a fresh vanilla:
* Login as System Administrator
* Open Table and navigate to AD_Client
* Navigate to the column RequestUserPW
* Click on the “Not Encrypted” button in the gear toolbar button
** Encrypted = Y
** Change the Current Setting = Y
** Maximum Length = 120
** Test Value = anything
* There is an error mentioning that the max length of 120 doesn’t fit in the 255 characters of the column, but anyways the column is encrypted and is not marked as encrypted, leaving the data corrupt because iDempiere cannot read it properly.
=> IDEMPIERE-5604 Column Encryption not marking column as encrypted - data corruption

org.adempiere.base/src/org/compiere/print/DataEngine.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5652 …
=> IDEMPIERE-5652 - Print Format: Format Pattern is not Applied on Grouping/Summary rows

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/CompositeADTabbox.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5658 …
=> IDEMPIERE-5658: NPE CompositeADTabbox.onTabSelectionChangedEcho

org.adempiere.base/src/org/compiere/util/WebEnv.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5174?focusedCommentId=49375
=> IDEMPIERE-5174 Disable System User - Set new System

org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.base/src/org/compiere/print/PrintDataElement.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5645 …
=> IDEMPIERE-5645 - Print Format Script Column cannot find Columns from context

migration/iD10/oracle/202304042029_IDEMPIERE-5650.sql, migration/iD10/postgresql/202304042029_IDEMPIERE-5650.sql, org.adempiere.base/src/org/compiere/model/MDashboardContent.java, org.adempiere.base/src/org/compiere/util/Util.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5650 …
=> IDEMPIERE-5650 - Cannot Define Multiple Values for Dashboard Content Process Parameters

org.adempiere.base/src/org/compiere/model/GridWindowVO.java, org.idempiere.test/src/org/idempiere/test/AbstractTestCase.java, org.idempiere.test/src/org/idempiere/test/adwindow/GridTabTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5560
=> IDEMPIERE-5560 Fix broken unit tests

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/ADCalendarEvent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/CalendarWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPDocumentStatus.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPFavourites.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPGoogleCalendar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPMenuTree.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPPerformance.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRunningJobs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPViews.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DashboardPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DashboardRunnable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/EventWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/FavouriteFolderDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/IDashboardPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/LoginOpenSequenceDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/RequestWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/AbstractDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/FavouriteController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/IDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/IServerPushCallback.java
- org.adempiere.webui.dashboard and org.adempiere.webui.desktop package
https://idempiere.atlassian.net/browse/IDEMPIERE-5570
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a …
=> IDEMPIERE-5570 Zk: Improve readability of code

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5666 …
=> IDEMPIERE-5666 - fix NPE on refreshing report

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/FavouriteController.java
- [] I have added unit tests that prove my fix is effective or that my feature works …
=> IDEMPIERE-5674 - Fix null pointer exception when remove favorites nodes

org.adempiere.base/src/org/compiere/model/MTable.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5675
=> IDEMPIERE-5675 MTable.getPO cache for model factory wrongly removing from cache when PO is not found

migration/iD11/oracle/202304171928_IDEMPIERE-5567.sql, migration/iD11/postgresql/202304171928_IDEMPIERE-5567.sql, org.adempiere.base/src/org/compiere/util/DB.java, org.idempiere.test/src/org/idempiere/test/model/MTestTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5567?focusedCommentId=49409
- fix broken unit tests in oracle
=> IDEMPIERE-5567 Support of UUID for Search (UU) data type (FHCA-4195)

migration/iD11/oracle/202304141228_IDEMPIERE-5669.sql, migration/iD11/postgresql/202304141228_IDEMPIERE-5669.sql, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5669 …
=> IDEMPIERE-5669 - Display Row Count of Executed Reports

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/AbstractDesktop.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5682 …
=> IDEMPIERE-5682 - Closing Browser Tab while Report Viewer is Opened causes NPE

org.adempiere.base/src/org/compiere/acct/Fact.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2194
- Copy the information from the line being distributed
=> Fixes IDEMPIERE-2194 GL Journal Distribution writes no DocumentNo in Accounting Fact Description

org.adempiere.base.process/src/org/compiere/process/OrderCreateProduction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5685
=> IDEMPIERE-5685 Do not Create Production for AutoProduce products

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
A NPE was introduced with latest changes when running Period Control Management - or process from an info window that have an alias on the main table
=> IDEMPIERE-5567 Fix NPE running Period Control Management

org.adempiere.base/src/org/compiere/print/PrintData.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
2 issues fixed:
- row count in tab did not refresh on clicking the refresh button (only on re-run)
- row count included function rows too
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5669
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the …
=> IDEMPIERE-5669 - Report Row Count shows incorrect data

migration/iD11/oracle/202304131354_IDEMPIERE-5668.sql, migration/iD11/oracle/202304250949_IDEMPIERE-5668.sql, migration/iD11/postgresql/202304131354_IDEMPIERE-5668.sql, migration/iD11/postgresql/202304250949_IDEMPIERE-5668.sql, org.adempiere.base.process/src/org/compiere/process/CopyRole.java
- [] I have added unit tests that prove my fix is effective or that my feature works …
=> IDEMPIERE-5668 - Improvements to the copy role process

migration/iD11/oracle/202304111125_IDEMPIERE-5663.sql, migration/iD11/postgresql/202304111125_IDEMPIERE-5663.sql
- [] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [] New and existing unit tests pass locally with my changes
- [] I have added unit tests that prove my fix is effective or that my feature works
- [] I have made corresponding changes to the documentation as follows:
- - [] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand …
=> IDEMPIERE-5663 - [Accounting Fact Details Report] - New parameter GL_category

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WListItemRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WTableColumn.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5692 …
=> IDEMPIERE-5692 Add custom column editor support to WListbox

org.adempiere.base/src/org/compiere/model/Query.java, org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5691 …
=> IDEMPIERE-5691 Add Table Direct type joint method to Query

org.adempiere.base/src/org/compiere/model/MLocatorLookup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocatorEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5689 …
=> IDEMPIERE-5689 Make MLocatorLookup and WLocatorEditor more extensible

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ProcessButtonPopup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/validator/WindowValidatorEvent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/validator/WindowValidatorEventType.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/validator/WindowValidatorManager.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5688 …
=> IDEMPIERE-5688 Enhancement to WindowValidator API

migration/iD11/oracle/202304281200_IDEMPIERE-5699.sql, migration/iD11/postgresql/202304281200_IDEMPIERE-5699.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5699 …
=> IDEMPIERE-5699 - Deactivated Product Info toolbar button

org.adempiere.base/src/org/compiere/model/ModelValidationEngine.java
- [] I have added unit tests that prove my fix is effective or that my feature works …
=> IDEMPIERE-5698 - Improvement for display all events errors

org.adempiere.base/src/org/eevolution/process/EnableNativeSequence.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/ValuePreference.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5509?focusedCommentId=49512
=> IDEMPIERE-5509 Implement readonly query without using Trx - fix issue with native sequences in PostgreSQL

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WArchiveViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5704
=> IDEMPIERE-5704 Archive Viewer silent when archive cannot be deleted

migration/iD10/oracle/202305011505_IDEMPIERE-5706.sql, migration/iD10/postgresql/202305011505_IDEMPIERE-5706.sql, org.adempiere.base/src/org/compiere/model/X_AD_FieldGroup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WTabEditor.java, org.adempiere.ui/src/org/compiere/apps/form/TabEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5706
=> IDEMPIERE-5706 Improvements to Tab Editor in Window Customization

org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.ui/src/org/compiere/print/ReportCtl.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5695
=> IDEMPIERE-5695 - Process audit doesn't set print language, format, print format on Forms/documents

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5702
=> IDEMPIERE-5702 - IndexOutOfBoundsException on Info Window

org.adempiere.base/src/org/compiere/model/GridField.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5708
=> IDEMPIERE-5708 Show in grid value in dictionary cannot be overriden by customize

org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/GenericPOElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5238?focusedCommentId=49523
=> IDEMPIERE-5238 Fix checkRecordIDCrossTenant failing in multi-key table

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5709 …
=> IDEMPIERE-5709 - Fixed SQLFind columns not working

migration/iD11/oracle/202304280940_IDEMPIERE-5683.sql, migration/iD11/postgresql/202304280940_IDEMPIERE-5683.sql, org.adempiere.base.process/src/org/idempiere/process/CleanOrphanCascade.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/PO_Record.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5683
=> IDEMPIERE-5683 - Improve Record ID and Record UU by Constraint Type

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5614
=> IDEMPIERE-5614 Advanced Find Window error when searching for Yes/No

org.adempiere.ui/src/org/compiere/apps/form/Archive.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5714
=> IDEMPIERE-5714 - Archive Viewer - Created By field shows cross tenant data

org.adempiere.base/src/org/compiere/model/PO_Record.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5683
=> IDEMPIERE-5683 - Ignore Views with Record ID and Record UU Model Constraints

org.adempiere.base/src/org/compiere/model/MTest.java, org.idempiere.test/src/org/idempiere/test/base/POTest.java, org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5712
=> IDEMPIERE-5712 Tests are leaving records in the database

org.idempiere.test/src/org/idempiere/test/model/ModelForeignKeyTest.java
=> IDEMPIERE-5683 ModelForeignKeyTest throwing error when parallel tests

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5667
=> IDEMPIERE-5667 Recent Items not Refreshing when Deleting Records in Grid View

org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5731
=> IDEMPIERE-5731 NPE when using Query.list() with a view

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5724
=> IDEMPIERE-5724 Cannot add Related Info Window to Info Product

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/GridTabDataBinder.java
=> IDEMPIERE-5720 Multi select product on orders is broken

org.adempiere.ui.zk/WEB-INF/src/name/fraser/neil/plaintext/diff_match_patch.java, org.adempiere.ui.zk/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-5733
- Upgrade org.outerj.daisy from 1.1.15 to 1.2.2
- Upgrade com.googlecode.owasp-java-html-sanitizer from 20200713.1 to 20220608.1
- Upgrade diff_match_patch.java with latest github location
=> IDEMPIERE-5733 Obsolete libraries in org.adempiere.ui.zk/lib

org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordIDEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordUUIDEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultEditorFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoAssetWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoBPartnerWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoInvoiceWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoAssetPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoAssignmentPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoBPartnerPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoInOutPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoInvoicePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoOrderPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPaymentPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordIDDialog.java
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195)

org.adempiere.base/src/org/compiere/print/DataEngine.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5737
=> IDEMPIERE-5737 - Change Report's "No Rows" log level

migration/iD11/oracle/202304151832_IDEMPIERE-5567.sql, migration/iD11/postgresql/202304151832_IDEMPIERE-5567.sql, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/I_AD_ChangeLog.java, org.adempiere.base/src/org/compiere/model/MChangeLog.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MSession.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/PO_Record.java, org.adempiere.base/src/org/compiere/model/X_AD_ChangeLog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WFieldRecordInfo.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordInfo.java
- implement ChangeLog for UUID Based Tables
- implement foreign key rules for Record_UU fields
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - ChangeLog - FKRules

migration/iD11/oracle/202305231609_IDEMPIERE-5567.sql, migration/iD11/postgresql/202305231609_IDEMPIERE-5567.sql, org.adempiere.base/src/org/compiere/model/I_AD_RecentItem.java, org.adempiere.base/src/org/compiere/model/MRecentItem.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/X_AD_RecentItem.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java
NOTE this pull request is dependent on https://github.com/idempiere/idempiere/pull/1852
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - Recent Items

org.adempiere.base/src/org/compiere/process/SvrProcess.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5730
=> IDEMPIERE-5730 - Context is not parsed in exception message logs thrown from processes

org.adempiere.base/src/org/compiere/print/ReportEngine.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5216
=> IDEMPIERE-5216 - HTML report Record ID Trl fix

org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordInfo.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5735
Most of the code removed here was duplicate from PO
=> IDEMPIERE-5735 Useless code in GridTable.dataSave

migration/iD11/oracle/202304280940_IDEMPIERE-5683.sql, migration/iD11/postgresql/202304280940_IDEMPIERE-5683.sql
Fixing - Because of the ordering of scripts - the latest changes on IDEMPIERE-5683 destroyed changes on IDEMPIERE-5567
=> IDEMPIERE-5683 Exception: NO Data found for Record_ID

migration/iD10/oracle/202305262207_IDEMPIERE-5739.sql, migration/iD10/postgresql/202305262207_IDEMPIERE-5739.sql, org.adempiere.base.process/src/org/compiere/process/InventoryValue.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5739
=> IDEMPIERE-5739 Allow Inventory Valuation Report for more than one warehouse

migration/i8.2z/oracle/202106282230_IDEMPIERE-4836.sql, migration/i8.2z/postgresql/202106282230_IDEMPIERE-4836.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4836?focusedCommentId=49630
=> IDEMPIERE-4836 Adding Access tab on Document Status (Activity) - fix issue with native sequence

migration/iD11/oracle/202305291332_IDEMPIERE-5567.sql, migration/iD11/postgresql/202305291332_IDEMPIERE-5567.sql, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/I_AD_Attachment.java, org.adempiere.base/src/org/compiere/model/I_AD_LabelAssignment.java, org.adempiere.base/src/org/compiere/model/I_AD_PostIt.java, org.adempiere.base/src/org/compiere/model/I_CM_Chat.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MChat.java, org.adempiere.base/src/org/compiere/model/MLabelAssignment.java, org.adempiere.base/src/org/compiere/model/MPostIt.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/X_AD_Attachment.java, org.adempiere.base/src/org/compiere/model/X_AD_LabelAssignment.java, org.adempiere.base/src/org/compiere/model/X_AD_PostIt.java, org.adempiere.base/src/org/compiere/model/X_CM_Chat.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.pipo/src/org/adempiere/pipo/srv/PipoDictionaryService.java, org.adempiere.server/src/main/server/org/compiere/server/AlertProcessor.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/LabelsSearchController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LabelsPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/LabelAction.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WChat.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPostIt.java
- add support for AD_Attachment, CM_Chat, AD_PostIt and AD_LabelAssignment for UUID based tables
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - Toolbar

org.adempiere.base/src/org/compiere/model/GridTab.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5567?focusedCommentId=49635
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - fix issue reported by Murilo

org.adempiere.base/src/org/compiere/acct/Doc_AllocationHdr.java, org.idempiere.test/src/org/idempiere/test/model/AllocationTest.java
base on patch from gauravsontakke
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation …
=> IDEMPIERE-5723 NPE when allocate has both AR and AP invoice

org.adempiere.base.process/src/org/compiere/process/ReplenishReportProduction.java
=> IDEMPIERE-5758 Improve extensibility of ReplenishReportProduction

org.adempiere.base/src/org/compiere/model/MOrder.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5759 …
=> IDEMPIERE-5759 - Fixed potential NPE when sending a null orderclause

org.adempiere.base/src/org/compiere/model/GridField.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5755
=> IDEMPIERE-5755 - Empty value preference logs false parsing error on Dates

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/DateRangePicker.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5753
=> IDEMPIERE-5753 - Date Picker doesn't set time on first date in Quick Mode

org.adempiere.base/src/org/compiere/process/SvrProcess.java
Applying changes from @igorpojzl.
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5754
=> IDEMPIERE-5754 - Check PInstance_ID before Process Lock DB Update, PInstance 0 on createPricelist

org.adempiere.server/src/main/server/org/compiere/server/AdempiereServerMgr.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5763 …
=> IDEMPIERE-5763 Improve reliability of stopping a scheduler

org.adempiere.base/src/org/compiere/model/MZoomCondition.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5721 …
=> IDEMPIERE-5721: Fill AD_ZoomCondition.SeqNo

org.adempiere.base/src/org/compiere/model/MChangeLog.java, org.adempiere.base/src/org/compiere/model/Query.java
While testing https://github.com/idempiere/idempiere/pull/1888 found two methods that can be refactored to improve readability and probably speed.
=> IDEMPIERE-5567 - refactor of some array related methods

org.adempiere.base/src/org/compiere/model/MSession.java
https://mattermost.idempiere.org/idempiere/pl/1gqauqg7o3rx9cstkmrm9pxuto
=> IDEMPIERE-5567 - fix stack overflow logging changelog

migration/iD11/oracle/202306072319_IDEMPIERE-5765.sql, migration/iD11/postgresql/202306072319_IDEMPIERE-5765.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5765
=> IDEMPIERE-5765 Shipment generated service lines cannot be directly edited because the Locator is empty

org.adempiere.base/src/org/compiere/model/MRole.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5407
Committing fix by @igorpojzl
=> IDEMPIERE-5407 - Fix Wrong getIdColumnName Validation

migration/iD10/oracle/202306061239_IDEMPIERE-5746.sql, migration/iD10/postgresql/202306061239_IDEMPIERE-5746.sql, org.adempiere.base/src/org/compiere/acct/Doc.java, org.adempiere.base/src/org/compiere/acct/Doc_BankStatement.java, org.adempiere.base/src/org/compiere/acct/Doc_Production.java, org.adempiere.base/src/org/compiere/model/CalloutEngine.java, org.adempiere.base/src/org/compiere/model/I_C_BankStatement.java, org.adempiere.base/src/org/compiere/model/I_M_Production.java, org.adempiere.base/src/org/compiere/model/MBankStatement.java, org.adempiere.base/src/org/compiere/model/MPeriod.java, org.adempiere.base/src/org/compiere/model/MProduction.java, org.adempiere.base/src/org/compiere/model/X_C_BankStatement.java, org.adempiere.base/src/org/compiere/model/X_M_Production.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WDocActionPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5746
=> IDEMPIERE-5746 Bank Statement and Production cannot use Overwrite Date/Seq on Complete

org.adempiere.server-feature/utils.unix/unix/DebianInstaller/DEBIAN/control
https://idempiere.atlassian.net/browse/IDEMPIERE-5448
Required change for debian installer
=> IDEMPIERE-5448 2023 June Platform Update

org.adempiere.base.process/src/org/compiere/process/InOutGenerate.java, org.adempiere.base/src/org/compiere/model/MStorageOnHand.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5776
=> IDEMPIERE-5776 Cannot generate shipment for an order with multiple lines for same product and Complete Order delivery rule

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPaySelect.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5777
=> IDEMPIERE-5777 Improve extensibility of WPaySelect

migration/iD10/oracle/202306211841_IDEMPIERE-5747.sql, migration/iD10/postgresql/202306211841_IDEMPIERE-5747.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5747
=> IDEMPIERE-5747 When using Generate PO from SO - cannot delete the generated PO, neither the SO lines

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5764 …
=> IDEMPIERE-5764 [ZOOM] - Window configured in reference does not work

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/zul/calendar/calendar.css
https://idempiere.atlassian.net/browse/IDEMPIERE-5364 …
=> IDEMPIERE-5364 Event name is truncated at bottom

org.adempiere.report.jasper/src/org/adempiere/report/jasper/ColumnLookup.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5783
=> IDEMPIERE-5783 Support date and number in jasper column lookup

org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MInvoice.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5782
=> IDEMPIERE-5782 Generated Shipments/MR and Invoices with Invalid Sales Rep

org.adempiere.base.process/src/org/compiere/process/DunningPrint.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/process/DunningPrint.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5787
=> IDEMPIERE-5787 Print Dunning Letters doesn't work with multi-language

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WProcessCtl.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5778
=> IDEMPIERE-5778 - Focus is not set to Process Modal Dialog in Info Windows

org.adempiere.base/src/org/compiere/model/MUserQuery.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5781
=> IDEMPIERE-5781 Any user can destroy a configured SQL Query

migration/iD11/oracle/202306290925_IDEMPIERE-5786.sql, migration/iD11/postgresql/202306290925_IDEMPIERE-5786.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/acct/WAcctViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WBOMDrop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPluginManager.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WFEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WFPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ADForm.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/InfoSchedule.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkJRViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5786
=> IDEMPIERE-5786 - Refactor ESC/Alt+X Shortcut for Closing Tabs

migration/iD11/oracle/202306221620_IDEMPIERE-5062.sql, migration/iD11/postgresql/202306221620_IDEMPIERE-5062.sql, org.adempiere.base/src/org/compiere/model/MProcessPara.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5062
- added validation for min and max value when run process
- added validation when insert min and max value format
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user …
=> IDEMPIERE-5062 validation when run process and input min max value on process parameter

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/grid/WQuickEntry.java
=> IDEMPIERE-2706 bug fix when create record from quick entry with default value

org.adempiere.base/src/org/compiere/model/MOrgInfo.java
=> JIRA TICKET : https://idempiere.atlassian.net/browse/IDEMPIERE-1502

org.adempiere.base/src/org/compiere/dbPort/Convert.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.base/src/org/compiere/util/Util.java
https: //idempiere.atlassian.net/browse/IDEMPIERE-5795 …
=> IDEMPIERE-5795: DeveloperMode context variable

migration/iD11/oracle/202306241143_IDEMPIERE-5567-Request.sql, migration/iD11/postgresql/202306241143_IDEMPIERE-5567-Request.sql, org.adempiere.base/src/org/compiere/model/I_R_Request.java, org.adempiere.base/src/org/compiere/model/MArchive.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MChat.java, org.adempiere.base/src/org/compiere/model/MLabelAssignment.java, org.adempiere.base/src/org/compiere/model/MPostIt.java, org.adempiere.base/src/org/compiere/model/MRequest.java, org.adempiere.base/src/org/compiere/model/X_R_Request.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/WRequest.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/model/MRequestTest.java, org.idempiere.test/src/org/idempiere/test/model/MTestTest.java
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - Implement support for Requests on UUID Based Tables

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WPerformanceDetail.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5786
=> IDEMPIERE-5786 - Support Closing Performance Detail with Shortcut

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
=> IDEMPIERE-5791 - Fix Error when changing print format to CSV

org.adempiere.base/src/org/adempiere/util/ReservationLogTracer.java, org.adempiere.base/src/org/compiere/model/MOrg.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5799
=> IDEMPIERE-5799 - Storage Reservation Log does not set Organization Correctly

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5725 …
=> IDEMPIERE-5725 NPE in gridview on mobile

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5801 …
=> IDEMPIERE-5801 Process Modal Dialog overlapped with Info Window

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5805
=> IDEMPIERE-5805 - Dashboard Help Icon Produces Unwanted Network Requests

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5790
=> IDEMPIERE-5790 - Print Format is being Reset after Report Refresh

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
=> IDEMPIERE-5811 - Fix NPE on event for BroadcastMessages

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5811?focusedCommentId=49884
=> IDEMPIERE-5811 - Fix NPE on event for BroadcastMessages / fix kill session feature

org.adempiere.server-feature/hazelcast-template.xml, org.idempiere.hazelcast.service/pom.xml, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/Activator.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/CacheConsoleProvider.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/CacheServiceImpl.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/ClusterMember.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/ClusterServiceImpl.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/MessageServiceImpl.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/TopicImpl.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5816
=> IDEMPIERE-5816 Upgrade Hazelcast version (FHCA-4436)

migration/iD11/oracle/202307241036_IDEMPIERE-5807.sql, migration/iD11/postgresql/202307241036_IDEMPIERE-5807.sql, org.adempiere.base/src/org/compiere/model/I_I_Product.java, org.adempiere.base/src/org/compiere/model/MProduct.java, org.adempiere.base/src/org/compiere/model/X_I_Product.java
I noticed the indentation in `I_I_Product.java` is a bit weird but since it is generated code I left it the way it was generated. Let me know if you want me to change it!
- - [X] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user …
=> IDEMPIERE-5807 Add ability to specify attribute set when importing products

org.adempiere.base/src/org/compiere/model/MSession.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5818
=> IDEMPIERE-5818 AD_Session cache is not working

org.adempiere.base/src/org/compiere/Adempiere.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/util/Trx.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/TableElementHandler.java, org.idempiere.test/src/org/idempiere/test/base/MatchInvTestIsolated.java, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5732
=> IDEMPIERE-5732 Cache reset should happens after commit of transaction

org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/session/SessionManager.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/DesktopWatchDog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5813 …
=> IDEMPIERE-5813 Change Role must close session like Logout does

org.adempiere.base.process/src/org/compiere/process/CommissionCalc.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/commission/CommissionRunTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5821
=> IDEMPIERE-5821 Credit Memos are commissioning positive

org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5826
=> IDEMPIERE-5826 iDempiere REST can insert/update an invalid foreign key

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/CalendarWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/RequestWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2533
- Fix Sales Rep validation
- Do not show the Switch Time Zone when no timezones to switch
- minor fix to avoid NPE in DPCalendar
=> IDEMPIERE-2533 Calendar (Event) - Create request has wrong Dyn Validation

org.adempiere.base/src/org/adempiere/base/PackInFolderApplication.java, org.adempiere.base/src/org/compiere/Adempiere.java, org.adempiere.base/src/org/compiere/model/MSystem.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/SystemProperties.java, org.adempiere.base/src/org/compiere/util/CCache.java, org.adempiere.base/src/org/compiere/util/CLogFormatter.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java, org.adempiere.base/src/org/compiere/util/Ini.java, org.adempiere.install/src/org/compiere/install/ConfigurationData.java, org.adempiere.install/src/org/compiere/install/SilentSetup.java, org.adempiere.replication/src/org/adempiere/process/rpl/exp/ModelExporter.java, org.adempiere.replication/src/org/adempiere/process/rpl/imp/ModelImporter.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/BundleResourceLoader.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ClassResourceLoader.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ReportStarter.java, org.adempiere.server/src/main/home/org/bmlaurus/home/Prop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/theme/ThemeManager.java, org.compiere.db.oracle.provider/src/org/adempiere/db/oracle/config/ConfigOracle.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.oracle.provider/src/org/compiere/dbPort/Convert_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java, org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/Activator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5837
=> IDEMPIERE-5837 Collect all System Properties of iDempiere in one class

org.adempiere.ui.zk/WEB-INF/src/org/zkoss/addon/chosenbox/Chosenbox.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5810 …
=> IDEMPIERE-5810 Reference "Chosen Multiple Selection Search" can not be done correctly at the first selection

org.adempiere.base.process/src/org/idempiere/process/CleanOrphanCascade.java
Fixes for the CleanOrphanCascade process:
- add management for AD_Tree_Favorite_Node
- remove management for AD_Package_UUID_Map (in the end this is unnecessary to take care of orphans in this table)
- implement management for Record_UU columns
- fix problem with UUID based tables
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - CleanOrphanCascade

org.adempiere.base/src/org/idempiere/process/MigraID.java
Fixes for the MigraID process:
- Add management for AD_Tree_Favorite_Node
- Add management for multi-IDs fields (comma separated IDs or UUIDs)
- Add management for AD_Package_UUID_Map
- Fix issues with UUID based tables
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - MigraID

org.adempiere.base/src/org/compiere/util/DisplayType.java, org.adempiere.base/src/org/idempiere/process/MoveClient.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
- Fix issue caused by last changes - the *SelectionGrid fields are not working because they don't have a formal Reference
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - 2Pack

migration/iD10/oracle/202309021535_IDEMPIERE-5843.sql, migration/iD10/postgresql/202309021535_IDEMPIERE-5843.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5843
=> IDEMPIERE-5843 System support users (like SuperUser) cannot see (fix) preferences on tenants

org.adempiere.base/src/org/adempiere/base/event/AbstractEventHandler.java, org.adempiere.base/src/org/adempiere/base/event/EventManager.java, org.adempiere.base/src/org/adempiere/base/event/IEventManager.java, org.adempiere.base/src/org/adempiere/base/event/RequestEventHandler.java, org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.base/src/org/compiere/model/MRecentItem.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/idempiere/broadcast/BroadcastMsgUtil.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5841 …
=> IDEMPIERE-5841  AD_Note created by Request causing Cross Tenant

migration/iD11/oracle/202308301811_IDEMPIERE-5493.sql, migration/iD11/postgresql/202308301811_IDEMPIERE-5493.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5493
- Set Model Cascade for Record_ID column in AD_WF_Activity, AD_WF_EventAudit and AD_WF_Process
=> IDEMPIERE-5493 [Workflow Activities] - Activity persists after delete related record

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5772
=> IDEMPIERE-5772 - Info Window Ctx - Paging Issue

migration/iD11/postgresql/202309111844_IDEMPIERE-5567_ADPInstance.sql
- Fix migration script error
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might …
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - AD_PInstance (#2003)

org.adempiere.base/src/org/compiere/model/PO.java
- Fix unit test errors
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be …
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - AD_PInstance

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5803
=> IDEMPIERE-5803 - Toolbar does not check if overlapped widow is closing with shortcut

migration/iD11/oracle/202309111358_IDEMPIERE-5852.sql, migration/iD11/postgresql/202309111358_IDEMPIERE-5852.sql, org.adempiere.base/src/org/idempiere/broadcast/BroadcastMsgUtil.java
=> IDEMPIERE-5852 Change broadcastmessage column size

org.adempiere.base/src/org/compiere/print/ServerReportCtl.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5854
=> IDEMPIERE-5854 Error when trying to call ServerReportCtl.runJasperProcess with a process info without a transaction name

migration/iD11/oracle/202309171225_IDEMPIERE-4697.sql, migration/iD11/postgresql/202309171225_IDEMPIERE-4697.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WFilenameEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4697 …
=> IDEMPIERE-4697 : temporary filename "adempiere_"

org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5826?focusedCommentId=49994
This reverts commit db833e36658381c7d9a0dd5932ede6be4beb3897.
=> Revert "IDEMPIERE-5826 iDempiere REST can insert/update an invalid foreign key (#1969)"

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WResetPassword.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5857
=> IDEMPIERE-5857 Cross tenant on Reset Password

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ConfirmPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4751 …
=> IDEMPIERE-4751 : Usability suggestion - Position for reset button in Info Window

org.adempiere.ui/src/org/compiere/print/DrillReportCtl.java
=> IDEMPIERE-5845 - Adds Window Access validation for Drill Assistent

org.adempiere.base/src/org/adempiere/base/sso/ISSOPrincipalService.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.eclipse.equinox.http.servlet/src/org/adempiere/eclipse/equinox/http/servlet/BridgeFilter.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitorFilter.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/sso/filter/SSOWebUIFilter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5346
- peer review …
=> IDEMPIERE-5346 : Adding SSO support

migration/iD11/oracle/202309200811_IDEMPIERE-4526.sql, migration/iD11/postgresql/202309200811_IDEMPIERE-4526.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4526 …
=> IDEMPIERE-4526 : Selection list for UOM on Client window do not relate to the type of UOM expected

org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditor.java
patch from Heng Sin
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be …
=> IDEMPIERE-5849:MRole.getDefault make phantom role on cache

Credits.html
https://idempiere.atlassian.net/browse/IDEMPIERE-5873
=> IDEMPIERE-5873 name correction in

org.adempiere.base/src/org/compiere/model/MLookupFactory.java
=> IDEMPIERE-5867:autocomplete show different list for table and table dir

org.adempiere.base/src/org/compiere/model/MInvoicePaySchedule.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2076 …
=> IDEMPIERE-2706 : auto validate invoice payment schedule when create new record

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4907 …
=> IDEMPIERE-4907 : Jasper Report using Dashboard Content

org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4687 …
=> IDEMPIERE-4687 : PackOut is writing twice the AD_Org_ID in each record

org.adempiere.base/src/org/compiere/acct/Doc.java
=> IDEMPIERE-5872 - Improve on SQL Errors displayed for user

org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/ModelADServiceImpl.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5865 …
=> IDEMPIERE-5865 : Cannot Update Always Updatable checked column via Web Service

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/HeaderPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4671
added shortcut using alt+g to focus on search box
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If …
=> IDEMPIERE-4671 : Shortcut for the menu box

migration/iD11/oracle/202310011317_IDEMPIERE-5207.sql, migration/iD11/oracle/202310150641_IDEMPIERE-5207.sql, migration/iD11/postgresql/202310011317_IDEMPIERE-5207.sql, migration/iD11/postgresql/202310150641_IDEMPIERE-5207.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5207 …
=> IDEMPIERE-5207 : Missing tabs on System Translation Check window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5833 …
=> IDEMPIERE-5833 : "parentIds" is null while zoom Partner Location in window Purchase Order

org.adempiere.base.process/src/org/compiere/process/AllocationReset.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4346
=> IDEMPIERE-4346 [Allocation Reset] - Transaction not close when exception is throw

migration/iD10/oracle/202310161741_IDEMPIERE-4682.sql, migration/iD10/postgresql/202310161741_IDEMPIERE-4682.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4682
=> IDEMPIERE-4682 oracle has M_INVENTORYLINEMA_KEY is reason error when complete Internal Use Inventory

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/MenuTreeFilterPanel.java
=> IDEMPIERE-5887 - Fixed bug causing NPE when clicking on Flat View

org.adempiere.base.process/src/org/compiere/process/DunningRunCreate.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/dunning/DunningRunTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5793
=> IDEMPIERE-5793 premature dunning when dunning run is done on exactly the due date

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5773 …
=> IDEMPIERE-5773 - Fixed bug on advance detail not adding the parenthesis on detail tab queries

migration/iD11/oracle/202310180934_IDEMPIERE-4648.sql, migration/iD11/postgresql/202310180934_IDEMPIERE-4648.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4648 …
=> IDEMPIERE-4648 : new tab Tax Rate in the Tax Category window.

migration/iD10/oracle/202310161235_IDEMPIERE-5883.sql, migration/iD10/postgresql/202310161235_IDEMPIERE-5883.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5883
=> IDEMPIERE-5883 Improve default for Receipt parameter in Payment Info

migration/iD10/oracle/202310191513_IDEMPIERE-5888.sql, migration/iD10/postgresql/202310191513_IDEMPIERE-5888.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/MUserPreference.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5888
=> IDEMPIERE-5888 Login Preferences are created on System tenant

org.adempiere.base/src/org/compiere/model/MRecentItem.java, org.adempiere.base/src/org/compiere/model/MShippingTransaction.java, org.adempiere.base/src/org/compiere/model/MSystem.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java, org.adempiere.base/src/org/compiere/process/MFARevokeDevice.java, org.adempiere.base/src/org/compiere/process/MFAUnregister.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.base/src/org/idempiere/mfa/EMailMechanism.java, org.adempiere.base/src/org/idempiere/mfa/TOTPMechanism.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ADTreeFavoriteOnDropListener.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WFieldSuggestion.java, org.idempiere.test/src/org/idempiere/test/form/PaymentFormTest.java, org.idempiere.test/src/org/idempiere/test/model/BankStatementTest.java, org.idempiere.test/src/org/idempiere/test/model/MSchedulerTest.java, org.idempiere.test/src/org/idempiere/test/model/MUOMConversionTest.java, org.idempiere.test/src/org/idempiere/test/model/ModelForeignKeyTest.java
This is just helping for readability
=> IDEMPIERE-4639 simplify calls using saveCrossTenantSafeEx when possible

org.idempiere.p2/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-5890 …
=> IDEMPIERE-5890:mvn validate is failed by artifacts could not be resolved

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5851
Committing original code by @igorpojzl
=> IDEMPIERE-5851 - Set Focus Automatically to the 1st Row of the Info Window Result Set

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxListEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditorPopupMenu.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5898 …
=> IDEMPIERE-5898 Implementation of the assistant to type search and table in multi-selection fields

org.adempiere.base/src/org/adempiere/base/event/delegate/AutoProduceEventDelegate.java
=> IDEMPIERE-5899 Fix message error AutoProduce

org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
https://idempiere.atlassian.net/browse/IDEMPIERE-5895 …
=> IDEMPIERE-5895:use maven for bundle from p2 repository eclipse 4.20

org.adempiere.base/src/org/compiere/model/MLookupFactory.java
- Fix NPE
https://idempiere.atlassian.net/browse/IDEMPIERE-5904 …
=> IDEMPIERE-5904 NPE for Search Fields within Reference Keys

org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5911 …
=> IDEMPIERE-5911 : [IDempiere Monitor] Open Log File on New Tab

org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
https://idempiere.atlassian.net/browse/IDEMPIERE-5914 …
=> IDEMPIERE-5914 Upgrade Jetty from 10.0.15 to 10.0.18

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
=> IDEMPIERE-5901 - Fix NPE for not found autocomplete column message

org.adempiere.base-feature/model.generator.launch, org.adempiere.base-feature/packinfolder.app.launch, org.adempiere.base-feature/sign.database.build.launch, org.adempiere.base-feature/synchronize-terminology.app.launch, org.adempiere.base-feature/translation.app.launch, org.adempiere.install/install.app.launch, org.adempiere.install/install.console.app.launch, org.adempiere.install/install.silent.app.launch, org.adempiere.server-feature/server.product.functionaltest.launch, org.adempiere.server-feature/server.product.launch, org.adempiere.server-feature/setup/configuration/config.ini, org.compiere.db.oracle.provider/.classpath, org.compiere.db.oracle.provider/META-INF/MANIFEST.MF, org.compiere.db.oracle.provider/build.properties, org.compiere.db.oracle.provider/pom.xml, org.compiere.db.postgresql.provider/.classpath, org.compiere.db.postgresql.provider/META-INF/MANIFEST.MF, org.compiere.db.postgresql.provider/build.properties, org.compiere.db.postgresql.provider/pom.xml, org.compiere.db.provider-feature/feature.xml, org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.repository.target, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.test/idempiere.unit.test.launch, org.idempiere.test/idempiere.unit.test.parallel.launch, utils_dev/oomph/idempiere.setup
=> IDEMPIERE-5909:use jdbc library as bundle

org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/ADLookup.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5926
=> IDEMPIERE-5926 SOAP WebService failing -> Invalid Lookup value

org.adempiere.base/src/org/compiere/model/MAuthorizationAccount.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5927
=> IDEMPIERE-5927 EMail Workflow fails when sending email using a System mail account

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/Dialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5925 …
=> IDEMPIERE-5925: Method Dialog.info with callback

org.adempiere.base/src/org/compiere/print/layout/GridElement.java, org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java, org.adempiere.base/src/org/compiere/print/layout/ParameterElement.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5908 …
=> IDEMPIERE-5908 Report parameters are not displayed in full in PDF

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxListEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5934
- [] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user …
=> IDEMPIERE-5934 : Read only Chosen Multiple Selection List fields can be updated using Assistant

org.adempiere.base/src/org/idempiere/process/MoveClient.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5940
=> IDEMPIERE-5940 Move/Copy Client failing when there are tables without AD_Client_ID

org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4877 …
=> IDEMPIERE-4877 - Fix Footer is overlay on content

org.adempiere.base.process/src/org/compiere/process/CreateFromInOut.java, org.adempiere.base.process/src/org/compiere/process/CreateFromInvoice.java, org.adempiere.base.process/src/org/compiere/process/CreateFromRMA.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5936
- Save all the columns of the selected row to T_Selection_InfoWindow
- Remove the SQL query joining between T_Selection table and CreateFrom database view
=> IDEMPIERE-5936 Slow performance creating MR/Invoice Lines using CREATE LINES FROM.. in process M_InOut/C_Invoice_CreateFromProcess

org.adempiere.ui.zk/plugin.xml, org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/model/MWebService.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/model/MWebServiceMethod.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/model/MWebServicePara.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/model/MWebServiceType.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5948 …
=> IDEMPIERE-5948:change to work with eclipse 2023-09

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/MenuElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5951
=> IDEMPIERE-5951 Menu root entries added by 2Pack are shown on top

migration/iD10/oracle/202312041243_IDEMPIERE-5782.sql, migration/iD10/postgresql/202312041243_IDEMPIERE-5782.sql, org.adempiere.base.callout/src/org/adempiere/model/CalloutRMA.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MRMA.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5782
- Fix same issue with RMA
=> IDEMPIERE-5782 Generated Shipments/MR and Invoices with Invalid SalesRep

org.adempiere.base/src/org/compiere/report/FinReportJasper.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5955
=> IDEMPIERE-5955 Financial Report using jasper is throwing exception about closed connection

org.adempiere.base/src/org/compiere/util/DB.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5076
Test case is to try to copy GardenWorld tenant when there is an attachment or image with binary data, against an oracle database.
=> IDEMPIERE-5076 Move/Copy client doesn't work in oracle

migration/iD10/oracle/202312081400_IDEMPIERE-5953.sql, migration/iD10/postgresql/202312081400_IDEMPIERE-5953.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5953
=> IDEMPIERE-5953 Can not select Order or Material receipt on Create lines from on Vendor Invoice as it do not show any value

migration/iD10/oracle/202312111654_IDEMPIERE-5954.sql, migration/iD10/postgresql/202312111654_IDEMPIERE-5954.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5954
=> IDEMPIERE-5954 Payment Info Window failing on Payments into Batch > Lines

migration/iD11/oracle/202312080607_IDEMPIERE-5932.sql, migration/iD11/postgresql/202312080607_IDEMPIERE-5932.sql, org.adempiere.base/src/org/compiere/model/MTreeFavorite.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPFavourites.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5932
=> IDEMPIERE-5932 Update English top-level menu names and window names to better support new user adoption

migration/iD11/oracle/202305020844_IDEMPIERE-5697.sql, migration/iD11/oracle/202305020845_IDEMPIERE-5697.sql, migration/iD11/postgresql/202305020844_IDEMPIERE-5697.sql, migration/iD11/postgresql/202305020845_IDEMPIERE-5697.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5697
- revert making AD_PInstance_Log.AD_PInstance_Log_UU primary key, left just as unique constraint IDEMPIERE-5957
=> IDEMPIERE-5697 Improve Process Log for more advanced logging options for Processes

org.adempiere.pipo/src/org/adempiere/pipo2/AbstractElementHandler.java
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - fix NPE in PackIn

migration/iD11/oracle/202311030829_IDEMPIERE-5905.sql, migration/iD11/postgresql/202311030829_IDEMPIERE-5905.sql
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5905
=> IDEMPIERE-5905 - Unique Constraint should ensure unique Import Loader Format Field to avoid invalid SQL

migration/iD11/oracle/202312041549_IDEMPIERE-5943.sql, org.compiere.db.postgresql.provider/src/org/adempiere/db/postgresql/partition/TablePartitionService.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java, org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java, org.idempiere.test/idempiere.unit.test.parallel.launch
https://idempiere.atlassian.net/browse/IDEMPIERE-5943?focusedCommentId=50387
=> IDEMPIERE-5943 Implement table partitioning support

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxListEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxSearchEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5934
=> IDEMPIERE-5934 Read only Chosen Multiple Selection List fields can be updated using Assistant

org.adempiere.base/src/org/compiere/install/Translation.java, org.adempiere.base/src/org/compiere/install/TranslationHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5965
=> IDEMPIERE-5965 Translation Import crashed with a wrong XML

org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5849?focusedCommentId=50382
- Make SysConfigurable to return System role for backward compatibility
=> IDEMPIERE-5849 MRole.getDefault make phantom role on cache

org.adempiere.ui.zk/index.zul
https://idempiere.atlassian.net/browse/IDEMPIERE-5966
=> IDEMPIERE-5966 Restore support for http

migration/iD11/oracle/202312221238_IDEMPIERE-5346.sql, migration/iD11/postgresql/202312221238_IDEMPIERE-5346.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5346
- fix UUID field displayed in grid
- fix UUID column without index
- fix CreatedBy/UpdatedBy must be Search instead of Table (for better performance)
- [x ] I have tested the direct scenario that my code is solving
=> IDEMPIERE-5346 SSO Support - dictionary fixes

org.adempiere.server-feature/pom.xml
=> IDEMPIERE-5967 Release 11 Synergy

org.adempiere.server-feature/pom.xml
=> Remove Byte Order Mark characters from pom.xml

Credits.html
=> Updated contributors list with 2023 info

org.compiere.db.oracle.provider/META-INF/MANIFEST.MF, org.compiere.db.postgresql.provider/META-INF/MANIFEST.MF, org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, utils_dev/oomph/idempiere.setup
https://idempiere.atlassian.net/browse/IDEMPIERE-5969
- postgresql 42.6.0 -> 42.7.1 (Dec 06, 2023)
- hikaricp 5.0.1 -> 5.1.0 (Nov 04, 2023)
=> IDEMPIERE-5969 Upgrade DB libraries

org.adempiere.base/src/org/compiere/model/MQuery.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5970
https://idempiere.atlassian.net/browse/IDEMPIERE-5271
=> IDEMPIERE-5970 Reference field must be filled in Report Customization for multiple fields

org.idempiere.javadoc/pom.xml, org.idempiere.webservices.resources/META-INF/MANIFEST.MF
https://idempiere.atlassian.net/browse/IDEMPIERE-3943
https://idempiere.atlassian.net/browse/IDEMPIERE-5903
=> IDEMPIERE-3943 Fix broken Automated javadoc generation

migration/iD11/oracle/202312301352_IDEMPIERE-5943.sql, migration/iD11/postgresql/202312301352_IDEMPIERE-5943.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5943
- minor fix to menu - make it centrally maintained and correct the process name
- this created an issue when generating the wiki Manual as the menu name is different than the process name - which is unusual in core
=> IDEMPIERE-5943 Implement table partitioning support - fix menu

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5062 …
=> IDEMPIERE-5062:Min/Max Validation for Process Parameters is not implemented

org.adempiere.base/src/org/compiere/model/MBankStatement.java, org.adempiere.base/src/org/compiere/process/DocumentEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5982 …
=> IDEMPIERE-5982: Reactivation of Bank Statements

org.adempiere.base/src/org/adempiere/base/event/delegate/AutoProduceEventDelegate.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5981
=> IDEMPIERE-5981 Misleading error when completing an auto-produce shipment

migration/iD11/oracle/202401101451_IDEMPIERE-5988.sql, migration/iD11/postgresql/202401101451_IDEMPIERE-5988.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5988
=> IDEMPIERE-5988 Wrong DisplayLogic in Discount, Write-off, Over/Under Payment fields

org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MChat.java, org.adempiere.base/src/org/compiere/model/MLabelAssignment.java, org.adempiere.base/src/org/compiere/model/MPostIt.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LabelsPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5989
IDEMPIERE-5567
Fix issue when the window doesn't have the UUID field
=> IDEMPIERE-5989 Attachments are not accessible after upgrade from Idempiere 10 to Idempiere 11

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5888?focusedCommentId=50505
=> IDEMPIERE-5888 - solve login issue for users with single client not saving preferences

org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/tree.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-5986 …
=> IDEMPIERE-5986 : Tree items w/o parent must be aligned like with parents

migration/iD12/oracle/202401151138_IDEMPIERE-5245.sql, migration/iD12/postgresql/202401151138_IDEMPIERE-5245.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5245
=> IDEMPIERE-5245 Fix typos in dictionary (used codespell on translation XML files)

org.adempiere.base/src/org/compiere/model/I_AD_Role.java, org.adempiere.base/src/org/compiere/model/I_A_Asset.java, org.adempiere.base/src/org/compiere/model/I_S_TimeExpenseLine.java, org.adempiere.base/src/org/compiere/model/I_T_BOM_Indented.java, org.adempiere.base/src/org/compiere/model/I_U_POSTerminal.java, org.adempiere.base/src/org/compiere/model/X_AD_Role.java, org.adempiere.base/src/org/compiere/model/X_AD_TablePartition.java, org.adempiere.base/src/org/compiere/model/X_A_Asset.java, org.adempiere.base/src/org/compiere/model/X_A_Asset_Reval_Entry.java, org.adempiere.base/src/org/compiere/model/X_C_Project.java, org.adempiere.base/src/org/compiere/model/X_C_ProjectPhase.java, org.adempiere.base/src/org/compiere/model/X_C_ProjectTask.java, org.adempiere.base/src/org/compiere/model/X_S_TimeExpenseLine.java, org.adempiere.base/src/org/compiere/model/X_T_BOM_Indented.java, org.adempiere.base/src/org/compiere/model/X_U_POSTerminal.java, org.adempiere.base/src/org/eevolution/model/I_HR_Job.java, org.adempiere.base/src/org/eevolution/model/I_PP_Order_BOMLine.java, org.adempiere.base/src/org/eevolution/model/I_PP_Product_BOMLine.java, org.adempiere.base/src/org/eevolution/model/I_T_BOMLine.java, org.adempiere.base/src/org/eevolution/model/X_HR_Job.java, org.adempiere.base/src/org/eevolution/model/X_PP_Cost_Collector.java, org.adempiere.base/src/org/eevolution/model/X_PP_Order_BOMLine.java, org.adempiere.base/src/org/eevolution/model/X_PP_Product_BOMLine.java, org.adempiere.base/src/org/eevolution/model/X_T_BOMLine.java
=> IDEMPIERE-5245 Model generate after latest dictionary fixes

org.adempiere.base/src/org/compiere/model/MSysConfig.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6000
- [x ] My code follows the best practices of this project
=> IDEMPIERE-6000 Reset AD_SysConfig cache automatically when configured

org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MInvoice.java, org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/model/MRfQResponse.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.base/src/org/compiere/print/ServerReportCtl.java, org.adempiere.base/src/org/compiere/process/ServerProcessCtl.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ReportStarter.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/ReportAction.java, org.adempiere.ui/src/org/compiere/apps/form/PayPrint.java, org.idempiere.test/src/org/idempiere/test/event/EventHandlerTest.java, org.idempiere.test/src/org/idempiere/test/model/ProcessTest.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5695
=> IDEMPIERE-5695 - Process audit doesn't set print language, format, print format on Jasper Reports

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/tree.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6001 …
=> IDEMPIERE-6001 Minor alignment fix for tree and view dashboard gadget

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
=> IDEMPIERE-5952 - Adjust to return IDColumn recordID

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/StatusBar.java
=> IDEMPIERE-5998:In case there is a document link, the status bar does not show a popup when clicked

org.adempiere.base/src/org/compiere/model/MColumnAccess.java, org.adempiere.base/src/org/compiere/model/MFormAccess.java, org.adempiere.base/src/org/compiere/model/MInfoWindowAccess.java, org.adempiere.base/src/org/compiere/model/MProcessAccess.java, org.adempiere.base/src/org/compiere/model/MRecordAccess.java, org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.base/src/org/compiere/model/MRoleIncluded.java, org.adempiere.base/src/org/compiere/model/MRoleOrgAccess.java, org.adempiere.base/src/org/compiere/model/MTableAccess.java, org.adempiere.base/src/org/compiere/model/MTaskAccess.java, org.adempiere.base/src/org/compiere/model/MWindowAccess.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java, org.adempiere.base/src/org/compiere/wf/MWorkflowAccess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5996
=> IDEMPIERE-5996 Record Access is not being updated when a new record is added

org.adempiere.base/src/org/compiere/util/Trx.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6016 …
=> IDEMPIERE-6016:trx timeout make leak connection by call Connection.about but not call Connection.close

org.adempiere.base/src/org/compiere/model/PO.java
Fixed a wrong parenthesis stopping the insert change log from being created
=> IDEMPIERE-5567 Insert Log not being created - fix wrong parenthesis

org.adempiere.base.process/src/org/compiere/process/AllocationReset.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6009
- fix wrong usage of TRIM in postgresql, must use TRUNC
- refactor to use safer methods throwing error on DB exceptions
=> IDEMPIERE-6009 AllocationReset Not Working Correctly

migration/iD11/oracle/202401271430_IDEMPIERE-6018.sql, migration/iD11/postgresql/202401271430_IDEMPIERE-6018.sql, org.adempiere.pipo/src/org/adempiere/pipo2/GridTab2PackExporter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6018
=> IDEMPIERE-6018 Dangerous 2Packs generated with UpdateDictionary=true

migration/iD11/oracle/202401271444_IDEMPIERE-6019.sql, migration/iD11/postgresql/202401271444_IDEMPIERE-6019.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6019
=> IDEMPIERE-6019 Add query to help finding customizations to official dictionary

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Messagebox.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6011 …
=> IDEMPIERE-6011: Allow use Enter key on Input dialog

org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.base/src/org/idempiere/process/MoveClient.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6017?focusedCommentId=50534
=> IDEMPIERE-6017 Fix NPE in MoveClient when a table does not exist

org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordIDEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRecordUUIDEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordIDDialog.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5992
=> IDEMPIERE-5992 - Move the getIdentifier methods from WRecordEditor to MLookup class

org.idempiere.p2/pom.xml, org.idempiere.parent/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-6004 …
=> IDEMPIERE-6004 Upgrade to Tycho 4.0.4

migration/iD11/oracle/202402011900_IDEMPIERE-6027.sql, migration/iD11/postgresql/202402011900_IDEMPIERE-6027.sql, org.idempiere.test/src/org/idempiere/test/AbstractTestCase.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/base/DBTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6027 …
=> IDEMPIERE-6027 Alter column fail with PostgreSQL 16.1

db/postgresql/functions/altercolumn.sql, migration/iD10/oracle/202402031000_IDEMPIERE-4579.sql, migration/iD10/postgresql/202402031000_IDEMPIERE-4579.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4579 …
=> IDEMPIERE-4579 Function altercolumn fails when a role name has a dash

org.adempiere.base/src/org/compiere/model/MBankStatement.java, org.adempiere.base/src/org/compiere/model/MBankStatementLine.java, org.adempiere.base/src/org/compiere/model/MPeriod.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3117
=> IDEMPIERE-3117 Wrong period validation on Bank Statement

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5888
=> IDEMPIERE-5888 Login Preferences are created on System tenant - fix NPE

org.adempiere.base/src/org/compiere/model/MSession.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/FavouriteController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ChangePasswordPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java, org.idempiere.test/src/org/idempiere/test/event/EventHandlerTest.java, org.idempiere.test/src/org/idempiere/test/model/MInfoWindowTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6035 …
=> IDEMPIERE-6035 Use saveCrossTenantSafe instead of PO.setCrossTenantSafe

org.adempiere.base/src/org/compiere/model/MSetup.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6031 …
=> IDEMPIERE-6031 Redundant code in MSetup.createClient method

org.adempiere.base/src/org/compiere/model/MLotCtl.java, org.idempiere.test/src/org/idempiere/test/model/MAttributeSetTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6036
=> IDEMPIERE-6036 Apply same approach to MLotCtl

org.adempiere.base/src/org/compiere/model/MBPartnerLocation.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6039
=> IDEMPIERE-6039 MBPartnerLocation returning Location wrongly from cache when asked to requery

migration/iD11/oracle/202402131228_IDEMPIERE-6042.sql, migration/iD11/postgresql/202402131228_IDEMPIERE-6042.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutPayment.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6042
- set IsReceipt field based on DocType
- avoid throwing error to the user on callout if the currency rate or converted amt are defined with default null
=> IDEMPIERE-6042 Improvements to Payment window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java
=> IDEMPIERE-6041 - Workflow activities on smartphones

migration/iD11/oracle/202401101633_IDEMPIERE-5990.sql, migration/iD11/postgresql/202401101633_IDEMPIERE-5990.sql, org.adempiere.base.process/src/org/compiere/process/BPartnerOrgLink.java
=> IDEMPIERE-5990 Create translation for BPartnerOrgLink process errors

migration/iD11/oracle/202401311524_IDEMPIERE-6026.sql, migration/iD11/postgresql/202401311524_IDEMPIERE-6026.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6026 …
=> IDEMPIERE-6026 - Set Model Cascade

migration/iD12/oracle/202402270843_IDEMPIERE-5859.sql, migration/iD12/postgresql/202402270843_IDEMPIERE-5859.sql
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5859
=> IDEMPIERE-5859 - Fix product multi-attribute setup

org.idempiere.test/src/org/idempiere/test/base/Convert_PostgreSQLTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6053
=> IDEMPIERE-6053 Problem with Convert_PostgreSQLTest running tests in parallel

org.adempiere.base/src/org/compiere/print/DataEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6052
=> IDEMPIERE-6052 Print Format: Format Pattern is not Applied on Grouping/Summary SCRIPT rows

org.adempiere.base/src/org/compiere/print/MPrintFormat.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6061
=> IDEMPIERE-6061 Performance - MPrintFormatItem loading MPrintFormat on constructor

org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6060
=> IDEMPIERE-6060 NPE when creating a Print Format Item using AutomaticPackIn on startup

org.adempiere.base/src/org/compiere/install/TranslationHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6062
=> IDEMPIERE-6062 Wrong query when importing translations / IDEMPIERE-5567

org.idempiere.zk-feature/feature.xml
- Fix deployment issue
https://idempiere.atlassian.net/browse/IDEMPIERE-5949
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, …
=> IDEMPIERE-5949 Datatables.js and Pivot.js Report Viewer

migration/iD12/oracle/202402261300_IDEMPIERE-2981.sql, migration/iD12/oracle/202402261354_IDEMPIERE-2981.sql, migration/iD12/postgresql/202402261300_IDEMPIERE-2981.sql, migration/iD12/postgresql/202402261354_IDEMPIERE-2981.sql, org.adempiere.base.process/src/org/compiere/process/TabCreateFields.java, org.adempiere.base/src/org/adempiere/impexp/GridTabCSVImporter.java, org.adempiere.base/src/org/compiere/db/AdempiereDatabase.java, org.adempiere.base/src/org/compiere/model/GridField.java, org.adempiere.base/src/org/compiere/model/I_Test.java, org.adempiere.base/src/org/compiere/model/MColumn.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/PO_LOB.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.base/src/org/compiere/model/X_Test.java, org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.base/src/org/compiere/util/DB.java, org.adempiere.base/src/org/compiere/util/DisplayType.java, org.adempiere.base/src/org/compiere/util/Util.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WJsonEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultEditorFactory.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java, org.idempiere.test/src/org/idempiere/test/base/JsonFieldTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2981 …
=> IDEMPIERE-2981 - Implement JSON field type

migration/iD12/oracle/202402231412_IDEMPIERE-5985.sql, migration/iD12/postgresql/202402231412_IDEMPIERE-5985.sql, org.adempiere.base/src/org/compiere/model/MPayment.java, org.adempiere.base/src/org/compiere/process/DocumentEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5985 …
=> IDEMPIERE-5985: Reactivation of Payments

org.adempiere.base.callout/src/org/adempiere/base/callout/TableIDCallout.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordIDDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6072
=> IDEMPIERE-6072 Record ID Editor not working well on detail tabs with multi-ID key

org.adempiere.server-feature/utils.unix/unix/DebianInstaller/etc/init.d/idempiere
https://mattermost.idempiere.org/idempiere/pl/ogx7cib4htbmzqnuyairrhs6oa
=> IDEMPIERE-5967 - prerequisite for java 17

migration/iD11/oracle/202403191408_IDEMPIERE-6068.sql, migration/iD11/postgresql/202403191408_IDEMPIERE-6068.sql, org.adempiere.base/src/org/compiere/model/I_C_UOM.java, org.adempiere.base/src/org/compiere/model/X_C_UOM.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6068
=> IDEMPIERE-6068 Add C_UOM.UNCEFACT column

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRadioGroupEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6075 …
=> IDEMPIERE-6075: WRadioGroupEditor - add a method to get Radiogroup

org.adempiere.base/src/org/compiere/model/GridFieldVO.java, org.adempiere.base/src/org/compiere/model/GridTabVO.java, org.adempiere.base/src/org/compiere/model/GridWindowVO.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.idempiere.test/src/org/idempiere/test/adwindow/GridWindowTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6074 …
=> IDEMPIERE-6074 Refinement of GridWindowVO cache

migration/iD11/oracle/202403291639_IDEMPIERE-6077.sql, migration/iD11/postgresql/202403291639_IDEMPIERE-6077.sql, org.adempiere.base/src/org/compiere/model/Query.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6077 …
=> IDEMPIERE-6077: Translation of QueryMoreThanOneRecordsFound

org.adempiere.base/src/org/compiere/acct/Doc_InOut.java, org.adempiere.base/src/org/compiere/model/MFactAcct.java, org.idempiere.test/src/org/idempiere/test/base/InOutTest.java, org.idempiere.test/src/org/idempiere/test/costing/AveragePOCostingTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5847 …
=> IDEMPIERE-5847 Wrong Posting in Shipment

migration/iD11/oracle/202403262247_IDEMPIERE-6040.sql, migration/iD11/postgresql/202403262247_IDEMPIERE-6040.sql, org.adempiere.base.process/src/org/idempiere/process/ImportCSVProcess.java, org.adempiere.base/src/org/adempiere/base/IGridTabImporter.java, org.adempiere.base/src/org/adempiere/impexp/GridTabCSVImporter.java, org.adempiere.base/src/org/compiere/model/I_AD_ImportTemplate.java, org.adempiere.base/src/org/compiere/model/MImportTemplate.java, org.adempiere.base/src/org/compiere/model/X_AD_ImportTemplate.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/CSVImportAction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6040
- Delimiter (Field Separator) configurable
- Quote delimiter configurable
- Fix issue when the UTF-8 file comes with BOM character
=> IDEMPIERE-6040 Improvements for CSV import template

org.adempiere.base/src/org/compiere/model/MStorageOnHand.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6084 …
=> IDEMPIERE-6084 Remove unreachable code in MStorageOnHand

migration/iD11/oracle/202404031429_IDEMPIERE-6086.sql, migration/iD11/postgresql/202404031429_IDEMPIERE-6086.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6086
=> IDEMPIERE-6086 Missing UUID indexes

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/window.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6092 …
=> IDEMPIERE-6092 Attachment dialog: remove hardcoded setStyle call

migration/iD11/oracle/202404081845_IDEMPIERE-6096.sql, migration/iD11/postgresql/202404081845_IDEMPIERE-6096.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6096
=> IDEMPIERE-6096 Implement regexp VFormat

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/QuickGridTabRowRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/QuickGridView.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WQuickForm.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/window.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6093 …
=> IDEMPIERE-6093 WQuickForm: remove hardcoded style call

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-6098
=> IDEMPIERE-6098 - Wrong Null Check in Dashboard Controller

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6096
=> IDEMPIERE-6096 Implement regexp VFormat - improve message

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/DocumentSearchController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/GlobalSearch.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/MenuSearchController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/HeaderPanel.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/application-menu.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6099 …
=> IDEMPIERE-6099 Global Search Enhancements

migration/iD12/oracle/202404051146_IDEMPIERE-6083.sql, migration/iD12/postgresql/202404051146_IDEMPIERE-6083.sql, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/CustomizeUserDefTabGridView.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WCustomizeUserDefTabGridView.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6083
- added "Customize Grid View" menu item to Window Customization > Tab Customization > Process Toolbar (The Gear Toolbar Button) popup menu.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement …
=> IDEMPIERE-6083 Add Customize Grid View form to Window Customization

org.compiere.db.oracle.provider/src/org/adempiere/db/oracle/partition/TablePartitionService.java, org.compiere.db.postgresql.provider/src/org/adempiere/db/postgresql/partition/TablePartitionService.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-6104
=> IDEMPIERE-6104 - Table Partitioning for List Type Key Columns

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocationEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6089 …
=> IDEMPIERE-6089 Address refresh issue

org.adempiere.base-feature/feature.xml, org.adempiere.base-feature/model.generator.launch, org.adempiere.base-feature/packinfolder.app.launch, org.adempiere.base-feature/sign.database.build.launch, org.adempiere.base-feature/synchronize-terminology.app.launch, org.adempiere.base-feature/translation.app.launch, org.adempiere.base/META-INF/MANIFEST.MF, org.adempiere.base/src/org/compiere/util/CCache.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java, org.adempiere.install/install.app.launch, org.adempiere.install/install.console.app.launch, org.adempiere.install/install.silent.app.launch, org.adempiere.server-feature/server.product.functionaltest.launch, org.adempiere.server-feature/server.product.launch, org.adempiere.server-feature/setup/configuration/config.ini, org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.test/idempiere.unit.test.launch, org.idempiere.test/idempiere.unit.test.parallel.launch, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6079 …
=> IDEMPIERE-6079 Implement expire after access policy for cache

org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/GlobalSearch.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/MenuSearchController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/FavoriteSimpleTreeModel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/AbstractDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/IDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/AbstractMenuPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6105 …
=> IDEMPIERE-6105 Implement recently access menu items

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6115
- X ] In hard-to-understand areas, I have commented my code.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task …
=> IDEMPIERE-6115 : Fix NPE in ADTabpanel while selecting a tree item

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6113 …
=> IDEMPIERE-6113 : Date Range boxes on Info Window are too small

.github/workflows/codeql-analysis.yml
[IDEMPIERE-6121](https://idempiere.atlassian.net/browse/IDEMPIERE-6121) …
=> IDEMPIERE-6121:github action fail by tycho update => setup maven to 3.9

org.adempiere.base/src/org/compiere/db/StatementProxy.java, org.adempiere.base/src/org/compiere/model/SystemProperties.java, org.adempiere.base/src/org/compiere/util/Trx.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6125
=> IDEMPIERE-6125 Allow monitoring null transactions on idempiereMonitor

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java
[ProcessParameterPanel - method to get ProcessInfo](https://idempiere.atlassian.net/browse/IDEMPIERE-6126)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. …
=> IDEMPIERE-6126: ProcessParameterPanel - method to get ProcessInfo

org.adempiere.base/src/org/compiere/print/PrintUtil.java, org.adempiere.base/src/org/compiere/util/CLogMgt.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6044
=> IDEMPIERE-6044 CLogMgt.enable not working properly after InitialClientSetup

org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/POInfo.java, org.adempiere.base/src/org/compiere/model/POResultSet.java, org.adempiere.base/src/org/compiere/model/Query.java, org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6122 …
=> IDEMPIERE-6122 Query class to accept a list of columns to select

org.adempiere.base/src/org/compiere/model/SystemProperties.java, org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6128
=> IDEMPIERE-6128 make org.idempiere.db.debug show just native Postgresql by default

org.adempiere.base/src/org/compiere/util/CCache.java, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6079?focusedCommentId=50798
=> IDEMPIERE-6079 fix NPE caused by library ben-manes/caffeine

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6130
=> IDEMPIERE-6130 Show gc information

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/parameter-process.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6127 …
=> IDEMPIERE-6127 : Improve Report Process Parameter for Mobile Screen

org.adempiere.server/build.properties
=> IDEMPIERE-6118 fix broken build

migration/iD11/oracle/202404302320_IDEMPIERE-6123.sql, migration/iD11/postgresql/202404302320_IDEMPIERE-6123.sql, org.adempiere.base/src/org/compiere/model/DataStatusEvent.java, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/issues/IDEMPIERE-6123
=> IDEMPIERE-6123 Query in search window causing slowness and load spikes in the database (FHCA-5356)

org.adempiere.base/src/org/compiere/print/DataEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6137
=> IDEMPIERE-6137 Payment Rule does not appear in reports from Sales Order

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6140
=> IDEMPIERE-6140 Chosen Multiple Selection Table column bug in Info window

migration/iD12/oracle/202405081649_IDEMPIERE-6138.sql, migration/iD12/postgresql/202405081649_IDEMPIERE-6138.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridView.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6138 …
=> IDEMPIERE-6138: freeze any column on grid

migration/iD11/oracle/202404171125_IDEMPIERE-6110.sql, migration/iD11/postgresql/202404171125_IDEMPIERE-6110.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6110?focusedCommentId=50844
=> IDEMPIERE-6110 New Error Message To Indicate When Sales Order has just Freight Product or Charge Freight - fix migration script

migration/iD12/oracle/202405081649_IDEMPIERE-6138.sql, migration/iD12/postgresql/202405081649_IDEMPIERE-6138.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6138?focusedCommentId=50843
=> IDEMPIERE-6138 freeze any column on grid - fix migration scripts

templates/.project
https://idempiere.atlassian.net/browse/IDEMPIERE-6135
=> IDEMPIERE-6135 Create Templates for rapid plugin development

org.adempiere.base.process/src/org/compiere/process/ColumnSync.java, org.adempiere.base/src/org/compiere/model/MColumn.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6142 …
=> IDEMPIERE-6142 Can't add new column to partitioned table

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/GlobalSearch.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6146 …
=> IDEMPIERE-6146 Recently access menu item: minor refresh refinement

org.adempiere.base/src/org/adempiere/util/ModelClassGenerator.java, org.adempiere.base/src/org/adempiere/util/ModelInterfaceGenerator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6149
=> IDEMPIERE-6149 Model[Class|Interface]Generator must have a predictable order independent of the developer language (collation)

org.adempiere.base/src/org/adempiere/impexp/GridTabCSVExporter.java, org.adempiere.base/src/org/adempiere/impexp/GridTabCSVImporter.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/ExportAction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6143
- fix export and import for UUID based tables
- fix ExportAction creating temporary files with the wrong extension
- fix export and import of multi-selection fields IDEMPIERE-6143
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) + IDEMPIERE-6143

org.adempiere.base/src/org/compiere/tools/FileUtil.java, org.adempiere.ui.zk/WEB-INF/src/org/idempiere/ui/zk/report/CSVReportViewerRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/idempiere/ui/zk/report/HTMLReportViewerRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/idempiere/ui/zk/report/PDFReportViewerRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/idempiere/ui/zk/report/XLSReportViewerRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/idempiere/ui/zk/report/XLSXReportViewerRenderer.java, org.idempiere.zk.datatable/src/org/idempiere/zk/datatable/DatatableReportViewerRenderer.java, org.idempiere.zk.pivot/src/org/idempiere/zk/pivot/PivotReportVieweRenderer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6144
=> IDEMPIERE-6144 Can't export a report if the name has less than 3 characters

org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInventory.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInvoice.java, org.adempiere.base.callout/src/org/compiere/model/CalloutMovement.java, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base.callout/src/org/compiere/model/CalloutProduction.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6158
=> IDEMPIERE-6158 Warehouse Purchase Order cannot be completed after change of product

org.adempiere.base.process/src/org/compiere/process/RequisitionPOCreate.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6162
=> IDEMPIERE-6162 Error with Create PO from Requisition for different BPs on multiple lines with same product

org.adempiere.base.callout/src/org/adempiere/model/CalloutRMA.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInvoice.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInvoiceBatch.java, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base/src/org/adempiere/base/DefaultTaxLookup.java, org.adempiere.base/src/org/adempiere/base/ITaxLookup.java, org.adempiere.base/src/org/compiere/model/MInvoiceLine.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java, org.adempiere.base/src/org/compiere/model/MRMALine.java, org.adempiere.base/src/org/compiere/model/Tax.java, org.idempiere.test/META-INF/MANIFEST.MF, org.idempiere.test/OSGI-INF/org.idempiere.test.model.MTaxTest_TaxLookup.xml, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/model/MTaxTest.java, org.idempiere.test/src/org/idempiere/test/model/MTaxTest_TaxLookup.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6159
=> IDEMPIERE-6159 Add drop ship location to ITaxLookup

db/oracle/functions/BOM_PriceLimit.sql, db/oracle/functions/BOM_PriceList.sql, db/oracle/functions/BOM_PriceStd.sql, db/postgresql/functions/BOM_PriceLimit.sql, db/postgresql/functions/BOM_PriceList.sql, db/postgresql/functions/BOM_PriceStd.sql, migration/iD11/oracle/202406072206_IDEMPIERE-6167.sql, migration/iD11/postgresql/202406072206_IDEMPIERE-6167.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6167
=> IDEMPIERE-6167 BOM Price List must search just for Verified BOMs

db/postgresql/functions/dbreplicasyncverifier.sql, db/postgresql/functions/register_migration_script.sql, migration/iD11/oracle/202406072107_IDEMPIERE-6166.sql, migration/iD11/postgresql/202406072107_IDEMPIERE-6166.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6166
- create unique index on dual.dummy for postgresql
=> IDEMPIERE-6166 PostgreSQL DUAL table with more than one record

org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.base/src/org/compiere/process/ServerProcessCtl.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ReportStarter.java, org.adempiere.ui/src/org/compiere/print/ReportCtl.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6168
=> IDEMPIERE-6168 Found problems with jasper setting filename

migration/iD11/oracle/202406131736_IDEMPIERE-6169.sql, migration/iD11/postgresql/202406131736_IDEMPIERE-6169.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6169
=> IDEMPIERE-6169 Performance on AD_ChangeLog with Record_UU

org.adempiere.base/src/org/compiere/model/MUser.java, org.idempiere.test/src/org/idempiere/test/model/MUserTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6170 …
=> IDEMPIERE-6170 MUser.isEMailValid not implemented correctly

migration/iD11/oracle/202406180027_IDEMPIERE-6176.sql, migration/iD11/postgresql/202406180027_IDEMPIERE-6176.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6176
* Inactivated index m_product_bom_uu_idx because m_product_bom is a view
* checked the flag isconstraint for  AD_TablePartition_UU_idx and TestUU_Trl_UU_idx
=> IDEMPIERE-6176 UUID indexes without constraint

org.adempiere.base.process/src/org/compiere/process/OrderCreateProduction.java, org.adempiere.base.process/src/org/compiere/process/OrderLineCreateProduction.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-6174
=> IDEMPIERE-6174 - Create Production from Order process doesn't set BOM Formula

org.adempiere.base/src/org/compiere/model/I_Test.java, org.adempiere.base/src/org/compiere/model/X_Test.java
minor fix - just generate model
=> IDEMPIERE-2981 Implement JSON Field type - generate model for Test

org.adempiere.base/src/org/compiere/print/ReportEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6187
=> IDEMPIERE-6187 Transaction closed when running workflow on certain conditions

migration/iD12/oracle/202407101502_IDEMPIERE-4297.sql, migration/iD12/postgresql/202407101502_IDEMPIERE-4297.sql
=> IDEMPIERE-4297 - Add Status Line Dashboard Examples to GW

org.adempiere.base.process/src/org/compiere/process/TabCreateFields.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6190
=> IDEMPIERE-6190 TabCreateFields.doIt postgresql exception found in log

migration/iD11/oracle/202407061229_IDEMPIERE-6188.sql, migration/iD11/postgresql/202407061229_IDEMPIERE-6188.sql, org.adempiere.base/src/org/compiere/model/I_AD_UserPreference.java, org.adempiere.base/src/org/compiere/model/MGoal.java, org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.base/src/org/compiere/model/MUserPreference.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.base/src/org/compiere/model/X_AD_UserPreference.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/acct/WAcctViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WProcessCtl.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/CalendarWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6188
=> IDEMPIERE-6188 Read-Only Session

org.adempiere.base/src/org/compiere/model/MColumn.java
=> Idempiere 6195

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6196
=> IDEMPIERE-6196 Fix selection columns on several windows

org.adempiere.base/src/org/compiere/util/Env.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5567?focusedCommentId=50971
Do not discover purchase window if the record ID/UU is not set
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - fix zoom

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6199
=> IDEMPIERE-6199 Payment Print/Export cannot set filesuffix depending on the document type

org.adempiere.base/src/org/compiere/util/Env.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-6204
=> IDEMPIERE-6204 - Env.parseVariable returns wrong parsed message if default value is used

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6202
=> IDEMPIERE-6202 Field status that applied to new record is applied to the existing a record too in a specific operation at Window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6209
=> IDEMPIERE-6209 Detail Zoom Across not working

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WEMailDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6212
=> IDEMPIERE-6212 CONTEXT_EMAIL_USER_CC overrides the email user set with CONTEXT_EMAIL_USER_TO in the WEMailDialog

org.idempiere.keikai/src/io/keikai/ui/au/in/TextHeightCommand.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6217
=> IDEMPIERE-6217 An Error Occurred While Uploading the CSV File as an Attachment

migration/iD11/oracle/202408201236_IDEMPIERE-6216.sql, migration/iD11/postgresql/202408201236_IDEMPIERE-6216.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6216
=> IDEMPIERE-6216 Usability - Initial Tenant Setup - Missing required parameters

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6215
=> IDEMPIERE-6215 Advanced Search Error -> Not unique in the ID space of <Window eJzF__g>: Row2

org.adempiere.base/src/org/adempiere/impexp/GridTabCSVImporter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6218 …
=> IDEMPIERE-6218   Failed to import location record when there are multiple region records with the same name

org.adempiere.base/src/org/compiere/process/ProcessInfoUtil.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3294
Fix unit tests broken
=> IDEMPIERE-3294 Process Audit generate unused AD_PInstance_Para (#2439)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WJsonEditor.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java, org.idempiere.test/src/org/idempiere/test/base/Convert_PostgreSQLTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2981?focusedCommentId=51010
https://idempiere.atlassian.net/browse/IDEMPIERE-6227
- Fix the JSON Editor, is sending to the database the value non prettified
=> IDEMPIERE-2981 Implement JSON Field type + IDEMPIERE-6227 - fixes

org.adempiere.base/src/org/compiere/model/MQuery.java, org.adempiere.base/src/org/compiere/print/layout/PrintDataEvaluatee.java, org.adempiere.base/src/org/compiere/util/Env.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5647?focusedCommentId=51018
=> IDEMPIERE-5647 Allow definition of context variables by Role - fix issue not being used in Logic

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6225 …
=> IDEMPIERE-6225 Improve IsSingleRow logic when opening 1 record

migration/iD11/oracle/202409141654_IDEMPIERE-5567.sql, migration/iD11/postgresql/202409141654_IDEMPIERE-5567.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordInfo.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5567?focusedCommentId=51032
- allow generating permalink also for multi-key tables using UUID
- use TableName instead of AD_Table_ID for permalink
- add zoom condition to role for access tables on non-system tenants
- on copy select, prefer to generate using ID than UUID when possible - is easier when copying a select that is needed to search also for children
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - Record Info Improvements

org.adempiere.server-feature/idempiere-server.sh
https://idempiere.atlassian.net/browse/IDEMPIERE-6244
=> IDEMPIERE-6244 Required change on idempiere-server.sh for docker

org.adempiere.base/src/org/compiere/model/MMeasureCalc.java
[IDEMPIERE-5432](https://idempiere.atlassian.net/browse/IDEMPIERE-5432) …
=> IDEMPIERE-5432:Performance Measure Calculation - Improve SQL Definition(cover more case)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java
[IDEMPIERE-6250](https://idempiere.atlassian.net/browse/IDEMPIERE-6250) …
=> IDEMPIERE-6250:NPE when open SortTab

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
[IDEMPIERE-6251](https://idempiere.atlassian.net/browse/IDEMPIERE-6251) …
=> IDEMPIERE-6251:clean status bar error info

migration/iD11/oracle/202409241248_IDEMPIERE-5760.sql, migration/iD11/postgresql/202409241248_IDEMPIERE-5760.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/util/EMail.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5760?focusedCommentId=51058
=> IDEMPIERE-5760 Manage mail.smtp.connectiontimeout and mail.smtp.writetimeout using SysConfig

migration/iD12/oracle/202409241649_IDEMPIERE-6242.sql, migration/iD12/postgresql/202409241649_IDEMPIERE-6242.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.base/src/org/compiere/util/DisplayType.java, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridTabRowRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ConfirmPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Tab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WListItemRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPViews.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WImageEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WImageURLEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultEditorFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/ManageImageCache.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WImageURLDialog.java, org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/layout.js, org.idempiere.zk.breeze.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/button.css.dsp, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/field-editor.css.dsp, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/button.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/field-editor.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6242 …
=> IDEMPIERE-6242 Info window, image fieldtype doesn't work

org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6013?focusedCommentId=51066
- fix queries with alias (like InfoWindow)
- fix InfoWindow issue when the table has no alias
=> IDEMPIERE-6013 Implement a way to filter dinamically records on MRole.addAccessSQL

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WListbox.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6257
- [] I have checked my code and corrected any misspellings
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task …
=> IDEMPIERE-6257: WListbox cannot add total line for Integer

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6211 …
=> IDEMPIERE-6211 Dashboard Goal - Chart doesn't work.

org.adempiere.base/src/org/compiere/print/layout/ImageElement.java, org.adempiere.base/src/org/idempiere/print/renderer/HTMLReportRenderer.java, org.idempiere.zk.datatable/src/org/idempiere/zk/datatable/DatatableReportRenderer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6222 …
=> IDEMPIERE-6222 HTML report not rendering images for Image Format Type

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPMenuTree.java
https://idempiere.atlassian.net/issues/IDEMPIERE-6210?filter=13321 …
=> IDEMPIERE-6210 : Dashboard Menu - not showed

migration/iD11/oracle/202410031525_IDEMPIERE-4297.sql, migration/iD11/postgresql/202410031525_IDEMPIERE-4297.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4297?focusedCommentId=51092
=> IDEMPIERE-4297 reorganize default dashboard

org.adempiere.base/src/org/compiere/acct/Doc.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6260
=> IDEMPIERE-6260 Posting error not creating Notice

org.adempiere.base/src/org/compiere/print/MPrintFormatItem.java, org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/idempiere/ui/zk/report/CSVReportViewerRenderer.java
=> IDEMPIERE-6255:Incorrect column count on datatables

org.adempiere.base/src/org/idempiere/process/MigraID.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6264
=> IDEMPIERE-6264 - other cases with double :: on Error

org.adempiere.base.process/src/org/compiere/process/InvoiceGenerate.java, org.idempiere.test/src/org/idempiere/test/model/InvoiceCustomerTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6263 …
=> IDEMPIERE-6263 Wrong line net amount

org.adempiere.base/src/org/compiere/model/MChart.java, org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ColumnLookup.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6048
=> IDEMPIERE-6048 Check access - based on Heng Sin's PR2485

migration/iD12/oracle/202410181336_IDEMPIERE-6262.sql, migration/iD12/postgresql/202410181336_IDEMPIERE-6262.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/adwindow.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/borderlayout.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/button.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/desktop.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/gadget.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/grid.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/input-element.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/login.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/tab.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/toolbar.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/tree.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/login-info.zul, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/vendor-logo.zul, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/version-info.zul
=> IDEMPIERE-6262 UI Enhancements for Consistency with IceBlue_c Theme

org.adempiere.server/idempiere.jsp, org.adempiere.server/resources/templates/black/styles/template.css, org.adempiere.server/resources/templates/white/styles/template.css
https://idempiere.atlassian.net/browse/IDEMPIERE-6273 …
=> IDEMPIERE-6273 : Idempiere Homepage Responsive

org.adempiere.base.process/src/org/compiere/process/TabCopy.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6276
=> IDEMPIERE-6276 Window > Tab > Copy Tab Fields - must copy just the missing fields

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6277
=> IDEMPIERE-6277 When deleting a Recent Item the list is shrunk, instead of showing the next recent item

migration/iD12/oracle/202410271703_IDEMPIERE-6278.sql, migration/iD12/postgresql/202410271703_IDEMPIERE-6278.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6278
- add order by to window/process/infowindow customization to mimic the order of the window/process/infowindow parents
- add order by AD_Language to _Trl tabs mising order by except Tenant Messages which is ordered by message-value + language
=> IDEMPIERE-6278 Improve Order By on Windows

org.adempiere.base/src/org/adempiere/model/MInfoProcess.java, org.adempiere.base/src/org/adempiere/util/GridRowCtx.java, org.adempiere.base/src/org/compiere/model/GridField.java, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTabVO.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/InfoColumnVO.java, org.adempiere.base/src/org/compiere/model/InfoRelatedVO.java, org.adempiere.base/src/org/compiere/model/MInfoColumn.java, org.adempiere.base/src/org/compiere/model/MQuery.java, org.adempiere.base/src/org/compiere/model/MZoomCondition.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/print/layout/PrintDataEvaluatee.java, org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.base/src/org/compiere/util/Evaluator.java, org.adempiere.base/src/org/idempiere/expression/logic/EvaluationVisitor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADSortTab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ToolbarCustomButton.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ToolbarProcessButton.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WInfoWindowListItemRenderer.java, org.idempiere.printformat.editor/src/org/idempiere/printformat/editor/ui/WPrintFormatEditor.java, org.idempiere.test/src/org/idempiere/test/base/EnvTest.java, org.idempiere.test/src/org/idempiere/test/base/LogicExpressionTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4827 …
=> IDEMPIERE-4827 Unify Evaluatee Implementation

org.adempiere.base/src/org/compiere/model/MOrder.java
=> IDEMPIERE-6284 - Order is not validating user values when 0 is set

org.adempiere.base/src/org/compiere/model/MTable.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5174?focusedCommentId=51192
=> IDEMPIERE-5174 Disable System User - remove AD_User from MTable.isZeroIDTable

org.adempiere.server-feature/hazelcast-template.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-6279?focusedCommentId=51194
=> IDEMPIERE-6279 Problem with hazelcast with multiple server running on localhost postgres on same network

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Tab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6289 …
=> IDEMPIERE-6289 : missing icon on tab list

org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6288 …
=> IDEMPIERE-6288 - Fix script in format item

org.adempiere.base/src/org/compiere/model/MAttributeSetInstance.java, org.adempiere.base/src/org/compiere/model/MReportCube.java, org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/compiere/model/MUser.java, org.adempiere.base/src/org/compiere/util/DB.java, org.adempiere.base/src/org/compiere/wf/MWorkflow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WFEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/grid/WBPartner.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordAccessDialog.java, org.adempiere.ui/src/org/compiere/apps/form/Archive.java, org.adempiere.ui/src/org/compiere/apps/form/TreeMaintenance.java, org.adempiere.ui/src/org/idempiere/apps/form/BOMDrop.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/base/DBTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6290 …
=> IDEMPIERE-6290 Improvement of DB.getKeyNamePair method

org.adempiere.base/src/org/compiere/model/MAttachment.java
- add trim of spaces in attachment url
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, …
=> IDEMPIERE-6256 Get image through url from attachment

org.adempiere.base/src/org/compiere/wf/MWFNodePara.java
=> IDEMPIERE-6296 -Fixed process workflow node using inactive parameters

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/RelatedInfoWindow.java
=> IDEMPIERE-6297 Fix RelatedInfoWindow Order By

migration/iD12/oracle/202411141102_IDEMPIERE-6298.sql, migration/iD12/postgresql/202411141102_IDEMPIERE-6298.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6298 …
=> IDEMPIERE-6298 : custom delete message for recent item widget

org.adempiere.base/src/org/compiere/model/GridField.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6294 …
=> IDEMPIERE-6294 default expression for multi-select fields

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Tab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6289 …
=> Idempiere 6289 missing icon on tab list

org.adempiere.base/src/org/adempiere/base/sso/ISSOPrincipalService.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.idempiere.ui.sso.oidc/src/org/idempiere/ui/sso/oidc/service/OIDCPrincipalService.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6295 …
=> IDEMPIERE-6295 OIDC SSO: logout not working for Amazon Cognito

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/button.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/form.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6302 …
=> IDEMPIERE-6302 : Update default button style

org.adempiere.ui.zk/OSGI-INF/defaultfindwindowfactory.xml, org.adempiere.ui.zk/OSGI-INF/org.adempiere.webui.factory.DefaultFindWindowFactory.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/Extensions.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultFindWindowFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/IFindWindowFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
=> IDEMPIERE-6283 Add support for extending FindWindow via plugins using IFindWindowFactory

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/MenuSearchController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6307 …
=> IDEMPIERE-6307: MenuSearch doesn't display tooltip

org.adempiere.base/src/org/adempiere/exceptions/ProductNotOnPriceListException.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.base/src/org/compiere/wf/WFActivityManage.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6305
=> IDEMPIERE-6305 Improve some Error Messages

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditorPopupMenu.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java, org.adempiere.ui/src/org/compiere/print/DrillReportCtl.java
https://idempiere.atlassian.net/issues/IDEMPIERE-5946 …
=> IDEMPIERE-5946 : Drill Assistant Error - For input string: "null"

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WTask.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6309
=> IDEMPIERE-6309 Output of task is better formatted as a console font

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/CalendarWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/calendar/calendar.css
https://idempiere.atlassian.net/browse/IDEMPIERE-6306 …
=> IDEMPIERE-6306 : Improve Calendar UI

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WTreeBOM.java, org.adempiere.ui/src/org/compiere/apps/form/TreeBOM.java, org.idempiere.test/src/org/idempiere/test/form/BOMViewerFormTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6308 …
=> IDEMPIERE-6308 Refactoring of BOM Viewer

org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordInfo.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6299 …
=> IDEMPIERE-6299 : Set Record Info View as a user preference

migration/iD12/oracle/202411251514_IDEMPIERE-6293.sql, migration/iD12/postgresql/202411251514_IDEMPIERE-6293.sql
[ https://idempiere.atlassian.net/browse/IDEMPIERE-6293 ] …
=> IDEMPIERE-6293: Theme variations - Unique Index

migration/iD11/oracle/202411260821_IDEMPIERE-6317.sql, migration/iD11/postgresql/202411260821_IDEMPIERE-6317.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6317 …
=> IDEMPIERE-6317 - Create message for errors in msysconfig

migration/processes_post_migration/oracle/01_add_missing_Translations.sql, migration/processes_post_migration/postgresql/01_add_missing_translations.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-99
=> IDEMPIERE-99 01_add_missing_Translations.sql does not create UUIDs

db/oracle/functions/BOM_PriceLimit.sql, db/oracle/functions/BOM_PriceList.sql, db/oracle/functions/BOM_PriceStd.sql, db/oracle/functions/BOM_Qty_OnHand.sql, db/oracle/functions/BOM_Qty_OnHandForReservation.sql, db/oracle/functions/BOM_Qty_Ordered.sql, db/oracle/functions/BOM_Qty_Reserved.sql, db/postgresql/functions/BOM_PriceLimit.sql, db/postgresql/functions/BOM_PriceList.sql, db/postgresql/functions/BOM_PriceStd.sql, db/postgresql/functions/BOM_Qty_OnHand.sql, db/postgresql/functions/BOM_Qty_OnHandForReservation.sql, db/postgresql/functions/BOM_Qty_Ordered.sql, db/postgresql/functions/BOM_Qty_Reserved.sql, db/postgresql/functions/ProductAttribute.sql, migration/iD11/oracle/202411301155_IDEMPIERE-6329.sql, migration/iD11/postgresql/202411301155_IDEMPIERE-6329.sql, org.idempiere.test/src/org/idempiere/test/base/GetBOMFunctionsTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6329
=> IDEMPIERE-6329 Bug in BOM* SQL functions not getting the correct BOM children

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/BackgroundJobCallable.java
[IDEMPIERE-6323](https://idempiere.atlassian.net/browse/IDEMPIERE-6323) …
=> IDEMPIERE-6323 fix Process Run as Job doesn't create change log

org.adempiere.base/src/org/compiere/model/MChart.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6332
=> IDEMPIERE-6332 Implement MChart.getData to return the data used to paint the chart

org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/adwindow.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/gadget.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6333 …
=> IDEMPIERE-6333 Refine line height of help content

migration/iD12/oracle/202412061426_IDEMPIERE-6338.sql, migration/iD12/postgresql/202412061426_IDEMPIERE-6338.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6338 …
=> IDEMPIERE-6338: Improve MFA Registered Device

org.adempiere.base/src/org/compiere/model/MChart.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6332
=> IDEMPIERE-6332 Implement MChart.getData to return the data used to paint the chart - add chart type

org.adempiere.base/src/org/compiere/wf/MWFActivity.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6331 …
=> IDEMPIERE-6331 - (MWFActivity) SaveError

migration/iD12/oracle/202412101939_IDEMPIERE-5136.sql, migration/iD12/postgresql/202412101939_IDEMPIERE-5136.sql, org.adempiere.base/src/org/adempiere/model/GenericPO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5136
- add warning message about SysConfig
=> IDEMPIERE-5136 Set Messages at tenant level

org.adempiere.base/src/org/compiere/model/MReference.java
[ [Please copy here the link to the related Jira ticket](https://idempiere.atlassian.net/browse/IDEMPIERE-6337) ]
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task …
=> IDEMPIERE-6337: Add cache for MReference using UU

org.adempiere.base/src/org/compiere/model/MMailText.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6324 …
=> IDEMPIERE-6324 Add markdown support to email template

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6341
=> IDEMPIERE-6341 Automatic Close tabs on Chrome #resolve

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WEMailDialog.java, org.idempiere.zk.breeze.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/about.css.dsp, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/font-icons.css.dsp, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/window-size.css.dsp, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/about.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/font-icons.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/window-size.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6343 …
=> IDEMPIERE-6343 : Improve About Window UI

org.adempiere.base/src/org/compiere/process/DatabaseTableRename.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6342
=> IDEMPIERE-6342 Issues when renaming a table that already has records saved

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4734
=> IDEMPIERE-4734 german mac keyboard characters (@€) accessed by ALT-L / ALT-E are not captured

org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/theme.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6347 …
=> IDEMPIERE-6347 Update default font-family setting

Credits.html, org.adempiere.server/resources/templates/white/styles/template.css
[ Please copy here the link to the related Jira ticket ] …
=> IDEMPIERE-6348 - Fix release image size in white template

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/IDesktop.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3989?focusedCommentId=51398
=> IDEMPIERE-3989 fast entity type identification - backward compatibility

migration/iD12/oracle/202412261358_IDEMPIERE-6349.sql, migration/iD12/postgresql/202412261358_IDEMPIERE-6349.sql, org.adempiere.base/src/org/compiere/model/I_C_Country.java, org.adempiere.base/src/org/compiere/model/X_C_Country.java
- added new columns/fields for C_Country.M49Code and ISOCountryCodeAlpha3
- assign codes values for 249 official countries
- deactivate Netherlands Antilles record
- improve Help of CountryCode removing/replacing broken links
https://idempiere.atlassian.net/browse/IDEMPIERE-6349
=> IDEMPIERE-6349 Add M49 country codes to the C_Country table (FHCA-6138)

org.adempiere.base/src/org/compiere/util/Login.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6354
=> IDEMPIERE-6354 User Locking mechanism broken

org.adempiere.base/src/org/compiere/model/MRefList.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6336?focusedCommentId=51401
=> IDEMPIERE-6336 Fix NPE on MRefList.getList

RUN_SyncDBDev.sh
https://idempiere.atlassian.net/browse/IDEMPIERE-6362
- [X ] I have performed a self-review of my own code
- [X ] I have checked my code and corrected any misspellings
- [X ] My changes generate no new warnings
- [X ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the …
=> IDEMPIERE-6362 Update SyncDB for MacOsx Compatibility

org.adempiere.base/src/org/compiere/model/GridTab.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2449
=> IDEMPIERE-2449 NPE on GridTab.m_DataStatusEvent / change approach from volatile to synchronized

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6367
=> IDEMPIERE-6367 Problem rendering info window columns vs gridfields

org.adempiere.base/src/org/compiere/model/MTask.java, org.adempiere.base/src/org/compiere/util/Task.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6368
=> IDEMPIERE-6368 Improve execution of Task

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/MenuSearchController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6364 …
=> IDEMPIERE-6364: Make Menu Search Highlight Accent Insensitive

org.adempiere.base/src/org/compiere/model/MSchedule.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4302
=> IDEMPIERE-4302 - remove unnecessary code

org.idempiere.test/src/org/idempiere/test/jasper/PrintWithinProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6371 …
=> IDEMPIERE-6371 : testPrintWithLocalFile unit test failed on windows

org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java
- fix issue not being able to delete orphan attachments
https://idempiere.atlassian.net/browse/IDEMPIERE-6314?focusedCommentId=51430
=> IDEMPIERE-6314 Issues with attachment on System records

migration/iD12/oracle/202501091312_IDEMPIERE-6375.sql, migration/iD12/postgresql/202501091312_IDEMPIERE-6375.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6375
- - [x] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld. …
=> IDEMPIERE-6375 - Add missing quantities to RV_Storage_per_product view

org.adempiere.base/src/org/compiere/model/MRoleOrgAccess.java, org.adempiere.base/src/org/compiere/model/MUserOrgAccess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6380
=> IDEMPIERE-6380 MRoleOrgAccess and MUserOrgAccess .get are returning inactive records

org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/button.css.dsp
https://idempiere.atlassian.net/issues/IDEMPIERE-6339 …
=> IDEMPIERE-6339 : Focused button is not highlighted with the new theme

org.adempiere.server/META-INF/MANIFEST.MF, org.adempiere.ui.zk/META-INF/MANIFEST.MF, org.idempiere.felix.webconsole/META-INF/MANIFEST.MF, org.idempiere.webservices/META-INF/MANIFEST.MF
- use unpacked deployment for WAB
https://idempiere.atlassian.net/browse/IDEMPIERE-6369 …
=> IDEMPIERE-6369 iDempiere 12 server startup error on Windows

org.idempiere.zk.billboard.chart/src/org/idempiere/zk/billboard/chart/ChartBuilder.java, org.idempiere.zk.billboard/src/org/idempiere/zk/billboard/Billboard.java, org.idempiere.zk.billboard/src/web/js/zul/billboard/Billboard.js
https://idempiere.atlassian.net/browse/IDEMPIERE-6379
=> IDEMPIERE-6379 Charts not honoring Display Legend flag

org.adempiere.base/src/org/adempiere/model/GenericPO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6384
=> IDEMPIERE-6384 Implement GenericPO UUID constructors

migration/iD12/oracle/202501131651_IDEMPIERE-6383.sql, migration/iD12/postgresql/202501131651_IDEMPIERE-6383.sql, org.adempiere.base/src/org/compiere/model/MInvoiceLine.java, org.adempiere.base/src/org/compiere/model/MOrderLandedCost.java
[ IDEMPIERE-6363 ](https://idempiere.atlassian.net/browse/IDEMPIERE-6383) …
=> IDEMPIERE-6383 Create Message Record for "Total Base Value is 0"

org.adempiere.base/src/org/compiere/util/AmtInWords_ES.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6388 …
=> IDEMPIERE-6388: Fix some errors in AmtInWords_ES

org.adempiere.base/src/org/compiere/model/MBankTransfer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6391 …
=> IDEMPIERE-6391 : SaveError when Create Bank Transfer Via REST

org.adempiere.base/src/org/compiere/model/MLookupFactory.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6365 …
=> IDEMPIERE-6365: RefTable with not ID as KeyColumn can't be translated

migration/iD12/oracle/202501170030_IDEMPIERE-6386.sql, migration/iD12/postgresql/202501170030_IDEMPIERE-6386.sql, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/CompositeADTabbox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WQuickForm.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6386
=> IDEMPIERE-6386 Detail tabs don't have control over slow or big queries (FHCA-6139)

org.adempiere.ui.zk/WEB-INF/src/fi/jawsy/jawwa/zk/atmosphere/AtmosphereServerPush.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6398
=> IDEMPIERE-6398 Server crash after a user without report permission tries to run a report

org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/CompiereService.java
- implement suggestion from Heng Sin
https://idempiere.atlassian.net/browse/IDEMPIERE-6399
=> IDEMPIERE-6399 Deadlock at Web service

Credits.html
https://idempiere.atlassian.net/issues/IDEMPIERE-4580
=> IDEMPIERE-4580 - Update credits file with new dev&Co name and logo

org.adempiere.base/src/org/compiere/model/MPayment.java
[Jira Ticket](https://idempiere.atlassian.net/browse/IDEMPIERE-6403) …
=> IDEMPIERE-6403 - Drafted payment cannot be deleted after printing

org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6400
=> IDEMPIERE-6400 Hide Print, Archive and report menu options and buttons for roles that cannot report

migration/iD13/oracle/202501290635_IDEMPIERE-6401.sql, migration/iD13/postgresql/202501290635_IDEMPIERE-6401.sql, org.adempiere.base/src/org/compiere/Adempiere.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.idempiere.zk.breeze.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.breeze.theme/src/web/theme/default/zul/login/login-info.zul, org.idempiere.zk.breeze.theme/src/web/theme/default/zul/login/login-left.zul, org.idempiere.zk.breeze.theme/src/web/theme/default/zul/login/login-links.zul, org.idempiere.zk.breeze.theme/src/web/theme/default/zul/login/vendor-logo.zul, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/login-info.zul, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/login-left.zul, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/login-links.zul, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/login/vendor-logo.zul
https://idempiere.atlassian.net/browse/IDEMPIERE-6401 …
=> IDEMPIERE-6401 : user can select demo user on login for testing purpose

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6409
=> IDEMPIERE-6409 Charts not rendered on certain conditions

migration/iD12/oracle/202501301404_IDEMPIERE-6407.sql, migration/iD12/postgresql/202501301404_IDEMPIERE-6407.sql, org.adempiere.ui/src/org/compiere/apps/form/PaySelect.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6407
=> IDEMPIERE-6407 Payment Selection (Manual) - NPE when there is no conversion rate

org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6436
=> IDEMPIERE-6436 Error inserting permission record for System Administrator role (FHCA-6351)

org.adempiere.base.process/src/org/compiere/process/SequenceCheck.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6440
=> IDEMPIERE-6440 Sequence Check is creating ID sequence for non-existing column

org.adempiere.base/src/org/compiere/model/MOrgInfo.java
[IDEMPIERE-6442:can't edit org_info of org "*"](https://idempiere.atlassian.net/browse/IDEMPIERE-6442)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If …
=> IDEMPIERE-6442:can't edit org_info of org "*"

org.adempiere.base/src/org/compiere/print/DataEngine.java
[IDEMPIERE-6443 ](https://idempiere.atlassian.net/browse/IDEMPIERE-6443) …
=> IDEMPIERE-6443:address(C_Location) is not print when city is empty(null)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/QuickGridTabRowRenderer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6385 …
=> IDEMPIERE-6385 [QuickForm] - Problem with quickform sorting

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/SimplePDFViewer.java
[IDEMPIERE-6445](https://idempiere.atlassian.net/browse/IDEMPIERE-6445) …
=> IDEMPIERE-6445:SimplePDFViewer don't respect agrument title (file name)

org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java, org.idempiere.test/src/org/idempiere/test/base/EnvTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4827?focusedCommentId=52488
=> IDEMPIERE-4827 Unify Evaluatee Implementation - fix import CSV process

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WFileImport.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6462
=> IDEMPIERE-6462 Zoom to loaded data after Import File Loader

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
[Jira Ticket ](https://idempiere.atlassian.net/browse/IDEMPIERE-6408) …
=> IDEMPIERE-6408 Problem when sorting columns in an Info Window with Distinct

org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/field-editor.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6457
=> IDEMPIERE-6457 Asterisk always colored in red for mandatory fields

org.adempiere.server-feature/jettyhome/etc/jetty-template.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-6464
=> IDEMPIERE-6464 Hide Jetty version from test.idempiere.org/adempiere

org.adempiere.base/src/org/adempiere/model/POWrapper.java
[IDEMPIERE-6474:improve POWrapper to use default function of inteface](https://idempiere.atlassian.net/browse/IDEMPIERE-6474)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a …
=> IDEMPIERE-6474:improve POWrapper to use default function of inteface

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6488 …
=> Idempiere 6488

org.adempiere.base.process/src/org/compiere/process/InvoiceGenerate.java
[Jira ticket - 6478 ](https://idempiere.atlassian.net/browse/IDEMPIERE-6478)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, …
=> IDEMPIERE-6478 - InvoiceGenerate Consolidating Sales Order from Different Organizations

org.idempiere.test/org.idempiere.test.iml
https://idempiere.atlassian.net/browse/IDEMPIERE-5150 …
=> IDEMPIERE-5150 Support development with IntelliJ

org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/util/CCache.java, org.adempiere.base/src/org/compiere/util/CacheChangeListener.java, org.adempiere.base/src/org/compiere/util/CacheInterface.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java, org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java, org.adempiere.base/src/org/compiere/util/ResetCacheCallable.java, org.idempiere.test/src/org/idempiere/test/model/AnnotationColumnCalloutFactoryTest.java, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6506 …
=> IDEMPIERE-6506 Translation cache not reset after update by user

org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6513
=> IDEMPIERE-6513 Error installing Cascade Delete plugin in release-12

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/InfoManager.java
[IDEMPIERE-6425](https://idempiere.atlassian.net/browse/IDEMPIERE-6425) …
=> IDEMPIERE-6425:service cache make wrong order of service ranking (IInfoFactory case)

org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/font-icons.css.dsp
https://idempiere.atlassian.net/issues/IDEMPIERE-6509 …
=> IDEMPIERE-6509 : Inconsistency on arrow to navigate on Detail Pane

org.adempiere.base/src/org/compiere/model/MInvoice.java, org.adempiere.base/src/org/compiere/model/MOrder.java
[Jira Ticket - 6476](https://idempiere.atlassian.net/browse/IDEMPIERE-6476) …
=> IDEMPIERE-6476 - Payment schedule is not getting updated with header record organization

org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6523
=> IDEMPIERE-6523 Migration script comment is not appearing in Preference

org.adempiere.base/src/org/compiere/model/SystemProperties.java, org.adempiere.base/src/org/compiere/util/Util.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5795?focusedCommentId=54534
=> IDEMPIERE-5795 DeveloperMode context variable - minor, move to SystemProperties

migration/iD12/oracle/202505011526_IDEMPIERE-6526.sql, migration/iD12/postgresql/202505011526_IDEMPIERE-6526.sql, org.adempiere.base/src/org/adempiere/impexp/AbstractXLSXExporter.java, org.adempiere.base/src/org/adempiere/print/export/PrintDataXLSXExporter.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6526
=> IDEMPIERE-6526 Performance improvement exporting to XLSX

migration/iD12/oracle/202505021601_IDEMPIERE-6433.sql, migration/iD12/postgresql/202505021601_IDEMPIERE-6433.sql
https://idempiere.atlassian.net/issues/IDEMPIERE-6433
=> IDEMPIERE-6433 Fill Getting Started box

org.adempiere.base/src/org/compiere/model/GridWindowVO.java
https://idempiere.atlassian.net/issues/IDEMPIERE-6529 …
=> IDEMPIERE-6529: Wrong cache for Window Names

org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/UserPanel.java, org.idempiere.zk.breeze.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/desktop.css.dsp, org.idempiere.zk.breeze.theme/src/web/theme/default/zul/desktop/header.zul, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/desktop.css.dsp, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/desktop/header.zul
https://idempiere.atlassian.net/browse/IDEMPIERE-6413
=> IDEMPIERE-6413 Visually differentiate environments

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6538
=> IDEMPIERE-6538 Info Window error sorting by ASI

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java
Set MaxAge and HttpOnly for MFA device cookies
https://idempiere.atlassian.net/browse/IDEMPIERE-6537
=> IDEMPIERE-6537

org.adempiere.base/src/org/compiere/model/MRole.java
[ IDEMPIERE-6539 ](https://idempiere.atlassian.net/browse/IDEMPIERE-6539) …
=> IDEMPIERE-6539 - [Role Access Update] - Created by / Updated by

RUN_ImportIdempiereDev.sh, RUN_SyncDBDev.sh, org.adempiere.server-feature/utils.unix/postgresql/ImportIdempiere.sh
https://idempiere.atlassian.net/browse/IDEMPIERE-6521?focusedCommentId=55095
=> IDEMPIERE-6521 Create RUN_ImportIdempiereDev.sh

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WChat.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6544
=> IDEMPIERE-6544 Chat window hides thread on Reply

org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPostIt.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6543
=> IDEMPIERE-6543 Error with Post-It on AD_User_Roles (FHCA)

org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
[IDEMPIERE-6546](https://idempiere.atlassian.net/browse/IDEMPIERE-6546)
[IDEMPIERE-6546]: https://idempiere.atlassian.net/browse/IDEMPIERE-6546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IDEMPIERE-6546 Allow exporting tree definition with 2Pack

migration/iD12/oracle/202505161145_IDEMPIERE-6549.sql, migration/iD12/postgresql/202505161145_IDEMPIERE-6549.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base/src/org/compiere/model/I_M_Warehouse.java, org.adempiere.base/src/org/compiere/model/X_M_Warehouse.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6549
- - [x] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld. …
=> IDEMPIERE-6549 - Add option to Disable Insufficient Inventory Popup

migration/iD12/oracle/202505292158_IDEMPIERE-6563.sql, migration/iD12/postgresql/202505292158_IDEMPIERE-6563.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.pipo/src/org/adempiere/pipo2/PackInNotifier.java, org.adempiere.pipo/src/org/adempiere/pipo2/PackInProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6563
=> IDEMPIERE-6563 Attach stacktrace and Unresolved to the 2pack as error_yyyymmddhhmmss.log (FHCA)

org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/acct/AccountingSchemaValidRangeTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6254 …
=> IDEMPIERE-6254 : Adding Junit test cases

org.adempiere.base/src/org/compiere/model/MInvoice.java, org.idempiere.test/src/org/idempiere/test/model/InvoiceCustomerTest.java
https://idempiere.atlassian.net/issues/IDEMPIERE-6067 …
=> IDEMPIERE-6067: Reactivation of Invoices - fix OrderLine QtyInvoiced

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6580
=> IDEMPIERE-6580 Multiple tab records and cannot be closed

org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6587
=> IDEMPIERE-6587 Product Info showing stock when no warehouse is selected

org.adempiere.base/src/org/compiere/model/MQuery.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6595
=> IDEMPIERE-6595 Enable Using Virtual Columns as Report Parameters

migration/iD12/oracle/202506201116_IDEMPIERE-6592.sql, migration/iD12/postgresql/202506201116_IDEMPIERE-6592.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6592
=> IDEMPIERE-6592 T_Spool wrongly defined as view in dictionary

migration/iD12/oracle/202506200917_IDEMPIERE-6591.sql, migration/iD12/postgresql/202506200917_IDEMPIERE-6591.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6591
- [] I have performed a self-review of my own code
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. …
=> IDEMPIERE-6591 : Can't delete records created through Recurring

org.adempiere.base/src/org/compiere/util/EMail.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6599
=> IDEMPIERE-6599 Enable mail session debug based on mail.debug

org.adempiere.base/src/org/adempiere/exceptions/DBException.java, org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6602
=> IDEMPIERE-6602 Excessive logging of Invalid Column

org.idempiere.test/src/org/idempiere/test/form/MergeFormTest.java, org.idempiere.test/src/org/idempiere/test/model/Allocation2ndAcctSchemaTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6594 …
=> IDEMPIERE-6594 Unit Test: Use Mockito.mockStatic to reduce the need to create and delete PO outside of transaction

org.adempiere.server-feature/utils.unix/unix/DebianInstaller/etc/init.d/idempiere
https://idempiere.atlassian.net/browse/IDEMPIERE-6607
=> IDEMPIERE-6607 Support Debian Installer in arm

migration/iD13/oracle/202507041539_IDEMPIERE-6534.sql, migration/iD13/postgresql/202507041539_IDEMPIERE-6534.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6534
=> IDEMPIERE-6534 Rename "Reset Locked Account" to "Unlock Account"

migration/iD13/oracle/202507041519_IDEMPIERE-5088.sql, migration/iD13/postgresql/202507041519_IDEMPIERE-5088.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5088?focusedCommentId=57638
=> IDEMPIERE-5088 Fix predefined context in bank/cash transfer window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ADForm.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6611
=> IDEMPIERE-6611 Predefined Context Variables are not being cleared for forms

migration/iD13/oracle/202411271710_IDEMPIERE-6304.sql, migration/iD13/postgresql/202411271710_IDEMPIERE-6304.sql, org.adempiere.base/src/org/adempiere/base/sso/ISSOPrincipalService.java, org.adempiere.base/src/org/adempiere/base/sso/SSOUtils.java, org.adempiere.base/src/org/compiere/model/I_SSO_PrincipalConfig.java, org.adempiere.base/src/org/compiere/model/MSSOPrincipalConfig.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/X_SSO_PrincipalConfig.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/sso/filter/SSOWebUIFilter.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/LoginWindow.java, org.idempiere.ui.sso.oidc/src/org/idempiere/ui/sso/oidc/service/OIDCPrincipalService.java, org.idempiere.zk.breeze.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/login.css.dsp, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/login.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6304 …
=> IDEMPIERE-6304: Multiple SSO provider support

migration/iD13/oracle/202507161744_IDEMPIERE-6628.sql, migration/iD13/postgresql/202507161744_IDEMPIERE-6628.sql, org.adempiere.base/src/org/compiere/model/MUserQuery.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/find-window.css.dsp, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/find-window.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6628
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld. -> https://wiki.idempiere.org/en/NF13_Advanced_Options_For_Saved_Queries
=> IDEMPIERE-6628 - Improve advanced options for Saved Queries on Find Window

org.adempiere.base/src/org/compiere/model/MAuthorizationCredential.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6631
=> IDEMPIERE-6631 Allow extra parameters in AD_AuthorizationProvider.AuthorizationEndpoint

org.adempiere.base/src/org/compiere/impexp/OFXBankStatementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6639
=> IDEMPIERE-6639 OFXFileBankStatementLoader - ErrorReadingData - Stream closed

org.compiere.db.oracle.provider/src/org/adempiere/db/oracle/config/ConfigOracle.java, org.compiere.db.postgresql.provider/src/org/adempiere/db/postgresql/config/ConfigPostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6641
=> IDEMPIERE-6641 Cryptic error on silent-setup-alt.sh when ADEMPIERE_DB_SERVER is not reachable

migration/iD12/oracle/202507312046_IDEMPIERE-6644.sql, migration/iD12/postgresql/202507312046_IDEMPIERE-6644.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6644
=> IDEMPIERE-6644 Fix some wrong defaults for EntityType

org.adempiere.base/src/org/compiere/acct/DocManager.java, org.adempiere.base/src/org/compiere/model/MMatchInv.java
[IDEMPIERE-6614](https://idempiere.atlassian.net/browse/IDEMPIERE-6614)
Performance improvement for back-dated costing process
Changes:
- Added a check to ensure the back-date process only runs after all matched PO and matched invoice documents are posted for a material receipt or purchase invoice
- Retrieve matched invoices by account date when reposting the matched invoices of an invoice
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change …
=> IDEMPIERE-6614 Performance improvement for back-dated costing process

org.adempiere.base/src/org/compiere/model/MRole.java, org.idempiere.test/src/org/idempiere/test/model/MRoleMockedTest.java, org.idempiere.test/src/org/idempiere/test/model/MRoleTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6647
=> IDEMPIERE-6647 - Extend Unit Tests for MRole

RUN_ImportIdempiereDev.sh
https://idempiere.atlassian.net/browse/IDEMPIERE-6648?focusedCommentId=58825
- Fix RUN_ImportIdempiereDev.sh according to new order of parameters
=> IDEMPIERE-6648 Ensure all scripts can run with an alternate db admin user (DAD-62)

org.adempiere.server-feature/utils.unix/setVar.sh
https://idempiere.atlassian.net/browse/IDEMPIERE-6657
=> IDEMPIERE-6657 Setup error when the DB password is 57 chars or longer

org.adempiere.base/src/org/compiere/Adempiere.java, org.adempiere.base/src/org/compiere/util/CLogger.java, org.idempiere.test/src/org/idempiere/test/base/CLoggerTest.java, org.idempiere.test/src/org/idempiere/test/model/MArchiveTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6645 …
=> IDEMPIERE-6645 Error message being cleared due to concurrency issue

org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6660 …
=> IDEMPIERE-6660: Temporary and AD_SysConfig tables should not fill Value/DocumentNo columns

org.adempiere.base/src/org/compiere/model/SystemProperties.java, org.adempiere.base/src/org/compiere/util/Secure.java, org.adempiere.base/src/org/compiere/util/SecureEngine.java, org.idempiere.test/src/org/idempiere/test/base/MySecure.java, org.idempiere.test/src/org/idempiere/test/base/SecureInterfaceTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6664 …
=> IDEMPIERE-6664 Secure engine extensibility improvements

org.adempiere.base/src/org/compiere/model/GridField.java
[ 6668 ](https://idempiere.atlassian.net/browse/IDEMPIERE-6668) …
=> IDEMPIERE-6668 Field holding invalid data

org.adempiere.base/src/org/compiere/model/DataStatusEvent.java, org.adempiere.base/src/org/compiere/model/GridTab.java
[ 6672 ](https://idempiere.atlassian.net/browse/IDEMPIERE-6672) …
=> IDEMPIERE-6672 The same event triggered in less than 200ms prevents callouts from being executed

org.adempiere.base/src/org/compiere/model/MColumn.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6676 …
=> IDEMPIERE-6676 Review the PO.getKeyColumns for UUID tables

org.adempiere.ui/src/org/compiere/print/ReportCtl.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6673 …
=> IDEMPIERE-6673 Jasper Linked to Print Format Being Generated Blank

org.adempiere.base/src/org/compiere/model/MUserPreference.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6683
=> IDEMPIERE-6683 Concurrent client requests can cause "key already exists" errors for user preference

org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java, org.adempiere.base/src/org/compiere/model/MDocType.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6666 …
=> IDEMPIERE-6666 fix getShipmentReceiptDocType in MDocType

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WArchiveViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6692
=> IDEMPIERE-6692 Archive Viewer is adding .pdf to any file - and showing always as PDF
