org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WProcessCtl.java
Tested the patch - it creates correctly the parameter "*RecordIDs*" with all the records in the window, and it doesn't throw NPE.  So, jasper reports could use this new parameter to get more than one record - but I didn't test this case, more focused on solving the NPE at this moment.
=> Idempiere 4258

org.adempiere.base/src/org/compiere/model/MPayment.java
Fixes issue reported by @mschnbeck 
14:08:47.076===========> MInvoice.load: NO Data found for C_Invoice_ID=1000000 [173]
java.lang.Exception
at org.compiere.model.PO.load(PO.java:1364)
bad trx management
=> IDEMPIERE-4220 payment could not be committed due to wrong invoice date

org.adempiere.ui.zk/theme/default/css/fragment/adwindow.css.dsp
The commit is to display the 'Show First' and 'Show Last' paging buttons again. The CSS is only for devices with screens larger than tablets, those two buttons on smaller screens overlap the toolbar buttons.
=> IDEMPIERE-3657 Missing buttons start/end page on detail tab

org.adempiere.base/src/org/compiere/model/MUserQuery.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
Comments added to the ticket. 
Changes made with this commit: 
1. If a user query is shared globally the saved button is disabled to avoid creating a private duplicate.
2. A user can make a copy of the global query and save it privately. A copy is made by changing the name of the saved query in the corresponding field in the search window. This also prevents having multiple queries with the same name.
3. There was a bug when updating a global query. When you selected a shared query, modified it, and click on the share button, it was duplicated instead of updated. This has been fixed as well.
=> IDEMPIERE-4304 Saved Query duplicates if use to save after sharing

migration/i7.1z/oracle/202005272300_IDEMPIERE-1540.sql, migration/i7.1z/postgresql/202005272300_IDEMPIERE-1540.sql, org.adempiere.base/src/org/compiere/model/GridFieldVO.java, org.adempiere.base/src/org/compiere/model/I_AD_InfoColumn.java, org.adempiere.base/src/org/compiere/model/I_AD_Process_Para.java, org.adempiere.base/src/org/compiere/model/I_AD_UserDef_Field.java, org.adempiere.base/src/org/compiere/model/Lookup.java, org.adempiere.base/src/org/compiere/model/MInfoColumn.java, org.adempiere.base/src/org/compiere/model/MInfoWindow.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/X_AD_InfoColumn.java, org.adempiere.base/src/org/compiere/model/X_AD_Process_Para.java, org.adempiere.base/src/org/compiere/model/X_AD_UserDef_Field.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ComboEditorBox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/InfoListSubModel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
Implement auto complete for search field
=> IDEMPIERE-1540 Autocomplete for field type "Search"

org.adempiere.base/src/org/compiere/model/MAccount.java, org.adempiere.base/src/org/compiere/model/MAccountLookup.java
Implement cache for MAccount.get(ctx, C_ValidCombination_ID)
=> IDEMPIERE-4311 Implement cache for MAccount(C_ValidCombination)

org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
Test case is different now because raising the exception, the order is not Invalid, but Draft
Jenkins test job failing:
https://jenkins.idempiere.org/job/iDempiereDaily/239/org.idempiere$org.idempiere.test/testReport/org.idempiere.test.model/SalesOrderTest/testDatePromisedValidation/
=> IDEMPIERE-4319 Cascade workflow activities

org.idempiere.webservices-feature/feature.xml
eclipse don't count plugin on dependency tab (require list) of feature.xml but tycho count it
=> IDEMPIERE-4350:org.apache.tomcat.util.descriptor.DigesterFactory warn

migration/i7.1z/oracle/202007071145_IDEMPIERE-4359.sql, migration/i7.1z/postgresql/202007071145_IDEMPIERE-4359.sql, org.adempiere.base.process/src/org/compiere/process/EMailTest.java, org.adempiere.base/src/org/compiere/model/MClient.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java
Ability to define a dedicated mail template for the EMailTest process (via a client level SysConfig).
Output of the process was wrong (always successful even when the email was not sent)
=> IDEMPIERE-4359 : EMailTest process : customization of email sent

org.adempiere.base/src/org/adempiere/impexp/GridTabCSVImporter.java, org.adempiere.base/src/org/compiere/model/MLookup.java
close trx in finally block.
m_directNullKey interfere with CSV Import Loader due to trx that's not
committed yet.
insert mode: update window/tab context after save.
=> IDEMPIERE-4373 Bug fixes for CSV Import loader

org.adempiere.base/src/org/compiere/wf/MWFProcess.java
maybe order by seq-no of node link to activity is more stable than ID
=> IDEMPIERE-4376:order activity workflow by ID (also time it's created)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4397
Hide ProcessModelDialog except BusyDialog when ProcessModelDialog is opened as Autostart.
Autostart Test Cases.
**Test Case 1: (Print Report)**
1. Open Sales Order Window in Garden World
1. Find Completed Sales Order
1. Click Print Button
1. Only BusyDialog should be shown when opening Print Report
**Test Case 2: (Complete Order)**
1. Open Sales Order Window in GardenWorld
1. Create new Sales Order with lines
1. Click Doc Action Button
1. Set Any Doc Action and Confirm
1. Only BusyDialog should be shown when processing Document
**Test Case 3: (Process Silent Run with Defaults)**
1. Open Sales Order Window in GardenWorld
1. Find Any Completed Order
1. Go To OrderLine
1. Click Process Button and start **Process OrderLine Create …
=> IDEMPIERE-4397 Hide ProcessModalDialog in Autostart

migration/i7.1z/oracle/202008061523_IDEMPIERE-4404.sql, migration/i7.1z/postgresql/202008061523_IDEMPIERE-4404.sql
This was probably caused years ago (2007) because off applying the script from commit 89c9a3b4 migration-historic/320-330/postgresql/001_add_brazilian_states.sql without the proper NLS_LANG variable set in oracle
It is important, when applying this script to set the NLS_LANG properly, suggested value is:
export NLS_LANG=AMERICAN_AMERICA.UTF8
https://idempiere.atlassian.net/browse/IDEMPIERE-4404
=> IDEMPIERE-4404 Wrong characters + typos in Brazilian regions

org.adempiere.pipo/src/org/adempiere/pipo2/AbstractElementHandler.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
Incorporate patch from hieplq - not to export ad_org_id for ad_org table
Fix typo for ad_org_id exclude check. Remove ad_org_id from exclude list to maintain backward compatiblity.
=> IDEMPIERE-4256 [2pack] issue with export org (non office id)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WDateEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WDatetimeEditor.java
sun.util.calendar.ZoneInfo consider offset and "daylight saving time" changed on range 1900-2037
for out of that range then offset always return raw offset, make date incorrect 1 day on some days
offset change by history can reference at:
https://en.wikipedia.org/wiki/Time_in_Vietnam#Time_in_French_Indochina
https://www.timeanddate.com/time/zone/vietnam/hanoi
database for all change
https://www.iana.org/time-zones
=> IDEMPIERE-4361:Date is subtracted by 1 day in certain cases

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
Pass ReadOnly Parameter to GridField from Info Window Column. For Better Performance of WTableDir Component.
https://idempiere.atlassian.net/browse/IDEMPIERE-4450
=> IDEMPIERE-4450 Info Window Performance

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WLocatorDialog.java
Fix NPE when we confirm Locator Dialog with empty Locator Field.
To test:
1. Open any Product which have its Locator selected.
2. Deselect Locator through Locator Dialog.
=> IDEMPIERE-4442 FIX NPE when locatorField is Empty

migration/i7.1z/oracle/201809141624_IDEMPIERE-1604.sql, migration/i7.1z/postgresql/201809141624_IDEMPIERE-1604.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutWindowCustomization.java, org.adempiere.base/src/org/compiere/model/GridTabVO.java, org.adempiere.base/src/org/compiere/model/I_AD_UserDef_Tab.java, org.adempiere.base/src/org/compiere/model/X_AD_UserDef_Tab.java
This will extend the window customization functionality.
Single Row layout and Read Only fields on window customization are now Lists, so it can be empty. This way the default behaviour will be preserved. You are now able to customize the WHERE clause (it will be appended to original WHERE clause for security reasons), process, order by, display logic and read only logic
=> IDEMPIERE-1604 - Extend features for Window Customization

org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
added "org.eclipse.pde.junit.runtime_3.5.700.v20200116-1804"
=> IDEMPIERE-4475 Can't Run Junit Plugin Test with Eclipse 2020-09

migration/i7.1z/oracle/202010031628_IDEMPIERE-4297.sql, migration/i7.1z/postgresql/202010031628_IDEMPIERE-4297.sql
Create a new accounting schema in Euros
Solve problems with documents not posting:
- Fix date for test conversion rates
- Reactivate price list
- Create required purchase order for matching
Create a default query for Unposted window to show Not Drafted documents
Set accounting to immediate (sync seed DBs - postgresql was immediate, oracle was not)
Reset accounting for GardenWorld, delete all facts and reset posted status of all documents
Inactivate cash journals not used anymore
=> IDEMPIERE-4297 Improve test data

org.adempiere.ui.zk/theme/default/css/fragment/desktop.css.dsp, org.adempiere.ui.zk/theme/default/css/fragment/group.css.dsp, org.adempiere.ui.zk/theme/default/css/fragment/tab.css.dsp, org.adempiere.ui.zk/theme/default/css/theme.css.dsp
Change font to improve the L&F
https://idempiere.atlassian.net/browse/IDEMPIERE-4482
=> IDEMPIERE-4482 Mobile Improvements - Font

org.adempiere.base.callout/src/org/compiere/model/CalloutPayment.java
Fix NPE when the field is not present in the window
13:56:08.612===========> CalloutPayment.start: start: amounts [147]
java.lang.NullPointerException
at org.compiere.model.CalloutPayment.amounts(CalloutPayment.java:599)
=> IDEMPIERE-4083 currency rate by document or by transaction

org.adempiere.server-feature/jettyhome/etc/jetty-template.xml, org.adempiere.ui.zk/WEB-INF/jetty-web.xml
replace the now defunc setting at jetty.xml with jetty-web.xml
=> IDEMPIERE-2490 java.lang.IllegalStateException: Form too large

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/LayoutUtils.java
Restore sendDeferLayoutEvent - deprecated, to avoid breaking some plugins out there
https://idempiere.atlassian.net/browse/IDEMPIERE-4528
=> IDEMPIERE-4528 Update Js Library

migration/i8.1z/oracle/202011241451_IDEMPIERE-4566.sql, migration/i8.1z/postgresql/202011241451_IDEMPIERE-4566.sql, org.adempiere.base/src/org/idempiere/process/TranslationImpExp.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/install/WTranslationDialog.java, org.adempiere.ui/src/org/compiere/install/TranslationController.java
- Deprecate zk form WTranslationDialog and controller TranslationController
- Move the logic to a java process org.idempiere.process.TranslationImpExp
- As a process works in mobile, can be called via webservices, tested with fitnesse, etc
- Importing leaves a better and readable log of each file processed
- Importing/Exporting gives feedback to the user about the file being processed
Side note:
- To standardize the menu - renamed the "Initial Client Setup Process" to "Initial Client Setup"
Improvements over the previous form:
- can process the files from the zip in root folder, or in internal folder with the name of the language
- can process a URL http/https to download the zip file
https://idempiere.atlassian.net/browse/IDEMPIERE-4566
=> IDEMPIERE-4566 Translation Import/Export - output message is not visible

org.adempiere.base/src/org/compiere/model/MRegion.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/wf/MWorkflow.java
Found a case where PO.checkValidClient fails, and then because of log.severe it tries to create a record with MIssue, and the PO.checkValidClient fails in MIssue, and is called recursively until it fails with a "Trx.run: Transaction timeout."
https://idempiere.atlassian.net/browse/IDEMPIERE-4268
=> IDEMPIERE-4268 Fix recursive call to PO

migration/i8.1z/oracle/201807250000_IDEMPIERE-4579.sql, migration/i8.1z/postgresql/201807250000_IDEMPIERE-4579.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4579
=> IDEMPIERE-4579 Function altercolumn fails when a role name has a dash

org.adempiere.base/src/org/compiere/model/MUserDefWin.java
Fixes:
org.adempiere.exceptions.AdempiereException: Cross tenant PO reading request detected from session 1009629 for table AD_UserDef_Win Record_ID=1000002
at org.compiere.model.PO.checkValidClient(PO.java:5000)
at org.compiere.model.PO.<init>(PO.java:212)
at org.adempiere.model.GenericPO.<init>(GenericPO.java:81)
at org.compiere.model.MTable.getPO(MTable.java:598)
at org.compiere.model.Query.list(Query.java:286)
at org.compiere.model.MUserDefWin.getAll(MUserDefWin.java:107)
at org.compiere.model.MUserDefWin.getBestMatch(MUserDefWin.java:160)
https://idempiere.atlassian.net/browse/IDEMPIERE-4268
=> IDEMPIERE-4268 Web Services : Read miss cross-tenant check

org.adempiere.server-feature/build.xml, org.adempiere.server-feature/console-setup-alt.sh, org.adempiere.server-feature/hazelcast-template.xml, org.adempiere.server-feature/setup-alt.sh
* Secure sensitive files containing passwords at the end of build.xml for linux
* jettyhome/etc/jetty-ssl-context.xml - contains keystore password
* idempiereEnv.properties, idempiere.properties, utils/myEnvironment.sh - contain database and other passwords
* setup-alt.sh and console-setup-alt.sh don't need to chmod as the ant task already did it
* add port to hazelcast-template.xml (useful in case there are same databases in different ports on the server)
https://idempiere.atlassian.net/browse/IDEMPIERE-4602
=> IDEMPIERE-4602 Encrypt passwords on properties files (FHCA-1982)

Credits.html
- Added missing organizations according to what was discussed by the marketing committee.
- Improved the layout to show all the organizations without the need for scrolling down
- Move founders side-to-side which is a better message than one on top
- Changed the links to HTTPS
=> IDEMPIERE-4580 Credits.html additions and layout improvements

org.adempiere.base/src/org/compiere/model/MTax.java, org.adempiere.base/src/org/compiere/model/StandardTaxProvider.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4621
Saving OrderTax After Deleting it caused CrossTennant Error.
Why do we save deleted OrderTax?
=> IDEMPIERE-4621  Cross Tenant Parent Tax Error

.gitignore, org.adempiere.install/install.silent.app.launch, org.adempiere.install/plugin.xml, org.adempiere.install/src/org/compiere/install/InstallApplication.java, org.adempiere.install/src/org/compiere/install/Setup.java, org.adempiere.install/src/org/compiere/install/SilentSetup.java, org.adempiere.install/src/org/compiere/install/console/ConsoleInstallApplication.java, org.adempiere.install/src/org/compiere/install/console/SilentInstallApplication.java, org.adempiere.server-feature/build.properties, org.adempiere.server-feature/silent-setup-alt.bat, org.adempiere.server-feature/silent-setup-alt.sh, org.adempiere.server-feature/silent-setup.bat, org.adempiere.server-feature/silent-setup.sh, org.adempiere.server-feature/utils.unix/unix/DebianInstaller/etc/init.d/idempiere, org.adempiere.server-feature/utils.unix/unix/createDEBpackage.sh
* Allow receiving log level as parameter for setup and console-setup
* Avoid duplication of log file - just leave it in /log
* Implement logging for console-setup too
* mark SilentSetup as deprecated
* add runtime-*.app to .gitignore (sometimes files appear in these folders and can be wrongly committed)
https://idempiere.atlassian.net/browse/IDEMPIERE-4620
=> IDEMPIERE-4620 Improvements for Setup programs

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
Problem is that Info Column has ReadOnly parameter which have 2 uses. So if we set Parameter as ReadOnly, this parameter is in table set as read only. But if this parameter is set as Query Parameter it will interfere with menu popup which checks ReadOnly Parameter.
So i created parameterTree to store new Gridfield copy which have forced read only false in Query Parameter.
https://idempiere.atlassian.net/browse/IDEMPIERE-4485
=> IDEMPIERE-4485 Info Window Columns has no Value preference

org.adempiere.server/resources/templates/black/styles/template.css, org.adempiere.server/resources/templates/white/styles/template.css
This is a fix for the safari tile image positioning issue:
Discussion here: https://groups.google.com/g/idempiere/c/soHxAlytJMs
=> Fix for the safari browser tile image positioning problem.

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
This is pull request of IDEMPIERE-4644 : Heading only Field is the cause of NullPointerException Error on Find Window.
I added null check logic.
And test below.
・I confirmed that NullPointerException Error on Find Window Don't display when there is a Heading only Field. 
・In case of tick "Lookup Only Selection Columns" of tab setting,  it also seemed good .
=> IDEMPIERE-4644 Heading only Field is the cause of NullPointerException Error on Find Window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTimeEditor.java
I tested below case.
* In case of processed = 'Y' at Window.
* In case of IsActive = 'Y' at Window.
* In case of Read only field at Window.
* In case of apply Read only Logic at Window. 
* In case of apply Read only Logic at Process. 
It's seems good.
best regards.
=> IDEMPIERE-4655 WTimeEditor display time picker button when read only.

org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
* Fixed a problem with IDEMPIERE-4130 that was not using role max query records
* GridTable was throwing NPEs because the arrays were disposed before closing
* Lowered log level on MRole to avoid clogging the console (I was testing with INFO level)
* Added more points of control for the timeout exception to give meaningful errors to the user and allow refining the query without closing the Find dialog
* Implemented a control to avoid repeating a slow initial query every time the dialog is open
* Added dialog when the find criteria doesn't return rows and allows the user to refine the query
* When the initial number of records is unknown, show a question mark instead of the count
https://idempiere.atlassian.net/browse/IDEMPIERE-4653
=> IDEMPIERE-4653 Improve timeout handling of window tab

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4658
=> IDEMPIERE-4658 The operator Dropdown entries for a foreign ID column is corrupted when a search preset is loaded in any window's Advanced Search tab.

org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4674
=> IDEMPIERE-4674 PackIn AD_Image or AD_Archive leave corrupt record when using FileSystem storage provider

migration/.project
Fix project definition for migration folder - is not java nature
Usually I import the projects db and migration into eclipse for tracking of changes, the migration definition is wrong.
https://idempiere.atlassian.net/browse/IDEMPIERE-4488
=> IDEMPIERE-4488 Remove .classpath from repository

migration/i8.2z/oracle/202104081114_IDEMPIERE-4755.sql, migration/i8.2z/postgresql/202104081114_IDEMPIERE-4755.sql
Report View are very useful to add WHERE clauses to VIEWs created on Table & Column window, so you can keep a single VIEW and use it with several "Report Views". 
The proposal of this ticket is to change the access level of Report View table to System+Client, so can create new Report Views on client instead of System. 
Also we have to make the field AD_ReportView_ID updatable on table AD_PrintFormat.
This feature is similar to Window Customization, but to be used with reports.
=> IDEMPIERE-4755 Change data access level of Report View to System+Client

org.adempiere.pipo/src/org/adempiere/pipo2/PackOut.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3508
Implement the fix for the case mentioned in the last comment at
https://idempiere.atlassian.net/browse/IDEMPIERE-3508?focusedCommentId=42780
"in case a 2pack is generated on a system with a blob column, and then imported in a system where that column is string, the import leaves wrong data"
For testing purposes, the following 2pack can be used:
[202105041141_GardenWorld_KanbanRequestsGardenWorld.zip](https://github.com/idempiere/idempiere/files/6420227/202105041141_GardenWorld_KanbanRequestsGardenWorld.zip)
The value of the _Kanban Card Content_ is left incorrectly as "1.dat|string" - with the fix the value is correctly assigned.
=> IDEMPIERE-3508 2pack: support export from text column to string column

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ToolbarCustomButton.java
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4811
Expanded ToolbarCustomButton class to set tabNo when rendered on Tab Detail Pane to have access to tab Context.
Expanded DetailPane on method updateToolbar to use ToolbarCustomButton.dynamicDisplay() when toolbarbutton is CustomToolbarButton.
=> IDEMPIERE-4811 Custom Toolbar Buttons Dynamic Validation Fix

org.adempiere.base.process/src/org/idempiere/process/MigrateStorageProvider.java, org.adempiere.base/src/org/compiere/model/AttachmentFileLazyDataSource.java, org.adempiere.base/src/org/compiere/model/AttachmentFileSystem.java, org.adempiere.base/src/org/compiere/model/IAttachmentLazyDataSource.java, org.adempiere.base/src/org/compiere/model/IAttachmentStore.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MAttachmentEntry.java
The approach is backward compatible, the actual plugins will keep working without changes.
For plugins that want to use the new delayed load implementation is simple:
* do not load the entries data in loadLOBData - this can be done using the new constructor MAttachmentEntry(MAttachment, String, int, Object)
* implement the load of the entry data in loadLOBDataEntry
The new approach was implemented and tested in AttachmentFileSystem, for attachments with many files, or with very big files the performance and memory footprint is reduced because the load of the data from files is done just when needed.
The unchanged AttachmentDBSystem was tested too to ensure everything keeps working without changes there.
=> IDEMPIERE-4889 Performance - Attachment management

org.adempiere.base/src/org/compiere/util/EMail.java, org.adempiere.base/src/org/compiere/util/EMailAuthenticator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4909
=> IDEMPIERE-4909 Allow empty password when using OAuth2 - refactor to allow sending email without AD_User (FHCA-2892)

org.adempiere.base/src/org/compiere/model/MPayment.java
Added a client check when retrieving the default bank account
[https://idempiere.atlassian.net/browse/IDEMPIERE-4914](url)
=> IDEMPIERE-4914 Wrong BankAccount when creating createCounterDoc for linked BPartner

migration/i8.2/oracle/202108182002_IDEMPIERE-4911.sql, migration/i8.2/postgresql/202108182002_IDEMPIERE-4911.sql, org.adempiere.base.process/src/org/compiere/process/TranslationDocSync.java, org.adempiere.base/src/org/adempiere/exceptions/DBException.java, org.adempiere.base/src/org/compiere/model/MColumn.java, org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4911
Changes:
* Saving a value that doesn't fit in the translation now fails with a proper user understandable message
* Synchronize Doc Translation now fails with a user understandable message in case it fails because a value doesn't fit
* When updating a column on a translation table, check for the size of the original column and update the size accordingly
* When updating a translated column, show warnings to user about creating the table, or creating the column, or updating the column size
=> IDEMPIERE-4911 Silent fail when translated column is shorter than original column (FHCA-2888)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultInfoFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/IInfoFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/InfoManager.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoAssetWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoAssignmentWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoBPartnerWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoInOutWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoInvoiceWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoOrderWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoPaymentWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
This improvement is applied normal Info Window and special Info Windows below.
*InfoBPartnerWindow
*InfoProductWindow
*InfoInvoiceWindow
*InfoOrderWindow
*InfoAssetWindow
*InfoInOutWindow
*InfoPaymentWindow
*InfoAssignmentWindow
I added above Info Windows to menu and tested below case.
I could perse Predefined Context Variables at Info Windows.
*Sql WHERE field of info window.
*Display Logic field of info window column.
*Default Logic field of info window column.
*Dynamic Validation of info window column.
*Fields of process parameter that assigned info window.
I added a new method to IInfoFactory as Default.
And I confirmed there are not bad impact of source code change.
*I could open info window and use at search field of window.
*I could open info window and use at search field of find …
=> IDEMPIERE-4917:Inject Context Variables from Menu to Info Window

org.adempiere.base/src/org/compiere/model/GridTable.java
At the end of table sorting, trigger data status change event before UI
event, so that GridTab data is changed before UI refresh, which is
needed for Swing UI.
I have tested the patch in Swing and ZK.
Not sure why ZK UI do not have this same issue.
=> IDEMPIERE-4945 Selected row is changed after table sort in Swing UI

org.idempiere.keikai/META-INF/MANIFEST.MF
- Jetty 10: Jetty-WarPatchFragmentFolderPath have been drop and replace
by Jetty-WarPrependFragmentResourcePath
=> IDEMPIERE-4933 Platform update for 9.x

org.adempiere.base/OSGI-INF/org.adempiere.base.AnnotationBasedModelFactory.xml, org.adempiere.base/build.properties, org.adempiere.base/src/org/adempiere/base/AnnotationBasedModelFactory.java
- Temporary disable AnnotationBasedModelFactory until getSubclasses()
doesn't work for subclass from different package is resolve.
=> IDEMPIERE-4842 Easier model registration

org.adempiere.base/src/org/adempiere/base/annotation/Parameter.java, org.adempiere.base/src/org/compiere/process/SvrProcess.java
Created `@Parameter` annotation in order to tag process class attributes as parameters and have them to have their values assigned automatically without extra code.
=> IDEMPIERE-5025 Easier usage of process parameters

org.adempiere.base.process/src/org/compiere/process/InOutGenerate.java
InOutGenerate.createLine(): The Process would sometimes generate
multiple inout lines from a single product lot/asi.
InOutGenerate.prepare(): moved date setting code out of the loop.
=> IDEMPIERE-4854 Bugfixes in InOutGenerate

org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java, org.adempiere.base/src/org/compiere/model/MInOut.java
When we call m_inout then - field - movementtype must be set by frontend - otherwise REST call fail.
We suggest to add to beforesave from callout - then m_inout.movementtype will be handled by backend.
=> IDEMPIERE-5078 - M_inout movementtype add to before save

org.adempiere.base/src/org/compiere/model/MInOut.java
Found a typo in beforeSave method, C_DocType should have been C_DocType_ID
=> IDEMPIERE-5078 - fix typo C_DocType should be C_DocType_ID

org.adempiere.base/src/org/compiere/util/DB.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4900
Fix wrong matches pattern -> eclipse 2021-12 complains with error
Invalid escape sequence (valid ones are  \b  \t  \n  \f  \r  \"  \'  \\ )
=> IDEMPIERE-4900 SQL statement added as an option to define WF Next Node Condition

org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd, org.idempiere.test/idempiere.unit.test.launch
Update JUnit to 5.8.1 from Eclipse 4.22
https://idempiere.atlassian.net/browse/IDEMPIERE-5128
=> IDEMPIERE-5128 JUnit test fail to launch with Eclipse 2021-12 (4.22)

org.adempiere.base/src/org/adempiere/model/MBroadcastMessage.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/BroadcastMessageWindow.java
Credits go to devcoffee - sorry i didn't find Matheus Marcelino's github account
Co-Authored-By: muriloht <5605206+muriloht@users.noreply.github.com>
=> IDEMPIERE-5135 : Add a link in a Broadcast message to open a record

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
All infowindows show the column headers, but this is not the case of lookup search, that uses InfoGeneralPanel. This should be enabled in order to get a consisting look and feel of iDempiere.
This was not captured in the ticket IDEMPIERE-4863 “Enable save column width in WListBox” where the use of WListbox in the infoWindows where implemented.
Examples of these lookups are RMA on Customer Returns, Cash Plan Line on Sales Order.
=> IDEMPIERE-5101 InfoGeneralPanel don’t show column headers when opened

org.idempiere.test/src/org/idempiere/test/model/ProductionTest.java
- set mulch product category to Standard Costing category, so that the standard cost of the component is compared to the standard cost of the parent, mulchx.
Currently the test is comparing the Average PO cost of mulch with the rolled up Standard Cost of mulchx. In the seed database the Average PO and Standard Cost of mulch are the same, so the test passes.
=> IDEMPIERE-5063 Improve Unit Tests - fix ProductionTest RollUp test

org.adempiere.base/src/org/compiere/model/Query.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java, org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5147
Question: Do i need to move 
`String sql = buildSQL(null, true);`
in TRY block? 
buildSQL can throw IllegalStateException. Which can cause that pageSize is not set to original value.
=> IDEMPIERE-5147  Improve Query.first() methods - performance

migration/i9/oracle/202201302336_IDEMPIERE-5168.sql, migration/i9/postgresql/202201302336_IDEMPIERE-5168.sql, org.adempiere.base/src/org/compiere/model/MColumn.java, org.adempiere.base/src/org/compiere/util/DisplayType.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultEditorFactory.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5168
- Allow reference Text with length 0 to be managed as CLOB/TEXT
- Increase AD_ChangeLog.OldValue/NewValue to 4000 to allow saving more information about changing long texts
- Change AD_AuthorizationAccount.AccessToken to CLOB/TEXT
- Change some important actual columns defined as Text Long, to Text with length 0 (this allows changelog, better 2Pack, encryption)
=> IDEMPIERE-5168 column AD_AuthorizationAccount.AccessToken is short on some case

org.adempiere.base/src/org/compiere/model/MAuthorizationAccount.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5169
Opening this in draft because is not tested against real potential cases:
- column AD_AuthorizationAccount.AccessToken encrypted and unencrypted
- multitenant
- potentially different encryption keys in different tenants
=> IDEMPIERE-5169 OAuth2: add same email account on other client will break it on old client

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WFactReconcile.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WTreeMaintenance.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/MenuTreeSearchPanel.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/font-icons.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4561
I only fix the straightforward ones
New Icon Class
- z-icon-Collapsing
- z-icon-ProcessMenu
- z-icon-ThreeLineMenu
Copy from iceblue_c
- z-icon-FastBack
- z-icon-FastForward
- z-icon-InfoLocator
- z-icon-InfoShipment
- z-icon-SelectAll
- z-icon-StepBack
- z-icon-StepForward
Also sort the font icons by name for easy comparison between themes
=> IDEMPIERE-4561 Font Icons not used in several points

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WInfoWindowListItemRenderer.java
Issue: CSS style replaces the entire style, instead of appending.
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-3831
Use case: Product Info: OnHandQty @QtyOnHand@>5 then color: green.
In this case 'replacelD' style was removed, ensure number right alignment, just the color was added. So cells with the colors were aligned left, w/o right (legacy)
solution: append style instead replace.
=> IDEMPIERE-3831 - css style replaces the entire style, instead of append

migration/iD10/oracle/202202280901_IDEMPIERE-5206.sql, migration/iD10/postgresql/202202280901_IDEMPIERE-5206.sql, org.adempiere.base/src/org/compiere/model/I_AD_PrintFormatItem.java, org.adempiere.base/src/org/compiere/model/X_AD_PrintFormatItem.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5206
Try to add AD_FieldStyle_ID on AD_PrintFormatItem table.
Improvement: you will be able to change css style of data in single cells of HTML report, based on the Display Logic defined in AD_FieldStyle.
=> IDEMPIERE-5206 - HTML Report CSS style - add AD_FieldStyle_ID on AD_PrintFormatItem table

migration/i9/oracle/202203071656_IDEMPIERE-5220.sql, migration/i9/oracle/202203071858_IDEMPIERE-5220.sql, migration/i9/postgresql/202203071656_IDEMPIERE-5220.sql, migration/i9/postgresql/202203071858_IDEMPIERE-5220.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5220
Please note:
* I separated the tickets because the first one is intended to integrate in a 7.1 installation
* Oracle script differs from postgresql because in oracle those indexes are OK - oracle doesn't allow duplicated indexes
=> IDEMPIERE-5220 Duplicated indexes in postgresql (and mismatch against oracle) / FHCA-2740

org.idempiere.test/src/org/idempiere/test/AbstractTestCase.java, org.idempiere.test/src/org/idempiere/test/base/POTest.java, org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5063
- Close DB connections after each unit test class
- POTest and QueryTest: use assert equals, use bigdecimal string constructor in preference to double
When running the Unit Tests, the number of DB connections continuously grows until all the tests are completed. Currently this is  over 80 connections. As the number of unit tests increase, this could become an issue. Closing the database after each test class greatly reduces the number of concurrent connections and doesn't add more than a couple of seconds to the total time taken to run all the tests.
Also added some minor improvevements to POTest and QueryTest.
=> IDEMPIERE-5063 Improve Unit Tests

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4753
Referenced PR: https://github.com/idempiere/idempiere/pull/1251
Bug: When we change print format, the file name stays the same. 
E.g. we have 2 print formats with different file name pattern, then only that one is applied, with which the report was opened. If we change print format after the report is opened, the filename stays the same.
=> IDEMPIERE-4753 Make printing filename configurable - bug

org.adempiere.base/src/org/compiere/model/MSession.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/process/ProcessInfo.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/AdempiereActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/Incremental2PackActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/Version2PackActivator.java, org.adempiere.server/src/main/server/org/compiere/server/AdempiereServerMgr.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/session/SessionContextListener.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/CompiereService.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5256
Added Caching to MSession. Added Parameter IsImmutable to select if we want to return immutable object (cached) or load from DB.
It Looks like Vector had some validation logic (Records Check) which cannot be copied to new Caching. Updating MSession record will delete cached data. 
Added Deprecated tag to previous methods.
=> IDEMPIERE-5256  Add Cache to MSession

migration/iD10/oracle/202206282000_IDEMPIERE-5295.sql
fix oracle script - caused by mismatch in primary key name IDEMPIERE-5227
https://idempiere.atlassian.net/browse/IDEMPIERE-5295?focusedCommentId=48499
=> IDEMPIERE-5295 Trial Balance Report creates wrong Opening Balance

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4592
=> IDEMPIERE-4592 Bank Statement Loader zoom in the Load Bank Statement process throws an exception when the field is empty

org.adempiere.pipo/src/org/adempiere/pipo2/POFinder.java
With this commit, Pack In will throw an informative error message if it can't find a table (including the table name).
Without this fix, you simply get an NPE which isn't very helpful for debugging.
Implements https://idempiere.atlassian.net/browse/IDEMPIERE-5366
=> [pipo] Throw useful exception when table not found

org.adempiere.pipo/src/org/adempiere/pipo2/PackIn.java
The input stream was not explicitly closed on exit (whether a success or failure). This leaves a resource leak and for added misery for Windows users meant that you can't pack in more than once without restarting the server.
Fixes [IDEMPIERE-5368](https://idempiere.atlassian.net/jira/software/c/projects/IDEMPIERE/issues/IDEMPIERE-5368)
_Edit: changed link to the correct issue in JIRA_
=> IDEMPIERE-5368 Pack In doesn't close resources properly on failure

org.adempiere.base/src/org/compiere/model/MRole.java
Removed the method MRole.loadTableInfo which loaded the arrays: m_tableAccessLevel, m_tableName, m_viewName, m_tableIdName
and replaced all usage with visits to cached information from tables or columns
https://idempiere.atlassian.net/browse/IDEMPIERE-5407
=> IDEMPIERE-5407 Heavy query in MRole repeated too often (FHCA-3883)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5389
**Before:**
**After:**
You can see, that the Performance Widget is partially hidden, also as chart doesn't fit widget height (next image)
For better testing we provide Pack Out for Status Line: https://idempiere.atlassian.net/browse/IDEMPIERE-5410
=> IDEMPIERE-5389 - improve Status Line as Dashboard Content height

org.compiere.db.oracle.provider/META-INF/pool/server.default.properties, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/META-INF/pool/server.default.properties, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
Fixes logic error in the way a user defined `jdbcUrl` in `hikaricp.properties` is handled.
Additionally changed the default max pool size to the previous limit of 90 connections. PR #926 originally also had this but this apparently fell out. Testing showed that during first time server startup a flood of connection can be made and a connection pool of 30 can be overwhelmed in some cases (depending on the speed of your setup). This results in callers waiting on a connection which will time-out.
=> Fixed user defined JDBC URL override not working.

db/.settings/org.eclipse.core.resources.prefs, migration/.settings/org.eclipse.core.resources.prefs
In eclipse 2022-09 two new warnings are shown:
Project 'db' has no explicit encoding set
Project 'migration' has no explicit encoding
=> Minor - solve two new eclipse 2022-09 warnings

org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MAttachmentEntry.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5446 …
=> IDEMPIERE-5446 : Property to know an AttachmentEntry has been updated

org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java
Fix issue with EMail MFA
https://idempiere.atlassian.net/browse/IDEMPIERE-5408
* When user login with EMail MFA the MFA panel is not shown and the Processing message just keep spinning
* Also changed the message about TenantNotFound by FailedLogin to avoid a brute force attack to discover which tenants are valid in the installation
=> IDEMPIERE-5408 Allow or enforce login with specific tenant (FHCA-3823)

org.adempiere.base/src/org/compiere/model/MMessage.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5136?focusedCommentId=48852
Fix Null Pointer Exception when saving a message without filling Value
=> IDEMPIERE-5136 Set Messages at tenant level / Fix NPE

org.compiere.db.postgresql.provider/META-INF/pool/server.default.properties
https://idempiere.atlassian.net/browse/IDEMPIERE-5013?focusedCommentId=48859
c3p0 had initial pool size set to 10.
HikariCP suggest a fixed pool size approach, so it starts immediately the 90 connections.
Changing the default back to 10 so it mimics better our previous c3p0 behavior.
=> IDEMPIERE-5013 set HikariCP initial pool size to 10 - as it was in c3p0

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/TabElementHandler.java
Add a space in sql statement to avoid an error when creating a 2Pack of tabs using postgresql 15
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is …
=> Add a space in sql statement to avoid an error

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/MenuElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5545
=> IDEMPIERE-5545 MenuElementHandler generating statements with bind variables in migration script

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
- Fix change role session error with nginx proxy
- Minor refinement for change role UI
https://idempiere.atlassian.net/browse/IDEMPIERE-5520
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the …
=> IDEMPIERE-5520 Navigation between Tabs leave Detached DOM objects (Leak)

org.adempiere.base/src/org/compiere/model/PO.java
- exclude AD_ChangeLog and AD_RecentItem from the validation to avoid affecting performance
Resolving @hengsin 's comment at
https://idempiere.atlassian.net/browse/IDEMPIERE-5238?focusedCommentId=49202
=> IDEMPIERE-5238 Record_ID editor

org.adempiere.base/src/org/compiere/model/PO.java
- Update should use ID column for where clause if ID value is official id.
https://idempiere.atlassian.net/browse/IDEMPIERE-5586
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a …
=> IDEMPIERE-5586 Implement ID independent migration script

org.adempiere.base/src/org/compiere/util/DisplayType.java
- Fix problem with the AbstractXLSXExporter going wild, the method getFormatString is trying to create a format with the number of digits supported by the NumberFormat, and as the MaximumIntegerDigits is not set, is trying to create a String with the default which is 2147483647
https://idempiere.atlassian.net/browse/IDEMPIERE-5542
=> IDEMPIERE-5542 [DisplayType] - Cache issue

org.adempiere.base/src/org/compiere/model/MColumn.java, org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5565
Tested successfully these cases for a virtual column in Test:
Both for Report and Info Window:
- Search/Table with AD_Reference defined with DisplayColumn=ID
- Search/Table with AD_Reference defined with DisplayColumn=Name
- Table Direct
=> IDEMPIERE-5565 Cannot create report with virtual column where reference is table with display column = ID

org.adempiere.base/src/org/compiere/model/GridField.java
…default value programmatically
https://idempiere.atlassian.net/browse/IDEMPIERE-5637 …
=> IDEMPIERE-5637 - Improve GridField to allow setting the default values of GridFieldVO programmatically with a method

org.idempiere.test/src/org/idempiere/test/AbstractTestCase.java, org.idempiere.test/src/org/idempiere/test/adwindow/GridTabTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5560#icft=IDEMPIERE-5560
https://idempiere.atlassian.net/browse/IDEMPIERE-5528
=> IDEMPIERE-5528 IDEMPIERE-5560 Cannot save more than one order line when an _ID field is not displayed

org.adempiere.base/src/org/compiere/process/SvrProcess.java
=> IDEMPIERE-5665 - [Multi Selection] - Negate option in process parameter

org.adempiere.base.callout/src/org/compiere/model/CalloutInvoice.java, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base/src/org/compiere/model/MInvoice.java, org.adempiere.base/src/org/compiere/model/MInvoiceLine.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java
=> IDEMPIERE-5671: Fixing Line net amount has error due to rounding.

org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/AbstractActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5684
=> Fixes IDEMPIERE-5684 Bad naming of Automatic 2Packs stop the whole process

org.adempiere.base.callout/src/org/adempiere/base/callout/CostAdjustmentLineProduct.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5703
=> IDEMPIERE-5703 NPE when importing Physical Inventory using Import CSV button

migration/iD10/oracle/202305011402_IDEMPIERE-5705.sql, migration/iD10/postgresql/202305011402_IDEMPIERE-5705.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5705
=> IDEMPIERE-5705 Field Event Change Log is not read only

org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5701 …
=> IDEMPIERE-5701: Improve logs when role cannot report or export

org.adempiere.base/src/org/compiere/print/DataEngine.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5645
=> IDEMPIERE-5645 - fix NPE on report Script columns

org.adempiere.base/src/org/compiere/model/GridTable.java
- Fix issues created with latest change - not able to create new records in Zero ID tables (C_DocType, AD_User, etc)
Example of test case failing:
- Try to create a new document type
- Check the ID when saved - is changing the record Zero instead of creating a new one
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195)

org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java
Jira ticket: [IDEMPIERE-5643](https://idempiere.atlassian.net/browse/IDEMPIERE-5643)
- - [x] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change. …
=> IDEMPIERE-5643 - Error during document's workflows are not displayed on Workflow Activities form.

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRadioGroupEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5769
- [] I have checked my code and corrected any misspellings
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task …
=> IDEMPIERE-5769: WRadioGroupEditor : make RadioGroupEditor class public

org.adempiere.base/src/org/compiere/model/GridTab.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5560?focusedCommentId=49477
=> IDEMPIERE-5560 Cannot save Material Receipt after filling Order if the User1_ID field is not displayed

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/StatusBarPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5780
It seems the InfoProductPanel (deprecated) is unusable, and this ticket doesn't solve this problem, but at least doesn't throw NPE and allows to select a product entering the value or name.
=> IDEMPIERE-5780 NPE on StatusBarPanel

org.adempiere.base/src/org/compiere/acct/Doc_AllocationHdr.java, org.idempiere.test/src/org/idempiere/test/model/Allocation2ndAcctSchemaTest.java, org.idempiere.test/src/org/idempiere/test/model/AllocationTest.java
[IDEMPIERE-5591](https://idempiere.atlassian.net/browse/IDEMPIERE-5591)
Payment allocation AP/AR GL postings not zero in alternative schema for invoice REVERSE/CORRECT
1. Create an Invoice (Vendor) in a different Currency (e.g. EUR)
2. Use a different Currency Type (e.g. Company) 
3. Set the Currency Rate (e.g. EUR/USD: 0.000063836578)
4. Create an invoice line with Line Amount 33,300 EUR
5. Complete and post the invoice (Grand Total: 33,300 EUR / 2.13 USD)
6. Reverse-Correct the invoice
7. Post the reversal invoice
8. Zoom into the allocation document
9. Post the allocation document
10. The expected postings:
DR A/P Trade 2.13 USD
CR A/P Trade 2.13 USD (or DR A/P Trade -2.13 USD)
[IDEMPIERE-5591]: https://idempiere.atlassian.net/browse/IDEMPIERE-5591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> IDEMPIERE-5591 Payment allocation AP/AR GL postings not zero in alternative schema for invoice REVERSE/CORRECT

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WDateEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WDatetimeEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5529 …
=> IDEMPIERE-5529 StackOverflowError at Quick Entry using WDateEditor

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
Fix the display bug for mandatory parameters and implements the ZK WrongValueException for mandatory parameters on ON_REFRESH time.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome …
=> Idempiere 5804 - Info Window mandatory parameters are not beeing display correctly.

org.idempiere.hazelcast.service/build.properties, org.idempiere.hazelcast.service/pom.xml, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/Activator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5816
- fix NPE when no hazelcast.xml file is in path or in bundle
- remove the library hazelcast-aws.jar - not needed anymore
I conducted tests with two amazon instances and it worked fine without the library as those classes are now included in hazelcast.jar
=> IDEMPIERE-5816 Upgrade Hazelcast version (FHCA-4436)

org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewerProvider.java, org.adempiere.ui/src/org/compiere/print/ReportCtl.java
- Fix process info log & error not shown
- Fix re-run missing context variable from menu
https://idempiere.atlassian.net/browse/IDEMPIERE-5275
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or …
=> IDEMPIERE-5275 Tabular Report Re-Run button/close parameter window

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/BroadcastMessageWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/HeaderPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5831
After adjusts, the window was oppened just once.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If …
=> IDEMPIERE-5831 - Fix onZoom events to be executed once a click for Broadcast Messages

migration/iD10/oracle/202308280920_IDEMPIERE-5760.sql, migration/iD10/postgresql/202308280920_IDEMPIERE-5760.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/util/EMail.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5760
https://github.com/idempiere/idempiere/pull/1883 + changes requested by Carlos (migration script)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the …
=> IDEMPIERE-5760: Manage mail.smtp.timeout using SysConfig

org.adempiere.base/src/org/adempiere/model/MTabCustomization.java, org.adempiere.base/src/org/compiere/model/MDashboardPreference.java, org.adempiere.base/src/org/compiere/model/MMFARegistration.java, org.adempiere.base/src/org/compiere/model/MPasswordHistory.java, org.adempiere.base/src/org/compiere/model/MPreference.java, org.adempiere.base/src/org/compiere/model/MUserPreference.java, org.adempiere.base/src/org/compiere/model/MUserQuery.java, org.adempiere.base/src/org/compiere/model/MUserRoles.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WGadgets.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5843
Noticed there are still records being created wrongly with AD_Preference.AD_User_ID=0, that lead to the window not being editable.
IDEMPIERE-5174 / Revert changes from IDEMPIERE-4386
=> IDEMPIERE-5843 System support users (like SuperUser) cannot see (fix) preferences on tenants

org.adempiere.base/src/org/compiere/acct/Doc_AllocationHdr.java, org.idempiere.test/src/org/idempiere/test/model/Allocation2ndAcctSchemaTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5878
1. Create a payment/receipt in period 1 for USD 1,000. Instead of selecting an open invoice (allocation), enter a charge, for example a bank charge, or an income account.
```
USD/COP 1:4000
COP accounting schema:
DR Bank in Transit COP 4,000,000
CR Bank Charge COP 4,000,000
USD accounting schema:
DR Bank in Transit USD 1,000
CR Bank Charge USD 1,000
```
2. REVERSE/ACCRUAL payment/receipt in period 2.
```
USD/COP 1:5000
COP accounting schema:
DR Bank Charge COP 5,000,000
CR Bank in Transit COP 5,000,000
USD accounting schema:
DR Bank Charge USD 1,000
CR Bank in Transit USD 1,000
```
3. The reversal in step 2 creates an allocation document between the payment and payment reversal document.
```
COP accounting schema:
DR Unallocated Cash …
```
=> IDEMPIERE-5878 Wrong GL posting in allocation for payment REVERSE/ACCRUAL, if payment WITH charge

org.adempiere.base/src/org/adempiere/base/event/delegate/AutoProduceEventDelegate.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5900 …
=> IDEMPIERE-5900 [AutoProduce] - Execute only when it is not a return

org.adempiere.base.process/src/org/adempiere/process/InOutGenerateRMA.java, org.adempiere.base.process/src/org/adempiere/process/InvoiceGenerateRMA.java, org.idempiere.test/src/org/idempiere/test/model/InvoiceCustomerTest.java, org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5915
Generate Invoices (manual)
1. Go to the 'Generate Invoices (manual)' window
2. Select an 'RMA' record
3. Click on the 'Generate Invoices for RMA' button 
4. In the 'Generate Invoices for RMA' dialog, enter the 'Date Invoiced'
5. Click on the 'OK' button
6. Zoom to the created invoice (i.e. AR Credit Memo)
7. The 'Date Invoiced' and 'Account Date' should be the same 'Date Invoiced' entered in Step 4
Generate Shipments (manual)
1. Go to the 'Generate Shipments (manual)' window
2. Select an 'RMA' record
3. Click on the 'Generate Shipments for Vendor RMA' button 
4. In the 'Generate Shipments for Vendor RMA' dialog, enter the 'Movement Date'
5. Click on the 'OK' button
6. Zoom to the created shipment (i.e. MM Vendor Return)
7. The …
=> IDEMPIERE-5915 Generate Invoices (manual) > RMA => AR Credit Memo created with system date instead of "Date Invoiced"

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5921
=> IDEMPIERE-5921 Enable Multi-Selection on Search fields (Info Windows) by default

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java
[Ticket](https://idempiere.atlassian.net/browse/IDEMPIERE-5929)
[MatterMost](https://mattermost.idempiere.org/idempiere/pl/zawqq7tu53fj8mk1c6kwqhrtie)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the …
=> IDEMPIERE 5929 - Looping on ZK happening on Exceptions caused by IServerPushCallback.updateUI implementations

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
[Mattermost](https://mattermost.idempiere.org/idempiere/pl/9j6pr87c97nc8k5qaoqofjy4ec)
[IDEMPIERE-5935](https://idempiere.atlassian.net/browse/IDEMPIERE-5935)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with …
=> IDEMPIERE-5935 - Fixes non-updatable product info window subtabs to auto-select first record functionality

org.adempiere.base/src/org/compiere/model/MProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5835?focusedCommentId=50273
- assign the default programatically to cover old 2Packs having this value as NULL
=> IDEMPIERE-5835 [Process Info] - Disallow Multiple Executions by different users

migration/iD11/oracle/202311261544_IDEMPIERE-5567_TestUU_Trl.sql, migration/iD11/oracle/202311261658_IDEMPIERE-5567-PackInDetail.sql, migration/iD11/postgresql/202311261544_IDEMPIERE-5567_TestUU_Trl.sql, migration/iD11/postgresql/202311261658_IDEMPIERE-5567-PackInDetail.sql, migration/processes_post_migration/oracle/01_add_missing_Translations.sql, migration/processes_post_migration/postgresql/01_add_missing_translations.sql, org.adempiere.base.process/src/org/compiere/process/TranslationDocSync.java, org.adempiere.base.process/src/org/idempiere/process/CreateTable.java, org.adempiere.base/src/org/compiere/model/I_AD_Package_Imp_Detail.java, org.adempiere.base/src/org/compiere/model/MLanguage.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/X_AD_Package_Imp_Detail.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/CommonTranslationHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/GenericPOElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/IndexColumnElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ViewColumnElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/WorkflowElementHandler.java, org.adempiere.pipo/src/org/adempiere/pipo2/AbstractElementHandler.java, org.adempiere.pipo/src/org/adempiere/pipo2/Element.java
- Manage translation for UUID based tables
- Enable 2Pack Import UUID based tables with translation
- Create ad_package_imp_detail.Record_UU
- Create test table TestUU_Trl
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - Translation

org.adempiere.base.process/src/org/idempiere/process/CleanOrphanCascade.java, org.adempiere.base/src/org/idempiere/process/MoveClient.java
- CleanOrphanCascade is failing when there are orphan change log records for M_InOutLineMA or other non-ID tables
- MoveClient is failing when there are AD_PInstance orphan records (because of the recently added AD_Table_ID reference)
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - Fixes #TestDay2023

migration/iD10/oracle/202311221523_IDEMPIERE-5931.sql, migration/iD10/oracle/202312011228_IDEMPIERE-5931.sql, migration/iD10/postgresql/202311221523_IDEMPIERE-5931.sql, migration/iD10/postgresql/202312011228_IDEMPIERE-5931.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5931
**Generate Invoices (manual)**
1. Create and complete a Customer RMA
2. Create and complete a Customer Return for the Customer RMA created in Step 1
3. Go to the 'Generate Invoices (manual)' window
3. The Customer RMA created in Step 1 should appear for selection
5. Go to the 'Invoice (Customer)' window
6. Create an AR Credit Memo
7. Use the 'Create lines from' window to create lines from the Customer Return created in Step 4
8. Complete the AR Credit Memo
9. Go to the 'Generate Invoices (manual)' window
10. The Customer RMA created in Step 1 should not appear for selection
**Generate Shipments (manual)**
1. Create and complete a Vendor RMA
2. Go to the 'Generate Shipments (manual)' window
4. The Vendor RMA created in Step 1 should …
=> IDEMPIERE-5931 Generate Invoices (manual) displays RMA for selection despite AR Credit memo already completed.

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5888?focusedCommentId=50338
- Fix an issue causing that SuperUser (or users with several tenants) are not saving correctly preferences
=> IDEMPIERE-5888 Login Preferences are created on System tenant

org.adempiere.base/src/org/compiere/model/MRecentItem.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
- this can happen for example when a recent item record doesn't have or doesn't manage UUID
=> IDEMPIERE-5567 Fix NPE when AD_RecentItem.Record_UU is null

org.adempiere.base/src/org/compiere/db/PreparedStatementProxy.java, org.adempiere.base/src/org/compiere/db/StatementProxy.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5994
=> IDEMPIERE-5994 Connection leak when using DB.prepareStatement(badSql, null)

org.adempiere.base/src/org/compiere/model/MTestUU.java, org.idempiere.test/src/org/idempiere/test/model/MTestUUTest.java
when executing unit tests in parallel, MTestUUTest fails frequently with error detected deadlock this can be caused by testReadingUpdatingTestUU trying to update translations and at the same time the testDeletingTestUU is deleting the same record and deleting the same translations
=> IDEMPIERE-5567 - Parallel unit tests fail frequently with deadlock

org.adempiere.base/src/org/compiere/install/Translation.java
- fix throwing TestUU_Trl org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying <= integer Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 268
- change the process to explicitly break when a DB exception happens
- also fix a bug creating a double WHERE in some circumstances
=> IDEMPIERE-5567 Trl Export for table TestUU_Trl

org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/idempiere/process/MoveClient.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6017
- improve discovery of key column
- improve avoiding block when the target column is bigger and can hold the source column
=>  IDEMPIERE-6017 Move/Copy Client failing when there are Record_ID references for AD_ClientInfo or AD_OrgInfo

migration/iD11/oracle/202304060001_IDEMPIERE-5567.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5567?focusedCommentId=50544
Fix issue reported by @nmicoud - oracle treats empty string '' as null
=> IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - fix oracle migration script

org.adempiere.base/src/org/compiere/model/MRole.java
Calling Env.getAD_Client_ID(getCtx()) within the loadOrgAccessUser function can cause issues if the context is not yet logged in. To avoid this, it's recommended to use getAD_Client_ID() directly instead.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the …
=> IDEMPIERE-4677: get client id from MRole instead of from context

org.adempiere.base/src/org/compiere/dbPort/Convert.java, org.idempiere.test/src/org/idempiere/test/base/JsonFieldTest.java, org.idempiere.test/src/org/idempiere/test/base/POTest.java
Hi @hengsin - the last run on iDempiereDaily showed one failure:
https://jenkins.idempiere.org/job/iDempiereDaily/1067/console
```
16:36:10 Failures: 
16:36:10   POTest.testLogMigrationScript:552 Not found: ../migration/iD12/postgresql/202403071034_PlaceholderForTicket.sql ==> expected: <true> but was: <false>
```
I added some methods in Convert to make it more usable in unit tests in case we keep using that in future.
=> IDEMPIERE-2981 Fixes to failing unit tests

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
- Fix issue with double click and drag to select text mouse gesture.
https://idempiere.atlassian.net/browse/IDEMPIERE-6054
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a …
=> IDEMPIERE-6054 Create Lines From checkboxes behave erratically

migration/iD11/oracle/202404041759_IDEMPIERE-6087.sql, migration/iD11/postgresql/202404041759_IDEMPIERE-6087.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6087
With these changes the non-advanced users are able to delete or make default their assigned queries.
Advanced users still can do anything.
=> IDEMPIERE-6087 Users cannot delete their own User Queries

org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6102
=> IDEMPIERE-6102 Performance: avoid SQL on AD_TreeNode when the table doesn't have a custom tree

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6130?focusedCommentId=50803
=> IDEMPIERE-6130 Move garbage collection to a button in About Window

migration/iD11/oracle/202405080101_IDEMPIERE-6123.sql, migration/iD11/postgresql/202405080101_IDEMPIERE-6123.sql, org.adempiere.base/src/org/compiere/db/AdempiereDatabase.java, org.adempiere.base/src/org/compiere/model/MAcctSchema.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MProductCategoryAcct.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/ReportAction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6123?focusedCommentId=50835
- make also configurable the timeout and number of records from windows
- improve timing of reports avoiding unncessary load of array when not jasper
=> IDEMPIERE-6123 Query in search window causing slowness and load spikes in the database (FHCA-5356)

migration/iD12/oracle/202404261129_IDEMPIERE-6129.sql, migration/iD12/postgresql/202404261129_IDEMPIERE-6129.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-6129 …
=> IDEMPIERE-6129 Change column type

org.adempiere.base.process/src/org/idempiere/process/GenerateModel.java, org.adempiere.base/src/org/adempiere/util/ModelClassGenerator.java, org.adempiere.base/src/org/adempiere/util/ModelInterfaceGenerator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5796 …
=> IDEMPIERE-5796: for several tables in a row

org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/field-editor.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-6157 …
=> IDEMPIERE-6157 Ice blue compact theme: html field has no border

org.adempiere.base/src/org/compiere/print/ServerReportCtl.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/JasperPrintRenderer.java, org.idempiere.test/src/org/idempiere/test/base/ReportTest.java
[IDEMPIERE-6165](https://idempiere.atlassian.net/browse/IDEMPIERE-6165) + [IDEMPIERE-6168](https://idempiere.atlassian.net/browse/IDEMPIERE-6168)
- the test case is failing for orders with jasper print format
- the downloadable file name for jasper is wrong in zk when using FileNamePattern
[IDEMPIERE-6165]: https://idempiere.atlassian.net/browse/IDEMPIERE-6165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDEMPIERE-6168]: https://idempiere.atlassian.net/browse/IDEMPIERE-6168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IDEMPIERE-6165 + IDEMPIERE-6168 More problems with jasper setting filename

org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2981
Safety measure to avoid a missing space between CLOB and CONSTRAINT (CLOBCONSTRAINT) in certain rare scenario running in oracle.
=> IDEMPIERE-2981 - Implement JSON field type / fix missing space in certain scenarios

org.adempiere.base/src/org/compiere/model/MTableIndex.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6214
=> IDEMPIERE-6214 PackIn AD_TableIndex can fail if the index exists previously without columns

migration/iD11/oracle/202409231820_IDEMPIERE-6248.sql, migration/iD11/postgresql/202409231820_IDEMPIERE-6248.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/util/CLogFormatter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6248 …
=> IDEMPIERE-6248: SysConfig to avoid cutting log

org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/AbstractActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3551
This is a minor change to lower verbosity of plugin.
The plugin is showing a warning on every already-processed file which is unnecessary.
Changed to info level, and announce just when processing a folder.
=> IDEMPIERE-3551 Automatic Packin - lower verbosity

org.adempiere.base/src/org/compiere/print/MPrintFormatItem.java, org.adempiere.base/src/org/idempiere/print/renderer/HTMLReportRenderer.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ColumnLookup.java, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridTabRowRenderer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ZkCssHelper.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WImageEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WImageURLEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WImageDialog.java, org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/layout.js, org.idempiere.zk.breeze.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.breeze.theme/src/web/theme/default/css/fragment/field-editor.css.dsp, org.idempiere.zk.datatable/src/org/idempiere/zk/datatable/DatatableReportRenderer.java, org.idempiere.zk.iceblue_c.theme/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/fragment/field-editor.css.dsp
- implement hover image for image url and image editor in form mode
- fix aspect ratio of thumbnail
- added thumbnail css class for thumbnail image
- rename image-fit-contain css class to image-fit
- handle ImageURL type for generation of new print format
https://idempiere.atlassian.net/browse/IDEMPIERE-6256
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the …
=> IDEMPIERE-6256 Get image through url from attachment

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADSortTab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/IADTabpanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6275 …
=> IDEMPIERE-6275 Fix row presentation after first time find modal is closed (User preference option - View find result and ZK_GRID_AFTER_FIND)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/RelatedInfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-6297
The info's default Order By clause must be separated by a comma if there is a user-entered order
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the …
=> IDEMPIERE-6297 Fix RelatedInfoWindow Order By

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeDialog.java
On M_Lot M_Product_ID is mandatory, so the filter for M_Product_ID is needed when loading Lots
https://idempiere.atlassian.net/browse/IDEMPIERE-6315
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system …
=> WPAttributeDialog: added filter for M_Product_ID when loading Lots

org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
- show errors immediately when a window query has error (f.e. a wrong virtual column)
https://idempiere.atlassian.net/browse/IDEMPIERE-6386?focusedCommentId=51470
=> IDEMPIERE-6386 Detail tabs don't have control over slow or big queries (FHCA-6139)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
[IDEMPIERE-6420:The Info column description is incorrect because it uses the name instead](https://idempiere.atlassian.net/browse/IDEMPIERE-6420)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or …
=> IDEMPIERE-6420:The Info column description is incorrect because it uses

.github/workflows/sonarqube.yml
1. setting memory is change on latest (5.x) https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/scanners/sonarscanner-for-maven/#if-you-get-a-javalangoutofmemoryerror
2. specifying the version instead of using the latest to avoid breaking changes at an unwanted time
[IDEMPIERE-6437:Change sonarqube analysis to manual workflow](https://idempiere.atlassian.net/browse/IDEMPIERE-6437)
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have …
=> IDEMPIERE-6437:fix java.lang.OutOfMemoryError: Java heap space on sonarquibe action

org.adempiere.base/src/org/compiere/model/MDepreciationExp.java, org.adempiere.base/src/org/compiere/model/MDepreciationWorkfile.java
[IDEMPIERE-6387:Asset Expense for the same period becomes two after asset addition](https://idempiere.atlassian.net/browse/IDEMPIERE-6387)
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the …
=> IDEMPIERE-6387:Asset Expense for the same period becomes two after asset addition

org.adempiere.base.callout/src/org/compiere/model/CalloutPayment.java
- fix NPE when ConvertedAmt or CurrencyRate are null
- calculate currency rate with 12 decimals - consistency with Conversion Rate calculation in CalloutEngine.rate
https://idempiere.atlassian.net/browse/IDEMPIERE-6472?focusedCommentId=53907
=> IDEMPIERE-6472 Payment - Amounts not recalculated if no BP/Inv leaving corrupt data

RUN_ImportIdempiereDev.sh
- fix issue when passing two parameters, the RUN_SyncDB has a second parameter with different meaning
https://idempiere.atlassian.net/browse/IDEMPIERE-6521
=> IDEMPIERE-6521 Create RUN_ImportIdempiereDev.sh

org.adempiere.base/src/org/compiere/model/MAttachment.java
- testing IDEMPIERE-6570 found that the "read-only" change on MAttachment is not allowing the Migrate Storage Provider to migrate attachments from tenants
=> IDEMPIERE-6314 Issues with attachment on System records

org.adempiere.base/src/org/compiere/model/GridField.java, org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java, org.idempiere.test/src/org/idempiere/test/base/LogicExpressionTest.java
[IDEMPIERE-6635](https://idempiere.atlassian.net/browse/IDEMPIERE-6635) …
=> IDEMPIERE-6635 - Makes the DataProvider a priority for search of context variables and restores 'IDEMPIERE-6473'
