org.adempiere.server-feature/setup/configuration/config.ini
Fixed issue reported by carlos when running console setup. tested swing setup and idempiere server script too.
=> IDEMPIERE-4136: Fixing console-setup errors.

migration/i7.1z/oracle/201804121850_Extend_Export_Feature.sql, migration/i7.1z/postgresql/201804121850_Extend_Export_Feature.sql, org.adempiere.base-feature/feature.xml, org.adempiere.base/plugin.xml, org.adempiere.base/src/org/adempiere/impexp/AbstractXLSXExporter.java, org.adempiere.base/src/org/adempiere/impexp/GridTabXLSXExporter.java, org.adempiere.base/src/org/adempiere/print/export/PrintDataXLSXExporter.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.server-feature/setup/configuration/config.ini, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WReportCustomization.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/ReportAction.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Before building, make sure that local copy of  maven cache for .m2\repository\p2\osgi\bundle\org.apache.poi.poi-ooxml-schemas\4.1.0 is deleted. I noticed that eclipse set target always load fresh copy but mvn verify try to reuse from local cache.
=> IDEMPIERE-2924: Adding XLSX Export support

migration/i7.1z/oracle/201912301640_IDEMPIERE-4065.sql, migration/i7.1z/postgresql/201912301640_IDEMPIERE-4065.sql, org.adempiere.base/src/org/compiere/model/I_PA_ReportColumn.java, org.adempiere.base/src/org/compiere/model/I_PA_ReportLine.java, org.adempiere.base/src/org/compiere/model/X_PA_ReportColumn.java, org.adempiere.base/src/org/compiere/model/X_PA_ReportLine.java, org.adempiere.base/src/org/compiere/report/FinReport.java
@globalqss this pull request has corrected Updated SQL and tested with postgresql and oracle
=> IDEMPIERE-4065: Making report configurable to reverse value

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java
This is minor patch from @nmicoud - I tested integration with eclipse.
=> IDEMPIERE-4247 WTableDirEditor - missing public methods

org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.webservices-feature/.project, org.idempiere.webservices-feature/.settings/org.eclipse.core.resources.prefs, org.idempiere.webservices-feature/.settings/org.eclipse.m2e.core.prefs, org.idempiere.webservices-feature/feature.xml
Fix target platform and feature configuration for slf4j
=> IDEMPIERE-4249 Platform Refresh for 7.1z

migration/i7.1/oracle/202004301515_IDEMPIERE-4261.sql, migration/i7.1/postgresql/202004301515_IDEMPIERE-4261.sql
Fix a typo on ProcessOK message
=> IDEMPIERE-4261

org.adempiere.report.jasper.library/META-INF/spring.handlers
Fix spring handlers configuration
=> IDEMPIERE-4265 Error log at console for first run of Jasper Report

org.adempiere.ui.zk/theme/default/css/fragment/parameter-process.css.dsp, org.adempiere.ui.zk/theme/default/css/fragment/window-size.css.dsp
Replace fixed process modal dialog height with css flex box rule.
=> IDEMPIERE-4266 Remove hard coded modal dialog height

org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.parent/pom.xml
Update zk library to version 9.0.1.2, a hot fix maintenance release for 9.0.1
=> IDEMPIERE-4276 Update zk to release 9.0.1.2

migration/i7.1z/oracle/202005032000_IDEMPIERE-4168.sql, migration/i7.1z/postgresql/202005032000_IDEMPIERE-4168.sql, org.adempiere.base/src/org/adempiere/base/ModelGeneratorApplication.java, org.adempiere.base/src/org/adempiere/util/GenerateModel.java, org.adempiere.base/src/org/adempiere/util/ModelClassGenerator.java, org.adempiere.base/src/org/adempiere/util/ModelGeneratorDialog.java, org.adempiere.base/src/org/adempiere/util/ModelInterfaceGenerator.java, org.adempiere.base/src/org/compiere/model/I_AD_UserMail.java, org.adempiere.base/src/org/compiere/model/X_AD_UserMail.java
Change entity type of WebStore entities from 'D' to 'WSTORE'
Added optional column entity type filter
Regenerate AD_UserMail model class
=> Idempiere 4168

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
Integrated patch from Hiep, tested successfully
=> IDEMPIERE-3233:process dialog:deduce refresh tab when run a process

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/LayoutUtils.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/StatusBar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
Fix size error of infowindow's parameter panel and ad window's error
message popup.
=> IDEMPIERE-4277 Sizing error for Info Window and Error message popup

org.adempiere.base/src/org/compiere/model/MReportView.java, org.adempiere.base/src/org/compiere/print/DataEngine.java
Carlos,
I made changes of replacing variable type X_AD_ReportView by MRerportView.
=> Idempiere 3333

org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
=> IDEMPIERE-4292 QueryTest.testOnlySelection fail on fresh db

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRunningJobs.java
=> IDEMPIERE-4300 DashboardPanel subclass should not cache Env Ctx

org.adempiere.base.callout/META-INF/MANIFEST.MF, org.adempiere.base.process/META-INF/MANIFEST.MF, org.adempiere.base/META-INF/MANIFEST.MF, org.adempiere.eclipse.equinox.http.servlet/META-INF/MANIFEST.MF, org.adempiere.install/META-INF/MANIFEST.MF, org.adempiere.payment.processor/META-INF/MANIFEST.MF, org.adempiere.pipo.handlers/META-INF/MANIFEST.MF, org.adempiere.pipo/META-INF/MANIFEST.MF, org.adempiere.plugin.utils/META-INF/MANIFEST.MF, org.adempiere.replication.server/META-INF/MANIFEST.MF, org.adempiere.replication/META-INF/MANIFEST.MF, org.adempiere.report.jasper.library/META-INF/MANIFEST.MF, org.adempiere.report.jasper/META-INF/MANIFEST.MF, org.adempiere.server-feature/server.product.launch, org.adempiere.server/META-INF/MANIFEST.MF, org.adempiere.ui.zk/META-INF/MANIFEST.MF, org.adempiere.ui/META-INF/MANIFEST.MF, org.apache.ecs/META-INF/MANIFEST.MF, org.compiere.db.oracle.provider/META-INF/MANIFEST.MF, org.compiere.db.postgresql.provider/META-INF/MANIFEST.MF, org.idempiere.felix.webconsole/META-INF/MANIFEST.MF, org.idempiere.hazelcast.service/META-INF/MANIFEST.MF, org.idempiere.maven.to.p2/org.idempiere.maven.to.p2/pom.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.parent/pom.xml, org.idempiere.test/META-INF/MANIFEST.MF, org.idempiere.webservices/META-INF/MANIFEST.MF, org.idempiere.zk.extra/META-INF/MANIFEST.MF
update org.apache.aries.spifly.dynamic.bundle to 1.2.4 to support jdk-12, 13, 14
also upudate asm to latest 7.3.1
=> Idempiere-4298:support update jdk (jdk 12 13 14)

migration/i7.1z/oracle/202005192336_IDEMPIERE-2523.sql, migration/i7.1z/postgresql/202005192336_IDEMPIERE-2523.sql, org.adempiere.base/src/org/compiere/dbPort/Convert.java, org.adempiere.base/src/org/compiere/model/MSequence.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPreference.java
=> IDEMPIERE-2523 improve method to add comment to log script

org.adempiere.base/src/org/compiere/model/MSystem.java, org.adempiere.base/src/org/compiere/util/WebEnv.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPCalendar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRunningJobs.java
=> Idempiere 4300

org.adempiere.base/src/org/adempiere/process/SalesOrderRateInquiryProcess.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java
there was just one call in core, replaced.
=> #resolve IDEMPIERE-4301 Replace MSysConfig.getDouble with getBigDecimal

org.adempiere.base/src/org/compiere/dbPort/Convert.java
Avoid logging the update to ad_sequence caused by the previous fixes for IDEMPIERE-1146 + IDEMPIERE-3234
=> IDEMPIERE-1146 + IDEMPIERE-3234

org.adempiere.base/src/org/compiere/model/MField.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/grid/WQuickEntry.java
=> IDEMPIERE-4307 Quick Entry always retrieve all fields from db

org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.base/src/org/compiere/model/MLookupInfo.java, org.adempiere.base/src/org/compiere/model/MQuery.java
Fix clone of MLookupInfo
Add list reference cache to MLookupFactory
=> IDEMPIERE-4312 Implement cache for list reference at MLookupFactory

org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.base/src/org/compiere/model/MLookupInfo.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
Fix search column for auto complete
=> IDEMPIERE-1540 Autocomplete for field type "Search"

migration/i7.1z/oracle/202006011551_IDEMPIERE-3358_ColombianRegions.sql, migration/i7.1z/postgresql/202006011551_IDEMPIERE-3358_ColombianRegions.sql
correct definition for Colombia to allow capturing addresses by default
add Colombia Regions
=> IDEMPIERE-3358 Dictionary fixes

org.adempiere.base/src/org/compiere/model/GridFieldVO.java, org.adempiere.base/src/org/compiere/model/GridTabVO.java
=> IDEMPIERE-4317 Add GridFieldVO list cache for GridTabVO.create

org.adempiere.base/src/org/compiere/model/MPeriod.java
Do not perform update with MAcctSchema from cache
=> IDEMPIERE-4327 MPeriod.isOpen - should not perform update with cache PO

org.adempiere.base/src/org/compiere/model/MOrder.java
=> IDEMPIERE-4320 Wrong code found in MOrder.reactivateIt

org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/POInfo.java
Do not serialize context and POInfo
=> IDEMPIERE-4332 PO Serialization Optimization

org.adempiere.base/src/org/compiere/util/CacheMgt.java, org.adempiere.base/src/org/idempiere/distributed/IClusterService.java, org.idempiere.hazelcast.service/src/org/idempiere/hazelcast/service/ClusterServiceImpl.java
Use normal map if hazelcast is stand alone
=> IDEMPIERE-4331 Do not use Hazelcast Cache Service if it is standalone

org.adempiere.base/src/org/compiere/model/MProductPricing.java
Bring one more point of failure discovered by Elaine Tan
=> IDEMPIERE-2753 Discount is not calculated when Price List Price <1

org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
This reverts commit fb67a8f375aae0276d83420d07abf8ba4c1e512a.
With latest change the original test is again valid.
=> Revert "IDEMPIERE-4319 Cascade workflow activities (#110)"

org.adempiere.server/src/main/server/org/compiere/server/WorkflowProcessor.java
#resolve
Correct operator in SQL-Query for "Over End Wait" alerts
Tests: 
Test with Limit in AD_WF_Node = 0 => no alert
Test with Limit in AD_WF_Node > 0 => alert after limit
=> IDEMPIERE-4336

migration/i7.1z/oracle/202006231508_IDEMPIERE-4282.sql, migration/i7.1z/postgresql/202006231508_IDEMPIERE-4282.sql, org.adempiere.base.process/src/org/compiere/process/M_PriceList_Create.java, org.adempiere.base/src/org/compiere/model/I_M_DiscountSchemaLine.java, org.adempiere.base/src/org/compiere/model/MProductPO.java, org.adempiere.base/src/org/compiere/model/X_M_DiscountSchemaLine.java
Starting point is the open source version of Compiere org/compiere/process/PriceListCreate.java
This version adds column M_DiscountSchemaLine.Description and rounding options for Hundred and Thousand
Then added to this version the iDempiere changes related to use correctly the T_Selection with AD_PInstance_ID,
and the changes related to Ticket #1002354: Price List Enhancement - which added Product Costs as an option for getting the initial price
=> IDEMPIERE-4282 Error creating a Price List - using -DPostgreSQLNative=Y

org.adempiere.base/src/org/compiere/util/EMail.java
Using Hiep's idea
Co-Authored-By: hieplq <hieplq@users.noreply.github.com>
=> IDEMPIERE-4356 : System properties shouldn't not be used when sending emails

migration/i7.1z/oracle/202007041557_IDEMPIERE-4358.sql, migration/i7.1z/postgresql/202007041557_IDEMPIERE-4358.sql, org.adempiere.base/src/org/compiere/model/MColumn.java, org.adempiere.base/src/org/compiere/model/M_Element.java, org.adempiere.base/src/org/compiere/process/DatabaseColumnDrop.java, org.adempiere.base/src/org/compiere/process/DatabaseColumnRename.java, org.adempiere.base/src/org/compiere/process/DatabaseConstraintDrop.java, org.adempiere.base/src/org/compiere/process/DatabaseTableDrop.java, org.adempiere.base/src/org/compiere/process/DatabaseTableRename.java
https://wiki.idempiere.org/en/NF8.1_Drop_Rename_DB_Objects
=> IDEMPIERE-4358 Processes to drop some objects from database

org.adempiere.base/src/org/compiere/model/MLookup.java
add back onlyActive logic when items is from cache.
=> IDEMPIERE-4349 WTableDirEditor show inactive item

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditor.java, org.adempiere.ui.zk/theme/default/css/fragment/field-editor.css.dsp
Fix CSS field  style not working for WSearchEditor
=> Idempiere 4374

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4380
=> IDEMPIERE-4380 Inconsistencies with selected filter query on tab navigation

org.adempiere.base/src/org/adempiere/base/DefaultLookupFactory.java, org.adempiere.base/src/org/compiere/model/MLocatorLookup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocatorEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WLocatorDialog.java
pass ValidationCode to MLocatorLookup
Fix dynamic display support
Fix filter for grid view
Fix locator dialog not open with the selected locator
=> IDEMPIERE-4382 Locator Editor inconsistent in the application of filter

migration/i7.1z/oracle/202007251842_IDEMPIERE-3413.sql, migration/i7.1z/postgresql/202007251842_IDEMPIERE-3413.sql
Configure most of the report parameters to allow multi selection
https://idempiere.atlassian.net/browse/IDEMPIERE-3413
=> IDEMPIERE-3413 Multi Select List and table reference

org.adempiere.base/src/org/adempiere/impexp/GridTabCSVImporter.java
Fix issue that entity type and language are not being set when imported
https://idempiere.atlassian.net/browse/IDEMPIERE-3897
=> IDEMPIERE-3897 export csv: reference column export like normal column

org.adempiere.base/src/org/compiere/acct/Fact.java
[IDEMPIERE-874](https://idempiere.atlassian.net/browse/IDEMPIERE-874)
=> IDEMPIERE-874 Suspense Account is Posted with Wrong Org on GL Journal

org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3675
=> IDEMPIERE-3675:Create new AD_Session Record for Scheduler run.

org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.base/src/org/compiere/wf/MWFProcess.java
=> IDEMPIERE-1804 Org of WF Process is Default(login) Organization.

org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/MQuery.java
add keyword quote escape to gridtable and mquery
=> IDEMPIERE-4390 Error in the Workflow window

org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MInOutConfirm.java, org.adempiere.base/src/org/compiere/model/MInOutLine.java, org.adempiere.base/src/org/compiere/model/MInOutLineConfirm.java, org.adempiere.base/src/org/compiere/model/MMovement.java, org.adempiere.base/src/org/compiere/model/MMovementConfirm.java, org.adempiere.base/src/org/compiere/model/MMovementLine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2624
=> IDEMPIERE-2624 Cant confirm 0 qty on Movement Confirmation

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WListbox.java
render header again if number of columns change
=> IDEMPIERE-4391 Product Info - columns are not hidden, when remove wh/pl

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WListbox.java
=> IDEMPIERE-4396 Allow idempiere forms sort by header

org.adempiere.base/src/org/adempiere/model/MInfoProcess.java, org.adempiere.base/src/org/adempiere/model/MInfoRelated.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MAttachmentEntry.java, org.adempiere.base/src/org/compiere/model/MInfoColumn.java, org.adempiere.base/src/org/compiere/model/MInfoWindow.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/PO_LOB.java, org.adempiere.base/src/org/compiere/print/MPrintFormat.java, org.adempiere.base/src/org/compiere/print/MPrintFormatItem.java, org.adempiere.base/src/org/compiere/print/MPrintTableFormat.java, org.adempiere.base/src/org/compiere/process/DocActionTemplate.java, org.adempiere.base/src/org/compiere/util/Language.java, org.idempiere.test/src/org/idempiere/test/model/MPrintFormatTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4389
Implement Copy Constructor support for PO
=> IDEMPIERE-4389

org.adempiere.base/src/org/compiere/util/CCache.java, org.adempiere.base/src/org/compiere/util/CacheInfo.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java
add hit and miss count for cache
=> IDEMPIERE-4405 Add basic cache statistics

org.adempiere.base/src/org/adempiere/model/MTabCustomization.java, org.adempiere.base/src/org/compiere/model/MDashboardPreference.java, org.adempiere.base/src/org/compiere/model/MPasswordHistory.java, org.adempiere.base/src/org/compiere/model/MPreference.java, org.adempiere.base/src/org/compiere/model/MUser.java, org.adempiere.base/src/org/compiere/model/MUserPreference.java, org.adempiere.base/src/org/compiere/model/MUserQuery.java, org.adempiere.base/src/org/compiere/model/MUserRoles.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WGadgets.java
Allow saving Tab Customization for System user
https://idempiere.atlassian.net/browse/IDEMPIERE-4386
=> IDEMPIERE-4386 setAD_User_ID() breaks when logged in as System user

org.adempiere.ui.zk/WEB-INF/src/web/js/zkforge/KeyListener.js
remove keydown handle at client side
=> IDEMPIERE-4413:Change Role, disfunction all keyboard shortcuts

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/acct/WAcctViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/FeedbackRequestWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WReportCustomization.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WSQLProcess.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WEMailDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WMediaDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordAccessDialog.java, org.adempiere.ui.zk/theme/default/css/fragment/font-icons.css.dsp
=> IDEMPIERE-4122 missing font icons

org.adempiere.base/src/org/compiere/model/MQuery.java
Fix for printing report parameters - it is printing OPERATOR_EQUAL on reports instead of =
=> IDEMPIERE-4425 Find Window improvements

org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
=> IDEMPIERE-3197 Tab still keep editing indicator when move to next record

org.adempiere.base/src/org/compiere/model/MInvoice.java
IDEMPIERE-1314 getDocumentInfo methods should return translated String
=> IDEMPIERE-4429 BOM Drop to Invoice is throwing error

org.adempiere.base/src/org/compiere/model/MTable.java
Fix Putting into Cache outside Synchronized methods in MTable.
https://idempiere.atlassian.net/browse/IDEMPIERE-4433
=> IDEMPIERE-4433 - MTable error - ConcurrentModificationException

org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridView.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4424
=> IDEMPIERE-4424

org.adempiere.base/src/org/compiere/model/MProcess.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.ui/src/org/compiere/apps/AbstractProcessCtl.java, org.idempiere.test/src/org/idempiere/test/model/ProcessTest.java
Implement chaining of workflow through the use of Process Action
Implement overwrite of Record_ID for Process through Node Parameter
=> IDEMPIERE-4187 implement the usage of workflows in processes

org.adempiere.base/src/org/compiere/acct/Doc_AllocationHdr.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4440
=> IDEMPIERE-4440 NPE in DocAllocationHdr

org.adempiere.base/src/org/compiere/model/Query.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
Add method Query.setRecordstoSkip
https://idempiere.atlassian.net/browse/IDEMPIERE-4447
=> IDEMPIERE-4447 Add offset to Query

org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WLocatorDialog.java
Changed listbox in Locator Dialog to Table Direct.
https://idempiere.atlassian.net/browse/IDEMPIERE-4442
=> IDEMPIERE-4442 Change Locator Dialog TableDirect

org.adempiere.server-feature/utils.unix/oracle/MonitoredSyncDB.sh, org.adempiere.server-feature/utils.unix/oracle/SyncDB.sh, org.adempiere.server-feature/utils.unix/postgresql/MonitoredSyncDB.sh, org.adempiere.server-feature/utils.unix/postgresql/SyncDB.sh
Fix issue caused by previous commit - RUN_SyncDB broken
=> IDEMPIERE-4441 More shellcheck

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/GlobalSearch.java
hi,
can you please check and accept this PR ? 
i'm updating the https://github.com/idempiere/idempiere-fitnesse project and this ID on the globalsearch allow to find easily the element for creating UI automated tests
=> IDEMPIERE-4029 - global search element id

org.adempiere.base/src/org/compiere/dbPort/Convert.java, org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java
Integrate patch from Paul Bowden (Adaxa)
=> IDEMPIERE-4462

org.adempiere.base/src/org/compiere/util/WebUser.java
IDEMPIERE-4287
https://idempiere.atlassian.net/browse/IDWS-8
=> IDWS-8 Cannot update user info in WebStore

org.adempiere.base/src/org/compiere/model/MUserDefField.java, org.adempiere.base/src/org/compiere/model/MUserDefTab.java
Add caching to UserDefTab and UserDefField.
https://idempiere.atlassian.net/browse/IDEMPIERE-4467
=> IDEMPIERE-4467 Window Customisation has not implemented caching

migration/i7.1z/oracle/202008040114_IDEMPIERE-3862.sql
Minor required change detected testing on a custom database
=> IDEMPIERE-3862 ORACLE - Update datatype NVARCHAR2 to VARCHAR2

migration/i7.1/oracle/202009251357_IDEMPIERE-4474.sql, migration/i7.1/postgresql/202009251357_IDEMPIERE-4474.sql, org.adempiere.base/src/org/adempiere/base/Core.java, org.adempiere.base/src/org/adempiere/model/MFreightShipmentProcessor.java, org.adempiere.base/src/org/adempiere/model/MShipperFacade.java, org.adempiere.base/src/org/adempiere/process/OnlineShipmentProcess.java, org.adempiere.base/src/org/adempiere/process/SalesOrderRateInquiryProcess.java, org.adempiere.base/src/org/compiere/model/MFreight.java, org.adempiere.base/src/org/compiere/model/MShippingTransaction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4474
test cases explained in the ticket
=> IDEMPIERE-4474 Automatic calculation of freight charges

org.idempiere.parent/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-4476
=> IDEMPIERE-4476 Upgrade to Tycho 2.0

org.adempiere.base/src/org/compiere/process/SvrProcess.java, org.adempiere.server/src/main/server/org/compiere/server/AdempiereServerMgr.java
Base on patch from NikColonel <polkneket@gmail.com>
=> IDEMPIERE-3676 Incorrect stop of the schedulers

db/ddlutils/oracle/functions/currencyConvertInvoice.sql, db/ddlutils/oracle/functions/currencyConvertPayment.sql, migration/i7.1z/oracle/202010031940_IDEMPIERE-4083.sql, migration/i7.1z/postgresql/202010031940_IDEMPIERE-4083.sql
=> IDEMPIERE-4083 currency rate by document or by transaction

migration/i7.1z/oracle/202010032109_IDEMPIERE-4481.sql, migration/i7.1z/postgresql/202010032109_IDEMPIERE-4481.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4481
=> IDEMPIERE-4481 Fix problem with oracle script lines starting with @

org.adempiere.base/src/org/compiere/model/MTable.java
@hengsin 
On Table we had method not using new Immutable Caching.
=> IDEMPIERE-4287 Fix for AD_Table caching.

org.adempiere.base/src/org/compiere/model/MTable.java
=> IDEMPIERE-4287 Fix for AD_Table caching

org.adempiere.ui.zk/index.zul, org.adempiere.ui.zk/theme/default/css/fragment/tree.css.dsp, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.parent/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-4477
=> IDEMPIERE-4477 Upgrade to Zk 9.5.0

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/StatusBar.java, org.adempiere.ui.zk/theme/default/css/fragment/adwindow.css.dsp
minor refinement - make toolbar and message overflow link easier to click
=> IDEMPIERE-4482 Mobile Improvements

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/theme/default/css/fragment/adwindow.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4493
=> IDEMPIERE-4493 Mobile: Animation for Swipe Gesture

org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultFeedbackService.java
Search recipients in SysConfig and if not found, fallback on System.SupportEMail
=> IDEMPIERE-4461 : Feedback email recipient(s) : add flexibility

migration/i7.1z/oracle/202010161844_IDEMPIERE-4297_NotAdvancedRole.sql, migration/i7.1z/postgresql/202010161844_IDEMPIERE-4297_NotAdvancedRole.sql
The GardenWorld Admin Not Advanced role was added as advanced by mistake
=> IDEMPIERE-4297 Improve test data

org.adempiere.base/src/org/compiere/util/WebUtil.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java
=> IDEMPIERE-4495 github code scanning alerts

org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4211
=> IDEMPIERE 4211

migration/i7.1z/oracle/202010211343_IDEMPIERE-4503.sql, migration/i7.1z/postgresql/202010211343_IDEMPIERE-4503.sql, org.adempiere.base/src/org/compiere/model/GridWindowVO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4503
=> IDEMPIERE-4503 Hide non-working things in Window Customization

migration/i7.1z/oracle/202010241637_IDEMPIERE-2999.sql, migration/i7.1z/postgresql/202010241637_IDEMPIERE-2999.sql, org.adempiere.base/src/org/compiere/model/MAttribute.java, org.adempiere.base/src/org/compiere/model/MAttributeUse.java
Fix security issue about non advanced roles
https://idempiere.atlassian.net/browse/IDEMPIERE-2999?focusedCommentId=46481&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46481
=> IDEMPIERE-2999 Attribute, Table Direct and date field support

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridView.java, org.adempiere.ui.zk/theme/default/css/fragment/adwindow.css.dsp
=> IDEMPIERE-4509 Grid View Horizontal scrolling is not working well

migration/i7.1z/oracle/202010271430_IDEMPIERE-4510.sql, migration/i7.1z/postgresql/202010271430_IDEMPIERE-4510.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4510
Extra comments in the ticket
=> IDEMPIERE-4510 Add New to the toolbar search query combobox

org.adempiere.ui.zk/theme/default/css/theme.css.dsp
Fix error on collapse icon on field groups
=> IDEMPIERE-4482 Mobile Improvements - Font

migration/i7.1z/oracle/202010281235_IDEMPIERE-4511.sql, migration/i7.1z/postgresql/202010281235_IDEMPIERE-4511.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4511
=> IDEMPIERE-4511 Drop ampersand & from messages

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/CompositeADTabbox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridView.java, org.adempiere.ui.zk/theme/default/css/fragment/adwindow.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4514
=> IDEMPIERE-4514 Grid View Layout Bug

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WRadioGroupEditor.java
=> IDEMPIERE-2902 UX: Implement Radio buttons

org.adempiere.base/src/org/compiere/acct/Doc.java, org.adempiere.base/src/org/compiere/acct/Doc_AllocationHdr.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MPayment.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/process/DocumentEngine.java, org.idempiere.test/src/org/idempiere/test/model/InvoiceCustomerTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4516
=> IDEMPIERE-4516 InvoiceCustomerTest show NPE at console

migration/i7.1z/oracle/202011021539_IDEMPIERE-4517.sql, migration/i7.1z/postgresql/202011021539_IDEMPIERE-4517.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4517
=> IDEMPIERE-4517 Some messages missing - toolbar

migration/i7.1z/oracle/202011031550_IDEMPIERE-4519.sql, migration/i7.1z/postgresql/202011031550_IDEMPIERE-4519.sql
Add migration script for the SysConfig key
=> IDEMPIERE-4519 Zk: Implement optional defer rendering for Grid View

org.adempiere.server-feature/utils.unix/unix/DebianInstaller/DEBIAN/control, org.adempiere.server-feature/utils.unix/unix/DebianInstaller/etc/init.d/idempiere
Fixes for debian installer in ubuntu 20.04
=> IDEMPIERE-4521 Release 8.1 - RC

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/DatetimeBox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Timebox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/RequestWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTimeEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WAssignmentDialog.java
Use time pattern defined in language for time fields
https://idempiere.atlassian.net/browse/IDEMPIERE-3921
=> IDEMPIERE-3921 DateTimeBox assigned Time format.

org.adempiere.ui.zk/theme/default/css/theme.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4536
=> IDEMPIERE-4536 Allow minor customizations in default theme

org.adempiere.base.process/src/org/compiere/process/RequestEMailProcessor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4547
=> IDEMPIERE-4547 Request EMail Processor - Unknown Parameter: p_NestInbox

db/ddlutils/oracle/functions/ProductAttribute.sql, migration/i8.1z/oracle/202011120940_IDEMPIERE-3862.sql, migration/i8.1z/postgresql/202011120940_IDEMPIERE-3862.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-3862
=> IDEMPIERE-3862 ORACLE - Update datatype NCHAR to CHAR

migration/i8.1z/oracle/202011121113_IDEMPIERE-4542.sql, migration/i8.1z/postgresql/202011121113_IDEMPIERE-4542.sql, org.adempiere.base/src/org/compiere/model/MDocumentStatus.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4542
=> IDEMPIERE-4542 Cannot report from window _My Unprocessed Documents_

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPaySelect.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4544
=> IDEMPIERE-4544 Payment Selection cannot be used in mobile portrait

org.adempiere.ui.zk/WEB-INF/src/fi/jawsy/jawwa/zk/atmosphere/AtmosphereServerPush.java, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/js/adempiere/local/storage/token.js, org.adempiere.ui.zk/WEB-INF/src/web/js/adempiere/local/storage/zk.wpd, org.adempiere.ui.zk/WEB-INF/src/web/js/jawwa/atmosphere/serverpush.js, org.adempiere.ui.zk/WEB-INF/web.xml, org.adempiere.ui.zk/WEB-INF/zk.xml, org.adempiere.ui.zk/index.zul, org.adempiere.ui.zk/sessiontimeout.zul
https://idempiere.atlassian.net/browse/IDEMPIERE-4512
=> IDEMPIERE-4512 zk9.5 - Timeout page is not working

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordAccessDialog.java
Fix layout for desktop and mobile
Filter the role list to exclude System roles
https://idempiere.atlassian.net/browse/IDEMPIERE-2418
=> IDEMPIERE-2418 Record Access Dialog Layout issue

org.adempiere.base/src/org/compiere/model/MOrder.java
**Incorrect price in intercompany document**
Description
I post a question in google group:
https://groups.google.com/g/idempiere/c/taAfzmkSKgk/m/WpMNgt7oBAAJ
Andrea Bellotto
=> IDEMPIERE-4555 Incorrect price in intercompany document

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3566
=> IDEMPIERE-3566 shortcut key for process gear (alt + o) don't effect

org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4465
=> IDEMPIERE-4465 Native Postgres - Error on Convert Layer

org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4556
=> IDEMPIERE-4556 Cannot synchronize columns with a Payment Reference

org.adempiere.base/src/org/compiere/model/MAssetAcct.java
=> IDEMPIERE-4572 Fix NPE

migration/i8.1z/oracle/202011202059_IDEMPIERE-4553.sql, migration/i8.1z/postgresql/202011202059_IDEMPIERE-4553.sql
Inactivate the menu entry for POS - the swing client must activate it
https://idempiere.atlassian.net/browse/IDEMPIERE-4553
=> IDEMPIERE-4553 POS menu option throwing error

migration/i8.1z/oracle/202011121122_IDEMPIERE-4569.sql, migration/i8.1z/postgresql/202011121122_IDEMPIERE-4569.sql
Fix error on Asset material receipt
=> IDEMPIERE-4569 Migration Script

migration/i8.1z/oracle/202011221417_IDEMPIERE-4572.sql, migration/i8.1z/postgresql/202011221417_IDEMPIERE-4572.sql
IDEMPIERE-4207 Fill Testing Asset Data
IDEMPIERE-4297 Improve test data
https://idempiere.atlassian.net/browse/IDEMPIERE-4572
=> IDEMPIERE-4572 NPE - Error posting Asset addition

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeInstance.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4417
=> IDEMPIERE-4417 Cancel ASI selection not closing properly

org.adempiere.base/src/org/compiere/model/MRfQResponse.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4285
=> IDEMPIERE-4285 Cannot send mail while creating RfQ Response

org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4268
=> IDEMPIERE-4268 Web Services : Read miss cross-tenant check

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java
Fix problem changing client in role panel when more than 2 clients
=> IDEMPIERE-4268 Fix issue with change client

org.adempiere.base/src/org/compiere/model/MMatchPO.java, org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4575
=> IDEMPIERE-4575 Cannot complete Material Receipt from negative PO

.github/workflows/codeql-analysis.yml
checkout full git history for sonar
add cache for sonar and maven
add sonar step
=> IDEMPIERE-4360 add sonarcloud.io

.github/workflows/codeql-analysis.yml, pom.xml
=> Idempiere 4360

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPActivities.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPRunningJobs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WRC2FieldOrderPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WRC3SortCriteriaPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WGadgets.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4561
DPActivities
DPRunningJobs
WChosenboxSearchEditor
WGadgets
WRC2FieldOrderPanel
WRC3SortCriteriaPanel
WWFActivity
=> IDEMPIERE-4561 Font Icons not used in several points

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/report/HTMLExtension.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java, org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/report.js, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/preference.zul
- Fix broken menu icon for html report
- Fix an issue with switching theme
=> IDEMPIERE-4421 Html asset versioning should allow fluent deployment

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ChosenSearchBox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxListEditor.java, org.adempiere.ui.zk/WEB-INF/src/web/js/chosenbox/Chosenbox.js
- add display of button
- fix dropdown doesn't render properly at Firefox
=> IDEMPIERE-4101 [Chosenbox] Multi select don't work in Firefox

org.idempiere.test/idempiere.unit.test.launch
Fix launcher to avoid adding all custom plugins every time I try to execute it
=> IDEMPIERE-4289 Implement Support for JUnit5 Unit Testing

migration/i8.1z/oracle/202012102125_IDEMPIERE-4595.sql, migration/i8.1z/postgresql/202012102125_IDEMPIERE-4595.sql, org.adempiere.base.callout/src/org/compiere/model/Callout_AD_Process_Para.java
Implement same callouts as in AD_Column
https://idempiere.atlassian.net/browse/IDEMPIERE-4595
This makes really fast the creation of process parameters.
=> IDEMPIERE-4595 Autofill process parameters with smart defaults

org.adempiere.base-feature/model.generator.launch, org.adempiere.base/src/org/adempiere/base/ModelGeneratorApplication.java, org.adempiere.base/src/org/adempiere/util/ModelGeneratorDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4581
comes from https://github.com/idempiere/idempiere/pull/434
=> IDEMPIERE-4581 Model generator should isn't dialog it should be window

org.adempiere.server/idempiere.html, org.adempiere.server/src/main/home/org/bmlaurus/home/Prop.java, org.adempiere.server/src/main/home/org/bmlaurus/home/home.properties
=> IDEMPIERE-4521 Release 8.1 - replace IRC with mattermost

Credits.html, org.adempiere.server-feature/build.properties, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/window-size.css.dsp
Work in progress
The file Credits.html is just a template until defined
https://idempiere.atlassian.net/browse/IDEMPIERE-4580
=> IDEMPIERE-4580 Refactor about credits

migration/i8.1z/oracle/202012151609_IDEMPIERE-4601.sql, migration/i8.1z/postgresql/202012151609_IDEMPIERE-4601.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPluginManager.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/AboutWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4601
=> IDEMPIERE-4601 Move Plugin manager from About to a Form

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4603
=> IDEMPIERE-4603 Find * character cause postgresql error

org.adempiere.server-feature/pom.xml
=> IDEMPIERE-4604 Release 8.2 Phong

org.adempiere.install/META-INF/MANIFEST.MF, org.adempiere.install/install.app.launch, org.adempiere.install/install.console.app.launch, org.adempiere.install/src/org/compiere/install/ConfigurationData.java, org.adempiere.server-feature/setup/configuration/config.ini
https://idempiere.atlassian.net/browse/IDEMPIERE-4618
=> IDEMPIERE-4618 Obfuscate ADEMPIERE_KEYSTOREPASS as suggested by jetty

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/find-window.css.dsp
Base on pull request 487 from Flemming Birch (gsjeffen)
https://idempiere.atlassian.net/browse/IDEMPIERE-4612
=> IDEMPIERE-4612 Improve layout of Find Dialog

org.adempiere.base/src/org/compiere/wf/MWorkflow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4615
=> IDEMPIERE-4615 Cross Tenant Workflow Node cause - Cross tenant PO issue

org.adempiere.base/src/org/compiere/model/MInvoice.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4623
=> IDEMPIERE-4623 Cash POS Sales Order is leaving wrong BP balance

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/DocumentSearchController.java
Added overflow style parameter to VLayout.
https://idempiere.atlassian.net/browse/IDEMPIERE-4630
=> IDEMPIERE-4630  Global Search, Tab Search has no scroll

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
add back the line that's wrongly remove in the review of PR 501
=> IDEMPIERE-4485 Info Window Columns has no Value preference

org.adempiere.base/src/org/compiere/util/Ini.java
Implement suggestions from Hiep on https://github.com/idempiere/idempiere/pull/498
https://idempiere.atlassian.net/browse/IDEMPIERE-4602
=> IDEMPIERE-4602 Encrypt passwords on properties files (FHCA-1982)

org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.base/src/org/compiere/model/MQuery.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4631
=> IDEMPIERE-4631 Lead window -> NPE GridFieldVO.loadLookupInfo: No LookupInfo for BP_Location_ID

org.adempiere.server-feature/console-setup-alt.sh, org.adempiere.server-feature/console-setup.sh, org.adempiere.server-feature/setup-alt.sh, org.adempiere.server-feature/setup.sh, org.adempiere.server-feature/silent-setup-alt.sh, org.adempiere.server-feature/silent-setup.sh
Allow passing the log parameter from command line in setup programs
https://idempiere.atlassian.net/browse/IDEMPIERE-4620
=> IDEMPIERE-4620 Improvements for Setup programs

org.adempiere.base/src/org/compiere/model/MUserDefInfo.java, org.adempiere.base/src/org/compiere/model/MUserDefProc.java, org.adempiere.base/src/org/compiere/model/MUserRoles.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4622
=> IDEMPIERE-4622  Cross Tenant UserDefInfo, Role

org.adempiere.base-feature/model.generator.launch, org.adempiere.base-feature/packinfolder.app.launch, org.adempiere.base-feature/sign.database.build.launch, org.adempiere.base-feature/synchronize-terminology.app.launch, org.adempiere.base-feature/translation.app.launch, org.adempiere.install/install.silent.app.launch, org.adempiere.server-feature/server.product.functionaltest.launch, org.adempiere.server-feature/server.product.launch, org.compiere.db.oracle.provider/META-INF/MANIFEST.MF, org.compiere.db.postgresql.provider/META-INF/MANIFEST.MF
https://idempiere.atlassian.net/browse/IDEMPIERE-4635
=> IDEMPIERE-4635 Model Generator launch configuration broken

org.adempiere.base/src/org/compiere/model/StandardTaxProvider.java
RMA Tax have Save After Delete.
https://idempiere.atlassian.net/browse/IDEMPIERE-4637
=> IDEMPIERE-4637  Cross Tenant RMA, Tax Rate issue

org.adempiere.server-feature/utils.unix/unix/idempiere_Debian.sh, org.adempiere.server-feature/utils.unix/unix/idempiere_RedHat.sh, org.adempiere.server-feature/utils.unix/unix/idempiere_Suse.sh
https://idempiere.atlassian.net/browse/IDEMPIERE-4634
=> IDEMPIERE-4634 idempiere service scripts still generating myEnvironment.sav as root

org.adempiere.base/src/org/compiere/model/MRecentItem.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WCtxHelpSuggestion.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4639
=> IDEMPIERE-4639 Cross tenant issues with context help

org.adempiere.base/src/org/compiere/model/GridField.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4641
=> IDEMPIERE-4641 AD_ProcessPara.DisplayLogic is not accepting @Value_ID.ForeignColumn@ notation

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPluginManager.java
Fix index out of bounds error - when selecting a plugin and then filtering for a number of items lower than the selected index
=> IDEMPIERE-4647 Plugin Manager improvement

org.adempiere.base/src/org/compiere/util/Language.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4649
=> IDEMPIERE-4649 NPE when running Change base language with a fake language (as instructed)

migration/i8.2/oracle/202101131048_IDEMPIERE-4645.sql, migration/i8.2/postgresql/202101131048_IDEMPIERE-4645.sql, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4645
=> IDEMPIERE-4645 Search by special field types failing

migration/i8.2/oracle/202101152101_IDEMPIERE-4650.sql, migration/i8.2/postgresql/202101152101_IDEMPIERE-4650.sql, org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4650
=> IDEMPIERE-4650 Problems with Language Management in PO

org.adempiere.base.process/src/org/compiere/process/CommissionCalc.java, org.adempiere.base.process/src/org/compiere/process/ExpenseAPInvoice.java, org.adempiere.base.process/src/org/compiere/process/ImportInventory.java, org.adempiere.base.process/src/org/compiere/process/ImportPayment.java, org.adempiere.base.process/src/org/compiere/process/PaySelectionCreateFrom.java, org.adempiere.base.process/src/org/compiere/process/SequenceCheck.java, org.adempiere.base/src/org/compiere/impexp/OFXFileBankStatementLoader.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/MPayment.java, org.adempiere.base/src/org/compiere/model/MProduction.java, org.adempiere.base/src/org/compiere/model/MProductionPlan.java, org.adempiere.base/src/org/globalqss/process/CashFlow.java, org.adempiere.eclipse.equinox.http.servlet/src/org/adempiere/eclipse/equinox/http/servlet/ServletContextAdaptor.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/GenericPOElementHandler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4652
=> IDEMPIERE-4652 Remove Eclispe warnings

migration/i8.2/oracle/202101190630_IDEMPIERE-4653.sql, migration/i8.2/postgresql/202101190630_IDEMPIERE-4653.sql, org.adempiere.base/src/org/adempiere/exceptions/DBException.java, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4653
=> IDEMPIERE-4653 Improve timeout handling of window tab

org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
IDEMPIERE-4087
IDEMPIERE-3760
https://idempiere.atlassian.net/browse/IDEMPIERE-4660
=> IDEMPIERE-4660 Wrong code in virtual columns broke IDEMPIERE-2356

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4657
=> IDEMPIERE-4657 Search Dialog Columns are duplicated when table is present in multiple window tabs.

org.adempiere.base/src/org/compiere/model/MUserMail.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4664
=> IDEMPIERE-4664 Cross tenant issue sending email with a System template

org.adempiere.server-feature/build.properties
https://idempiere.atlassian.net/browse/IDEMPIERE-4668
=> IDEMPIERE-4668 update*.bat not included in windows installers

org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4667
=> IDEMPIERE-4667 Project can not be printed using template print format

org.adempiere.base/src/org/compiere/model/MLocator.java, org.adempiere.base/src/org/compiere/model/MStorageOnHand.java, org.adempiere.base/src/org/compiere/model/MStorageReservation.java, org.idempiere.test/src/org/idempiere/test/base/MStorageTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4659
=> IDEMPIERE-4659 MStorageOnHand and MStorageReservation api improvements

org.adempiere.server-feature/utils.unix/RUN_ImportIdempiere.sh, org.adempiere.server-feature/utils.windows/RUN_ImportIdempiere.bat
https://idempiere.atlassian.net/browse/IDEMPIERE-4670
=> IDEMPIERE-4670 RUN_ImportIdempiere can call RUN_SyncDB and sign-database

org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4662
=> IDEMPIERE-4662 Some problems of sort at window before save

org.adempiere.base/src/org/compiere/process/DocumentEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/StatusBar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4672
=> Improve the StatusBar Menupopup to render HTML text

migration/i8.2/oracle/202101260800_IDEMPIERE-4654.sql, migration/i8.2/postgresql/202101260800_IDEMPIERE-4654.sql, org.adempiere.base.process/src/org/compiere/process/InOutGenerate.java, org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/process/ServerProcessCtl.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4654
=> IDEMPIERE-4654 Sales Order After Receipt Delivery Rule is not working

org.adempiere.base/src/org/compiere/model/MArchive.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4673
=> IDEMPIERE-4673 PackOut fails to export attachments with File storage provider

org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.base/src/org/compiere/model/MPInstanceLog.java, org.adempiere.base/src/org/compiere/process/ProcessInfoUtil.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java
* Added also a refactor for the INSERT INTO AD_PInstance_Log to use safer binding variables and add method saveEx
https://idempiere.atlassian.net/browse/IDEMPIERE-4678
=> IDEMPIERE-4678 Save log informing Notice created when background job

org.adempiere.base/src/org/compiere/util/Login.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4685
=> IDEMPIERE-4685 Cross tenant PO reading request detected from session for table AD_User Record_ID

org.adempiere.base.process/src/org/compiere/process/CreateWindowFromTable.java
Solve issue with SeqNo=0
https://idempiere.atlassian.net/browse/IDEMPIERE-1026
=> IDEMPIERE-1026 Button on table to create automatically the window

org.adempiere.base.process/src/org/compiere/process/ImportBankStatement.java, org.adempiere.base.process/src/org/compiere/process/LoadBankStatement.java, org.adempiere.base/src/org/compiere/model/MBankStatementLoader.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4698
=> IDEMPIERE-4698 Load/Import Bank Statement issues

org.adempiere.base/src/org/compiere/model/MRole.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4693
=> IDEMPIERE-4693 2Pack Hangs in 7.1+ / IDEMPIERE-2767

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/IndexColumnElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/TableIndexElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ViewColumnElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ViewComponentElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4700
=> IDEMPIERE-4700 PackOut is creating index and view data for Dictionary entries when export dictionary is disabled

org.adempiere.base/src/org/compiere/util/Env.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4701
=> IDEMPIERE-4701 Env.parseVariable is parsing boolean values wrong

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADSortTab.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4703
=> IDEMPIERE-4703 Cross tenant issue on sort tabs

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Messagebox.java
This replaces the retracted PR of the same name.  https://github.com/idempiere/idempiere/pull/583
(Original PR used the wrong source branch and can not be fixed)
=> IDEMPIERE-4702 Messagebox enhancement: Esc key closes Dialog with cancel

migration/i8.2z/oracle/202102180540_IDEMPIERE-4705.sql, migration/i8.2z/postgresql/202102180540_IDEMPIERE-4705.sql, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/CompositeADTabbox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridView.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/IADTabpanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4705
=> IDEMPIERE-4705 Add grid toggle button to Detail Pane

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4084
Based on what was discussed in the ticket this is a new pull request, more information added to the ticket.
=> IDEMPIERE-4084 Improve button access logic

org.adempiere.base/src/org/compiere/process/DatabaseTableRename.java
Rename the table also in whereclause and orderbyclause in AD_Tab and AD_Ref_Table
https://idempiere.atlassian.net/browse/IDEMPIERE-4358
=> IDEMPIERE-4358 Rename table issue

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
This pull request solved the issue mentioned in the ticket about dynamic display not working on overflow buttons neither on mobile nor desktop.
=> Idempiere 4084

org.adempiere.base/src/org/compiere/process/ProcessInfo.java
* Add logging for possible severe issue
https://idempiere.atlassian.net/browse/IDEMPIERE-4710
=> IDEMPIERE-4710 NPE in ProcessInfo.getLastServerRebootDate()

migration/i8.2/oracle/202102191922_IDEMPIERE-4713.sql, migration/i8.2/postgresql/202102191922_IDEMPIERE-4713.sql, org.adempiere.base/src/org/compiere/model/I_AD_Menu.java, org.adempiere.base/src/org/compiere/model/I_AD_Window.java, org.adempiere.base/src/org/compiere/model/X_AD_Menu.java, org.adempiere.base/src/org/compiere/model/X_AD_Window.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/FavoriteSimpleTreeModel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/AbstractDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/IDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ADForm.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/AbstractMenuPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4713
=> IDEMPIERE-4713 Allow definition of context variables to inject on menu and window definition

migration/i8.2/oracle/202103081357_IDEMPIERE-4714.sql, migration/i8.2/postgresql/202103081357_IDEMPIERE-4714.sql, org.adempiere.base/src/org/compiere/model/MColumn.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4714
=> IDEMPIERE-4714 email password changes being displayed in the change log

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/IProcessParameterListener.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/process/BankTransferParameterListener.java
* based on patch from Anozi Mada
https://idempiere.atlassian.net/browse/IDEMPIERE-4692
=> IDEMPIERE-4692 Mandatory range parameters : "To" style not updated after being filled manually

org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java, org.adempiere.base/src/org/compiere/model/MOrderPaySchedule.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4723
=> IDEMPIERE-4723 - Clean up dead code on MOrder* classes

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4708
=> IDEMPIERE-4708 Context from ProcessParameterPanel is not cleared when closing the window

org.adempiere.pipo/src/org/adempiere/pipo2/POFinder.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java
* Fix Cross tenant PO reading request ...
https://idempiere.atlassian.net/browse/IDEMPIERE-4733
=> IDEMPIERE-4733 2Pack - -Cannot export and import data from one client to another client

org.adempiere.base/src/org/compiere/model/MAuthorizationCredential.java
* Fix hardcoded reference to EMail scope in the processToken method
https://idempiere.atlassian.net/browse/IDEMPIERE-3101
=> IDEMPIERE-3101 implement OAuth2 for mail (gmail, outlook and other mail system)

org.adempiere.base/src/org/compiere/model/MInventory.java, org.adempiere.base/src/org/compiere/model/MInventoryLine.java, org.adempiere.base/src/org/compiere/model/MInvoice.java, org.adempiere.base/src/org/compiere/model/MInvoiceBatch.java, org.adempiere.base/src/org/compiere/model/MInvoiceBatchLine.java, org.adempiere.base/src/org/compiere/model/MInvoiceLine.java, org.adempiere.base/src/org/compiere/model/MInvoicePaySchedule.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4723
=> IDEMPIERE-4723 - Clean up dead code on MInvoice*/MInventory* classes

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4731
=> IDEMPIERE-4731 No default salesrep_id in PO/SO,Invoice when using 'Change Role'

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WResetPassword.java
IDEMPIERE-4287
https://idempiere.atlassian.net/browse/IDEMPIERE-4738
=> IDEMPIERE-4738 Password for user System cannot be changed

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4743
=> IDEMPIERE-4743- Fixed Shift+Alt+N to save and create in detail

org.adempiere.base.process/src/org/compiere/process/CreateWindowFromTable.java
Fixes order by SQL generation error in CreateWIndowFromTable process.
JIra: https://idempiere.atlassian.net/browse/IDEMPIERE-4745
=> IDEMPIERE-4745 Fixes order by SQL generation error

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4742
=> IDEMPIERE-4742 Delete button on detail tab is not disabled for processed records

org.adempiere.base.process/src/org/compiere/process/CreateWindowFromTable.java, org.adempiere.base/src/org/adempiere/model/GenericZoomProvider.java, org.adempiere.base/src/org/compiere/model/MTable.java, org.adempiere.base/src/org/compiere/model/MTree_Base.java, org.adempiere.base/src/org/idempiere/process/MoveClient.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java
* Implementing suggestion from Andreas Sumerauer
* Fix issue in IDEMPIERE-3916 (Move Client) and IDEMPIERE-1026 (Create Window from Table)
https://idempiere.atlassian.net/browse/IDEMPIERE-4746
=> IDEMPIERE-4746 Wrong usage of MTable.getColumnIndex

org.adempiere.base/src/org/compiere/wf/MWFActivity.java
Issue: https://idempiere.atlassian.net/browse/IDEMPIERE-4747
=> IDEMPIERE-4747 Workflow Activity do not pass PO from Workflow Process

org.adempiere.base/src/org/compiere/process/DocumentEngine.java, org.idempiere.test/src/org/idempiere/test/base/MatchPOTest.java
=> IDEMPIERE-4747 Pass PO object from MWFProcess to MWFActivity

org.adempiere.base/src/org/compiere/model/MColumn.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ColumnElementHandler.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoFiller.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4756
=> IDEMPIERE-4756 2pack import problem

migration/i8.2/oracle/202104121227_IDEMPIERE-4748.sql, migration/i8.2/postgresql/202104121227_IDEMPIERE-4748.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4748
=> IDEMPIERE-4748 Window, Tab & Field: Fields that are not displayed in the frontend window are hidden also in the backend.

org.adempiere.base/src/org/compiere/util/Trx.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4759
=> IDEMPIERE-4759 Method to create Trx with other Connection (FHCA-2544)

org.adempiere.base/src/org/compiere/model/GridTable.java, org.adempiere.base/src/org/compiere/model/MAcctSchema.java, org.adempiere.base/src/org/compiere/model/MClient.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/MSystem.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/model/TranslationTable.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxListEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4764
- Change setting for all caches to be non-distributed
=> IDEMPIERE-4764 Hazelcast distributed cache can be an issue in some environments

org.adempiere.base/src/org/compiere/model/MInOut.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4760
Disable Credit Check on Customer Returns.
=> IDEMPIERE-4760 Credit check do not allow complete Customer Return

org.adempiere.base/src/org/compiere/model/MLocator.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WLocatorDialog.java
IDEMPIERE-4442 Change Locator Dialog ListBox to Tabledirect (autocomplete)
* Fix an issue not setting the new locator created when returning
https://idempiere.atlassian.net/browse/IDEMPIERE-1405
=> IDEMPIERE-1405 Locator Dialog allows to create locators without any check

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WButtonEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4766
=> IDEMPIERE-4766 Record ID button would be more useful if it shows the ID

org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeInstance.java, org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4768
WIP
Pending unit test
Pending review why this is not failing with sample GW data
=> IDEMPIERE-4768 Cannot ship in some cases when multiple ASI with different material policy

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4769
=> IDEMPIERE-4769 False result in validation for pending changes

migration/i8.2/oracle/202104162211_IDEMPIERE-4762.sql, migration/i8.2/postgresql/202104162211_IDEMPIERE-4762.sql, org.adempiere.base.process/src/org/idempiere/process/MigrateStorageProvider.java, org.adempiere.base/src/org/compiere/model/AttachmentFileSystem.java, org.adempiere.base/src/org/compiere/model/I_AD_Archive.java, org.adempiere.base/src/org/compiere/model/I_AD_Attachment.java, org.adempiere.base/src/org/compiere/model/I_AD_Image.java, org.adempiere.base/src/org/compiere/model/MArchive.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.base/src/org/compiere/model/MImage.java, org.adempiere.base/src/org/compiere/model/MStorageProvider.java, org.adempiere.base/src/org/compiere/model/X_AD_Archive.java, org.adempiere.base/src/org/compiere/model/X_AD_Attachment.java, org.adempiere.base/src/org/compiere/model/X_AD_Image.java, org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4762
=> IDEMPIERE-4762 Add AD_StorageProvider_ID to AD_Attachment (FHCA-1165)

org.adempiere.base.process/src/org/compiere/process/RequestEMailProcessor.java, org.adempiere.base/src/org/compiere/util/EmailSrv.java
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4765
=> IDEMPIERE-4765 IMAPS limited to GMAIL

migration/i8.2z/oracle/202102201441_IDEMPIERE-4709.sql, migration/i8.2z/postgresql/202102201441_IDEMPIERE-4709.sql, org.adempiere.base/plugin.xml, org.adempiere.base/src/org/adempiere/model/CalloutPrintFormatType.java, org.adempiere.base/src/org/adempiere/print/export/PrintDataExcelExporter.java, org.adempiere.base/src/org/compiere/model/I_AD_PrintFormatItem.java, org.adempiere.base/src/org/compiere/model/X_AD_PrintFormatItem.java, org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.base/src/org/compiere/print/MPrintFormatItem.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java
Ticket - https://idempiere.atlassian.net/browse/IDEMPIERE-4709
Based From branch: https://github.com/devcoffee/idempiere/tree/IDEMPIERE-4709
Removed formatting, Revert of Commit and custom target platform changes.
=> IDEMPIERE-4709 - Print Format Item: implement script column (expression)

org.adempiere.base/src/org/compiere/print/DataEngine.java
Fix issue when using spaces on the name of the print format item
=> IDEMPIERE-4709 Print Format Item: implement script column (expression)

org.idempiere.maven.to.p2/org.idempiere.webservice.client/pom.xml, org.idempiere.maven.to.p2/pom.xml, org.idempiere.parent/pom.xml
=> IDEMPIERE-4711 Upgrade to Tycho 2.3

org.adempiere.base/src/org/compiere/model/GridTable.java
Revert change to assign the variable _TabInfo_SQL just on some log level
https://idempiere.atlassian.net/browse/IDEMPIERE-4372
=> IDEMPIERE-4372 Performance: only add log record and sql statement to context if trace/debug level <= debug/info

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeInstance.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4715
=> COF #11523 / IDEMPIERE-4715 - attribute set instance: new qty available column and group results in select existing record dialog

org.adempiere.server/src/main/server/org/compiere/server/LogFileInfo.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java
Sort logs and schedulers in IDempiere Monitor
=> IDEMPIERE-4776 - iDempiere Monitor: Sort logs and Schedulers

org.adempiere.ui/src/org/compiere/apps/form/Match.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4774
Wrong number sign when matching Vendor Return and Credit Memo
=> IDEMPIERE-4774 Matching PO-Receipt-Invoice is still view Vendor RMA as unmatched receipt

org.adempiere.base/src/org/compiere/util/DB.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4777
=> IDEMPIERE-4777 New table whose name ends in "Line" and does not have a Header table

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/NumberBox.java, org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/calc.js
* Fix not filling the box when the initial value is zero
* Fix removing  the leading zeroes to avoid octal calculations
=> IDEMPIERE-4783 Changing the way number field with calculator are handled

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/Extensions.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/IDashboardGadgetFactory.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4791
=> IDEMPIERE-4791 Pass PA_DashboardContent information to IDashboardGadgetFactory

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-434
WTabEditor is not supported at this moment.
I did not know how to handle when we want to save Record and we have Mandatory Field on not selected Group Tab.
=> IDEMPIERE-434  Tab field group is not available in web

org.adempiere.base/src/org/compiere/model/MStatusLine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4798
=> IDEMPIERE-4798 Add Event Before Parse Status Line

org.adempiere.base/src/org/compiere/model/GridTab.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4799
=> IDEMPIERE-4799 - Window cannot open detail on nested tabs connected through Parent Link Column

migration/i8.2/oracle/202105291354_IDEMPIERE-4804.sql, migration/i8.2/postgresql/202105291354_IDEMPIERE-4804.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ChangePasswordPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4804
=> IDEMPIERE-4804 Message in Reset Password Panel is misleading

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4803
Added Check for Columname that ends with "tedBy".
Added Missing AD_Reference_ID for Related Info Window columnInfo.
=> IDEMPIERE-4803 Related Info Window Display Bug

org.adempiere.base/src/org/compiere/model/MCountry.java
Jira: https://idempiere.atlassian.net/browse/IDEMPIERE-4815
=> IDEMPIERE-4815 FIX Check C_Country_ID when getting cached data.

migration/i8.2z/oracle/202105241446_IDEMPIERE-4796.sql, migration/i8.2z/postgresql/202105241446_IDEMPIERE-4796.sql, org.adempiere.base.process/src/org/compiere/process/RequestEMailProcessor.java, org.adempiere.base/src/org/compiere/util/EmailSrv.java
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4796
=> IDEMPIERE-4796 Request EMail Processor  - Html email processing type parameter

migration/i8.2/oracle/202106021000_IDEMPIERE-4813.sql, migration/i8.2/postgresql/202106021000_IDEMPIERE-4813.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutProcessCustomization.java, org.adempiere.base.callout/src/org/compiere/model/CalloutWindowCustomization.java, org.adempiere.base/src/org/compiere/model/MUserDefProc.java
* Implement for Window, Process and Info Window Customization:
* Change to non-updateable the columns that have related children
* Change default to NULL in role, user and language
* Disable the autofilling of name, description and help
* Implement the unique validation using index
https://idempiere.atlassian.net/browse/IDEMPIERE-4813
=> IDEMPIERE-4813 Process Customization Cross Tenant Error

migration/i8.2/oracle/202106081633_IDEMPIERE-3980.sql, migration/i8.2/postgresql/202106081633_IDEMPIERE-3980.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WImageDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3980
=> IDEMPIERE-3980

org.idempiere.test/src/org/idempiere/test/base/LogicExpressionTest.java
add validation test for boolean logic expression in AD
=> IDEMPIERE-4824 Boolean Logic Expression Enhancements

org.adempiere.base/src/org/adempiere/impexp/AbstractXLSXExporter.java, org.adempiere.base/src/org/adempiere/print/export/PrintDataXLSXExporter.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java
sync xls and xlsx output
https://idempiere.atlassian.net/browse/IDEMPIERE-4565
=> IDEMPIERE-4565 Report (XLSX output) : add header

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/QuickGridView.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/IQuickForm.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WQuickForm.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4839
=> IDEMPIERE-4839 IQuickForm interface

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4844
=> IDEMPIERE-4844 Cross tenant issue on Forgot My Password

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ConfirmPanel.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4840
=> IDEMPIERE-4840: ConfirmPanel with Checkbox

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/Extensions.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4848
=> BUGFIX: Extensions.getQuickEntryService() - fixed cache management issue

org.adempiere.base/src/org/compiere/model/MProduction.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4849
=> IDEMPIERE-4849: fix for MProduction.createLines() storage issue

org.adempiere.base/src/org/compiere/model/MTableIndex.java, org.adempiere.base/src/org/compiere/process/TableIndexValidate.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4847
=> IDEMPIERE-4847 TableIndexValidate: include only active columns in table index

org.adempiere.base/src/org/adempiere/print/export/PrintDataExcelExporter.java, org.adempiere.base/src/org/adempiere/print/export/PrintDataXLSXExporter.java, org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.base/src/org/compiere/print/PrintData.java, org.adempiere.base/src/org/compiere/print/PrintDataColumn.java, org.adempiere.base/src/org/compiere/print/PrintDataElement.java, org.adempiere.base/src/org/compiere/print/PrintDataGroup.java, org.adempiere.base/src/org/compiere/print/PrintDataHandler.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java, org.adempiere.ui.zk/css/report.css, org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/ReportEngineEx.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4227
=> IDEMPIERE-4227 Unable to use 2 print format item with the same AD_Column_ID and different formatting

org.adempiere.base/src/org/compiere/print/ReportEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2937
=> IDEMPIERE-2937 Html Report - Suppress Null checkbox doesn't work

migration/i8.2/oracle/202106291641_IDEMPIERE-4851.sql, migration/i8.2/postgresql/202106291641_IDEMPIERE-4851.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4851
=> IDEMPIERE-4851 Tenant Admin can deactivate his own client.

migration/i8.2/oracle/202106301531_IDEMPIERE-4856.sql, migration/i8.2/postgresql/202106301531_IDEMPIERE-4856.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4856
=> IDEMPIERE-4856 Setting an attribute with type reference doesn't work in german / IDEMPIERE-2999

migration/i8.2/oracle/202106301952_IDEMPIERE-4806.sql, migration/i8.2/postgresql/202106301952_IDEMPIERE-4806.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4806
=> IDEMPIERE-4806 System Configurator window must be Advanced

migration/i8.2/oracle/202106302004_IDEMPIERE-4853.sql, migration/i8.2/postgresql/202106302004_IDEMPIERE-4853.sql, org.adempiere.base.process/src/org/compiere/process/CopyFromPackOut.java, org.adempiere.base/src/org/compiere/model/MPackageExp.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4853
=> IDEMPIERE-4853 Process to copy a Packout definition (FHCA-859)

org.adempiere.base/src/org/adempiere/model/DocActionDelegate.java, org.adempiere.base/src/org/adempiere/model/GenericPO.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/process/DocAction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4578
=> IDEMPIERE-4578 generic DocAction

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/MenuElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4859
=> IDEMPIERE-4859 PackOut with AD_Menu (AD_TreeNodeMM) (FHCA-1374)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/GridView.java
refine auto hide rule for new row
https://idempiere.atlassian.net/browse/IDEMPIERE-4835
=> IDEMPIERE-4835 Grid View: Implement optional hide empty column feature

migration/i8.2z/oracle/202107051142_IDEMPIERE-4865.sql, migration/i8.2z/postgresql/202107051142_IDEMPIERE-4865.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4865
=> IDEMPIERE-4865 Find window enhancements

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
Fix toolbar shortcut is active when it is block by process log dialog
https://idempiere.atlassian.net/browse/IDEMPIERE-4864
=> IDEMPIERE-4864 Fix shortcut handling for combobox and ad window

org.adempiere.report.jasper/src/org/adempiere/report/jasper/ColumnLookup.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ReportStarter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4868
=> IDEMPIERE-4868 Implement column lookup support for Jasper Report

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/form.css.dsp
Co-Authored-By: pmargery <87129041+pmargery@users.noreply.github.com>
=> IDEMPIERE-4872 : Typo on form.css.dsp (pdding -> padding)

org.adempiere.base/src/org/compiere/print/DataEngine.java
Jira: https://idempiere.atlassian.net/browse/IDEMPIERE-4871
=> IDEMPIERE-4871 Added Data Type for Script Column

migration/i8.2z/oracle/202107150800_IDEMPIERE-4841.sql, migration/i8.2z/postgresql/202107150800_IDEMPIERE-4841.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4841
=> IDEMPIERE-4841 Info Window: Implement auto hide empty columns

org.adempiere.base/src/org/compiere/util/MimeType.java
Fix preview of xlsx not working at attachment viewer
https://idempiere.atlassian.net/browse/IDEMPIERE-4801
=> IDEMPIERE-4801 Add IMediaView interface and Keikai implementation

org.adempiere.base/src/org/idempiere/expression/logic/EvaluationVisitor.java, org.idempiere.test/src/org/idempiere/test/base/LogicExpressionTest.java
Fix equal evaluation for numeric expression
https://idempiere.atlassian.net/browse/IDEMPIERE-4881
=> IDEMPIERE-4881 CSS style anomaly - display logic

org.adempiere.ui.zk/WEB-INF/src/org/zkoss/addon/chosenbox/Chosenbox.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4887
=> IDEMPIERE-4887 Chosenbox: Make multi selection easier

org.adempiere.base/src/org/compiere/util/Util.java, org.adempiere.report.jasper/META-INF/MANIFEST.MF, org.adempiere.report.jasper/src/org/adempiere/report/jasper/Activator.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/AttachmentResourceLoader.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/BundleResourceLoader.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ClassResourceLoader.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/FileResourceLoader.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/ReportStarter.java, org.adempiere.report.jasper/src/org/adempiere/report/jasper/WebResourceLoader.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkJRViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4873
=> IDEMPIERE-4873 Jasper Report Starter Refactoring

org.idempiere.parent/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-4711
=> IDEMPIERE-4711 Upgrade to Tycho 2.4

migration/i8.2/oracle/202107211936_IDEMPIERE-4886.sql, migration/i8.2/postgresql/202107211936_IDEMPIERE-4886.sql, org.adempiere.base.process/src/org/compiere/process/ColumnSync.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4886
Created a process parameter "Date From" - when empty or when the table is new it behaves the same as before.
When filled and the table already exists in DB - then all the columns modified after that "Date From" are synchronized.
=> IDEMPIERE-4886 Synchronize multiple columns on ALTER

org.idempiere.printformat.editor/.project, org.idempiere.printformat.editor/.settings/org.eclipse.core.resources.prefs, org.idempiere.printformat.editor/.settings/org.eclipse.m2e.core.prefs, org.idempiere.printformat.editor/src/org/idempiere/printformat/editor/ui/WPrintFormatEditor.java, org.idempiere.printformat.editor/src/org/idempiere/printformat/editor/ui/WPrintFormatEditorForm.java
- add maven for eclipse configs
- remove maximize/restore button
https://idempiere.atlassian.net/browse/IDEMPIERE-4059
=> IDEMPIERE-4059 Print format editor

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/StatusBarPanel.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/borderlayout.css.dsp, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/info-window.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4140
Integrating the patch from Flemming Birch
=> IDEMPIERE-4140 cph::erp Improvement to the layout of the info Windows

migration/i8.2z/oracle/202107281652_IDEMPIERE-4894.sql, migration/i8.2z/postgresql/202107281652_IDEMPIERE-4894.sql, org.adempiere.base/META-INF/MANIFEST.MF, org.adempiere.base/src/org/adempiere/base/Core.java, org.adempiere.base/src/org/compiere/model/I_AD_PrintFormat.java, org.adempiere.base/src/org/compiere/model/I_AD_PrintHeaderFooter.java, org.adempiere.base/src/org/compiere/model/X_AD_PrintFormat.java, org.adempiere.base/src/org/compiere/model/X_AD_PrintHeaderFooter.java, org.adempiere.base/src/org/compiere/print/layout/LayoutEngine.java, org.adempiere.base/src/org/idempiere/print/IPrintHeaderFooter.java, org.adempiere.base/src/org/idempiere/print/StandardHeaderFooter.java, org.idempiere.printformat.editor/src/org/idempiere/printformat/editor/ui/WPrintFormatEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4894
=> IDEMPIERE-4894 OSGi Interface to support custom header and footer

org.adempiere.base/src/org/compiere/model/ProductCost.java
Jira: https://idempiere.atlassian.net/browse/IDEMPIERE-4895
=> IDEMPIERE-4895  Product Cost - Valid Combination Caching

migration/i8.2/oracle/202108051100_IDEMPIERE-4902.sql, migration/i8.2/postgresql/202108051100_IDEMPIERE-4902.sql
=> IDEMPIERE-4902 : Record migration scripts with Dictionnary EntityType

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/form.css.dsp
Implement suggestion from Flemming Birch to fix find dialog status count
https://idempiere.atlassian.net/browse/IDEMPIERE-4140
=> IDEMPIERE-4140 Improvement to the layout of the info Windows

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/BreadCrumb.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4908
=> IDEMPIERE-4908 Not unique in the ID space of ... breadcrumb with same name tabs (FHEG-8847)

migration/i8.2z/oracle/202108091122_IDEMPIERE-4904.sql, migration/i8.2z/postgresql/202108091122_IDEMPIERE-4904.sql, org.adempiere.base/src/org/compiere/model/I_AD_Process_Para.java, org.adempiere.base/src/org/compiere/model/MQuery.java, org.adempiere.base/src/org/compiere/model/X_AD_Process_Para.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4904
=> IDEMPIERE-4904 Add custom query clause support to report parameter

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ADTreeOnDropListener.java
Allow to handle change events in the AD_TreeNodeXX tables.
=> IDEMPIERE-4867 Updating moving node by PO

org.adempiere.base/src/org/compiere/model/PO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4061
=> IDEMPIERE-4061 isTranslated is not set Yes on new Record default

org.adempiere.base/src/org/adempiere/model/GenericZoomProvider.java
- generate fully qualified where clause for generic zoom across
https://idempiere.atlassian.net/browse/IDEMPIERE-2963
=> IDEMPIERE-2963 Error creating report after zoom across

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/BusyDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3646
=> IDEMPIERE-3646 statusupdate should only be shown on its own tab

org.adempiere.base-feature/feature.xml, org.adempiere.base-feature/model.generator.launch, org.adempiere.base-feature/packinfolder.app.launch, org.adempiere.base-feature/sign.database.build.launch, org.adempiere.base-feature/synchronize-terminology.app.launch, org.adempiere.base-feature/translation.app.launch, org.adempiere.base/META-INF/MANIFEST.MF, org.adempiere.base/src/org/adempiere/pdf/Document.java, org.adempiere.base/src/org/compiere/util/Util.java, org.adempiere.install/install.app.launch, org.adempiere.install/install.console.app.launch, org.adempiere.install/install.silent.app.launch, org.adempiere.report.jasper/META-INF/MANIFEST.MF, org.adempiere.server-feature/server.product.functionaltest.launch, org.adempiere.server-feature/server.product.launch, org.adempiere.server-feature/setup/configuration/config.ini, org.adempiere.ui.zk/META-INF/MANIFEST.MF, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java, org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd, org.idempiere.test/idempiere.unit.test.launch
https://idempiere.atlassian.net/browse/IDEMPIERE-4880
=> IDEMPIERE-4880 Replace iText PDF with OpenPDF

migration/i8.2z/oracle/202108172001_IDEMPIERE-3494.sql, migration/i8.2z/postgresql/202108172001_IDEMPIERE-3494.sql, org.adempiere.base.process/src/org/compiere/process/ProjectIssue.java, org.adempiere.base/src/org/adempiere/model/DocActionDelegate.java, org.adempiere.base/src/org/compiere/model/I_C_ProjectIssue.java, org.adempiere.base/src/org/compiere/model/MProjectIssue.java, org.adempiere.base/src/org/compiere/model/X_C_ProjectIssue.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3494
=> IDEMPIERE-3494 Implement DocStatus/DocAction for Project Issue

org.adempiere.base/src/org/compiere/util/EmailSrv.java, org.adempiere.server/src/main/server/org/compiere/server/EMailProcessor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4918
=> IDEMPIERE-4918 Cannot use simple auth after used OAuth (FHCA-2014)

org.adempiere.base/src/org/compiere/model/MColumn.java
fix issue with 2Pack
https://idempiere.atlassian.net/browse/IDEMPIERE-4911
=> IDEMPIERE-4911 Silent fail when translated column is shorter than original column (FHCA-2888)

org.adempiere.base/src/org/compiere/util/Env.java, org.idempiere.test/src/org/idempiere/test/base/LogicExpressionTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4939
=> IDEMPIERE-4939 Implement ability to discover operating system environment variables when parsing context (FHCA-3026)

org.adempiere.ui/src/org/compiere/grid/CreateFromShipment.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4943
=> IDEMPIERE-4943 Create a Material Receipt from Invoice with UOM conversion is leaving corrupt data

migration/i8.2z/oracle/202007171100_IDEMPIERE-4364.sql, migration/i8.2z/oracle/202109031531_IDEMPIERE-4470.sql, migration/i8.2z/postgresql/202007171100_IDEMPIERE-4364.sql, migration/i8.2z/postgresql/202109031531_IDEMPIERE-4470.sql, org.adempiere.base/src/org/compiere/model/MQuery.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4470
Based on pull request 170
Co-authored-by: Igor Pojzl <igor.pojzl@cloudempiere.com>
=> IDEMPIERE-4470 Window Advanced Search - New operator types: AND Not, Or Not

org.adempiere.base/src/org/compiere/util/Trx.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ADTreeOnDropListener.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4937
=> IDEMPIERE-4937 Refreshing the GridTab after moving a node in the Tree

migration/i8.2z/oracle/202109080800_IDEMPIERE-4949.sql, migration/i8.2z/postgresql/202109080800_IDEMPIERE-4949.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/desktop.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4949
=> IDEMPIERE-4949 Desktop tab enhancements

org.adempiere.ui/src/org/compiere/grid/CreateFromInvoice.java
We correct the issue keeping the unit from the in/out record and we are only converting the price of the item.
[https://idempiere.atlassian.net/browse/IDEMPIERE-4885](https://idempiere.atlassian.net/browse/IDEMPIERE-4885)
=> IDEMPIERE-4885 Possible bug with uom conversion on invoice when create from shipment

org.adempiere.base/.project, org.idempiere.parent/.project
minor: remove unnecessary nature and build command from .project
=> IDEMPIERE-4933 Platform update for 9.x

org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.base/src/org/compiere/model/POResultSet.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/AbstractDesktop.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4958
=> IDEMPIERE-4958 Performance improvement for the opening of process dialog

org.adempiere.base/src/org/compiere/util/CacheChangeListener.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java, org.adempiere.base/src/org/compiere/util/DefaultEvaluatee.java
- added cache
https://idempiere.atlassian.net/browse/IDEMPIERE-4924
=> IDEMPIERE-4924 Performance issue with indirect context

org.adempiere.base/src/org/compiere/model/MForm.java, org.adempiere.base/src/org/compiere/model/MLanguage.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ADForm.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/HelpController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4959
=> IDEMPIERE-4959 Performance improvement for the opening of form window

org.adempiere.base-feature/model.generator.launch, org.adempiere.base/src/org/adempiere/util/ModelClassGenerator.java, org.adempiere.base/src/org/compiere/model/I_AD_PInstance_Para.java, org.adempiere.base/src/org/compiere/model/X_AD_PInstance_Para.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4963
=> IDEMPIERE-4963 Performance: avoid loop in X_ class interface getters

org.adempiere.base/src/org/adempiere/model/MInfoProcess.java, org.adempiere.base/src/org/adempiere/model/MInfoRelated.java, org.adempiere.base/src/org/compiere/model/GridWindow.java, org.adempiere.base/src/org/compiere/model/GridWindowVO.java, org.adempiere.base/src/org/compiere/model/MInfoColumn.java, org.adempiere.base/src/org/compiere/model/MInfoWindow.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/DefaultInfoFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/HelpController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4960
=> IDEMPIERE-4960 Performance improvement for the opening of info window

migration/i8.2z/oracle/202109171424_IDEMPIERE-2853.sql, migration/i8.2z/postgresql/202109171424_IDEMPIERE-2853.sql, org.adempiere.base/src/org/compiere/model/MTab.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2853
=> IDEMPIERE-2853 Panel tab as a factory - preserve AD_Tab.IsSortTab for backward compatibility

migration/i8.2z/oracle/202109161712_IDEMPIERE-4906.sql, migration/i8.2z/postgresql/202109161712_IDEMPIERE-4906.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4906
=> IDEMPIERE-4906 Dashboard showing donation message on first log-in

migration/i8.2z/oracle/202107200830_IDEMPIERE-4866.sql, migration/i8.2z/postgresql/202107200830_IDEMPIERE-4866.sql, org.adempiere.base.process/src/org/compiere/process/EMailTest.java, org.adempiere.base/src/org/compiere/model/I_AD_SMTP.java, org.adempiere.base/src/org/compiere/model/MClient.java, org.adempiere.base/src/org/compiere/model/MSMTP.java, org.adempiere.base/src/org/compiere/model/X_AD_SMTP.java, org.adempiere.base/src/org/compiere/util/EMail.java
Replace https://github.com/idempiere/idempiere/pull/783
=> Idempiere 4866 v2

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Tab.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4952
ZK_THEME_USE_FONT_ICON_FOR_IMAGE
=> IDEMPIERE-4952 Image icon missing for Notice, Request, Product and Business Partner tab

migration/i8.2/oracle/202109221858_WrongPara.sql, migration/i8.2/postgresql/202109221858_WrongPara.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4976
=> IDEMPIERE-4976 Wrong parameter in Initial Client Setup (duplicated IsUseSalesRegionDimension)

org.adempiere.base/src/org/compiere/model/MProduct.java
=> IDEMPIERE-4978 Fix error in setting product resource type

org.adempiere.base/src/org/adempiere/util/ModelClassGenerator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4979
=> IDEMPIERE-4979 ModelGenerator class generates entries for inactive ref lists

migration/i8.2/oracle/202109171808_IDEMPIERE-4968.sql, migration/i8.2/postgresql/202109171808_IDEMPIERE-4968.sql, org.adempiere.base/src/org/compiere/model/I_AD_Package_Exp_Detail.java, org.adempiere.base/src/org/compiere/model/I_AD_Package_Imp_Detail.java, org.adempiere.base/src/org/compiere/model/MPackageExpDetail.java, org.adempiere.base/src/org/compiere/model/X_AD_Package_Exp_Detail.java, org.adempiere.base/src/org/compiere/model/X_AD_Package_Imp_Detail.java, org.adempiere.pipo.handlers/plugin.xml, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/JavaShellScriptElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/SQLMandatoryElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/SQLStatementElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ScriptJSR223ElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ShellScriptElementHandler.java, org.adempiere.pipo/src/org/adempiere/pipo2/AbstractElementHandler.java, org.adempiere.pipo/src/org/adempiere/pipo2/PackOutProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4968
=> IDEMPIERE-4968 Enable 2Pack to run java class or script (FHCA-3112 FHCA-3113) / Shell script

org.idempiere.test/META-INF/MANIFEST.MF, org.idempiere.test/idempiere.unit.test.launch, org.idempiere.webservices/META-INF/MANIFEST.MF, org.idempiere.webservices/OSGI-INF/org.compiere.model.WS_ModelFactory.xml, org.idempiere.webservices/OSGI-INF/ws_modelfactory.xml, org.idempiere.webservices/OSGI-INF/wsprocessfactory.xml, org.idempiere.webservices/WEB-INF/src/org/compiere/model/MWebService.java, org.idempiere.webservices/WEB-INF/src/org/compiere/model/MWebServiceMethod.java, org.idempiere.webservices/WEB-INF/src/org/compiere/model/MWebServicePara.java, org.idempiere.webservices/WEB-INF/src/org/compiere/model/MWebServiceType.java, org.idempiere.webservices/WEB-INF/src/org/compiere/model/WS_ModelFactory.java, org.idempiere.webservices/testScripts/postman/https---localhost-8443 WebService.postman_environment.json, org.idempiere.webservices/testScripts/postman/idempiere-soap-as-rest.postman_collection.json
https://idempiere.atlassian.net/browse/IDEMPIERE-4980
=> IDEMPIERE-4980 Update model factory of org.idempiere.webservices

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPreference.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4915
=> IDEMPIERE-4915 Improvements to Preference Popup / fix NPE

migration/i8.2z/oracle/202110051700_IDEMPIERE-4985.sql, migration/i8.2z/postgresql/202110051700_IDEMPIERE-4985.sql
Adding indexes on AD_UserDef_Tab, AD_UserDef_Field, AD_UserDef_Info_Column, AD_UserDef_Proc_Parameter
=> IDEMPIERE-4985 : Missing index on AD_UserDef sub tables

migration/i8.2z/oracle/202111020750_IDEMPIERE-5021.sql, migration/i8.2z/postgresql/202111020750_IDEMPIERE-5021.sql, org.adempiere.base/src/org/adempiere/base/Core.java, org.adempiere.base/src/org/adempiere/util/DefaultReservationTracerFactory.java, org.adempiere.base/src/org/adempiere/util/IReservationTracer.java, org.adempiere.base/src/org/adempiere/util/IReservationTracerFactory.java, org.adempiere.base/src/org/adempiere/util/ReservationLogTracer.java, org.adempiere.base/src/org/compiere/model/I_M_StorageReservationLog.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/model/MStorageReservation.java, org.adempiere.base/src/org/compiere/model/MStorageReservationLog.java, org.adempiere.base/src/org/compiere/model/X_M_StorageReservationLog.java, org.adempiere.ui/src/org/compiere/apps/form/Match.java, org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
- implement log table for movement of QtyReserved and QtyOrdered
https://idempiere.atlassian.net/browse/IDEMPIERE-5021
=> IDEMPIERE-5021 Implement Storage Reservation Log

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/MenuElementHandler.java
Copy code snippet handle common translation from MenuElementHandler.createApplication.
=> IDEMPIERE-5027 Packing out lost translation of sub menu

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/layout.js
https://idempiere.atlassian.net/browse/IDEMPIERE-5024
=> IDEMPIERE-5024 Horizontal scrolling anomaly

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/TableIndexElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5028
=> IDEMPIERE-5028 NPE on 2Pack when a TableIndex deferred cannot find the Table

migration/i8.2z/oracle/202111060700_IDEMPIERE-5031.sql, migration/i8.2z/postgresql/202111060700_IDEMPIERE-5031.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base.process/src/org/compiere/process/InOutGenerate.java, org.adempiere.base/src/org/adempiere/base/event/delegate/AutoProduceEventDelegate.java, org.adempiere.base/src/org/compiere/model/I_M_InOutLine.java, org.adempiere.base/src/org/compiere/model/I_M_Product.java, org.adempiere.base/src/org/compiere/model/I_M_Production.java, org.adempiere.base/src/org/compiere/model/X_M_InOutLine.java, org.adempiere.base/src/org/compiere/model/X_M_Product.java, org.adempiere.base/src/org/compiere/model/X_M_Production.java, org.idempiere.test/src/org/idempiere/test/model/ProductionTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5031
=> IDEMPIERE-5031 Implement auto produce upon shipment for mfg light

org.adempiere.base/src/org/compiere/model/AttachmentFileSystem.java, org.adempiere.base/src/org/compiere/model/MAttachment.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5034
=> IDEMPIERE-5034 NPE and other problems when a file is removed from store attachment filesystem

org.adempiere.ui/src/org/compiere/grid/CreateFromInvoice.java
This now fixes the issue with already invoiced RMA's still being shown in Create From Invoice in the "Receipt" pull down list and fixes the Create from Invoice form not showing any partially invoiced RMA’s in the RMA pulldown list.
=> IDEMPIERE-5026 Create from Invoice showing already invoiced RMA's

org.adempiere.server-feature/server.product.launch, org.adempiere.ui.zk/pom.xml, org.idempiere.jetty.osgi.boot.fragment/META-INF/MANIFEST.MF, org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
https://idempiere.atlassian.net/browse/IDEMPIERE-5035
=> IDEMPIERE-5035 Update of Dependency (November 2021)

org.adempiere.pipo/src/org/adempiere/pipo2/AbstractElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5037
=> IDEMPIERE-5037 PackOut/PackIn must treat EE01/2/4/5 entries as official dictionary

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5036
=> IDEMPIERE-5036 NPE auto-opening a process

migration/i8.2z/oracle/202110090932_IDEMPIERE-4086.sql, migration/i8.2z/postgresql/202110090932_IDEMPIERE-4086.sql, org.adempiere.base/src/org/compiere/model/I_C_DocType.java, org.adempiere.base/src/org/compiere/model/MDocType.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java, org.adempiere.base/src/org/compiere/model/X_C_DocType.java
Please note that new feature is documented at
https://wiki.idempiere.org/en/NF9.1_Product_Without_Pricelist
=> IDEMPIERE-4086: Allow Product without price list on some document type

org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
add unit test
https://idempiere.atlassian.net/browse/IDEMPIERE-4854
=> IDEMPIERE-4854 Bugfixes in InOutGenerate

org.adempiere.base/src/org/compiere/model/MOrder.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5039
=> IDEMPIERE-5039 Negative Lost Sales Quantity

migration/i8.2/oracle/202111161430_IDEMPIERE-4808.sql, migration/i8.2/postgresql/202111161430_IDEMPIERE-4808.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4808
=> IDEMPIERE-4808 Payment Allocation should be IsSOTrx neutral + Product Window

db/ddlutils/oracle/views/M_INOUT_CANDIDATE_V.sql, db/ddlutils/postgresql/views/M_INOUT_CANDIDATE_V.sql, migration/i8.2/oracle/202111161449_IDEMPIERE-2620.sql, migration/i8.2/postgresql/202111161449_IDEMPIERE-2620.sql, org.adempiere.base.process/src/org/compiere/process/InOutGenerate.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2620
=> IDEMPIERE-2620 Customer Drop Ships not implemented

org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/AdempiereActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/Incremental2PackActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/Version2PackActivator.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5045
=> IDEMPIERE-5045 Applying packins is leaving open records in AD_Session (Processed=N)

org.compiere.db.postgresql.provider/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-4933
=> IDEMPIERE-4933 Platform update for 9.x / latest postgresql version

org.adempiere.base/src/org/compiere/Adempiere.java, org.adempiere.base/src/org/compiere/util/CCache.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5046
=> IDEMPIERE-5046 Implement background reset of expire cache

org.adempiere.base/src/org/compiere/model/GridTabVO.java, org.adempiere.base/src/org/compiere/model/MAttribute.java, org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.base/src/org/compiere/util/CCache.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/AbstractService.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5047
=> IDEMPIERE-5047 iDempiere Server Monitor Improvements

org.adempiere.base/src/org/compiere/process/SvrProcess.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5048
=> IDEMPIERE-5048 Minor fix for Scheduler and SvrProcess: set m_trx to null

org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5039
https://idempiere.atlassian.net/browse/IDEMPIERE-4587
=> IDEMPIERE-5039 Negative Lost Sales Quantity / fix unit test IDEMPIERE-4587

migration/i8.2/oracle/202111231355_IDEMPIERE-5051.sql, migration/i8.2/postgresql/202111231355_IDEMPIERE-5051.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5051
=> IDEMPIERE-5051 PaymentExportClass must be advanced field

migration/i8.2z/oracle/202111281338_IDEMPIERE-5060.sql, migration/i8.2z/postgresql/202111281338_IDEMPIERE-5060.sql, org.adempiere.base/src/org/compiere/model/I_AD_ViewComponent.java, org.adempiere.base/src/org/compiere/model/X_AD_ViewComponent.java, org.adempiere.base/src/org/compiere/process/DatabaseViewValidate.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5060
=> IDEMPIERE-5060 iDempiere dictionary view doesn't support UNION ALL

org.idempiere.test/src/org/idempiere/test/model/ProductionTest.java
Fix unit test error on Jenkins
=> IDEMPIERE-1250 Multiple BOM (formulas) support for mfg-light

org.idempiere.webservices/OSGI-INF/org.idempiere.webservices.model.WS_ModelFactory.xml
Fix duplicate component definition file for ws modelfactory
=> IDEMPIERE-5050 Service startup freeze

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/PrintFormatElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5058
=> IDEMPIERE-5058 Pack In from a tenant print format just packed out throws cross tenant error because of Print Paper

org.adempiere.base/src/org/compiere/model/MInfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5006
=> IDEMPIERE-5006 [Info Window] - MInfoProcess & MInfoRelated cached incorrectly

migration/i8.2z/oracle/202111301716_IDEMPIERE-5052.sql, migration/i8.2z/postgresql/202111301716_IDEMPIERE-5052.sql, org.adempiere.base/src/org/compiere/model/POInfo.java, org.adempiere.base/src/org/compiere/model/POInfoColumn.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5052
test case described in ticket
=> IDEMPIERE-5052 Date Min/Max Validation wrong with 5 digit years

migration/i8.2/oracle/202111302130_IDEMPIERE-1302.sql, migration/i8.2/postgresql/202111302130_IDEMPIERE-1302.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-1302
Implemented as adding IsSold/IsPurchased in Product Info window with the same management as IsCustomer/IsVendor on BP Info window
=> IDEMPIERE-1302 Validate flag IsPurchased and IsSold on Price List, Order, InOut, and Invoice

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5064
https://idempiere.atlassian.net/browse/IDEMPIERE-4472
Window Advanced Search - Allow select column from window tabs - 2pack compatibility
Fixes for find dialog in report
=> IDEMPIERE-5064 Lookup Record Dialog on Reports is unusable / IDEMPIERE-4472

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/LayoutUtils.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5068
=> IDEMPIERE-5068 Improvement to report viewer find dialog

org.adempiere.base/src/org/compiere/model/MBankStatement.java, org.adempiere.base/src/org/compiere/model/MCash.java, org.adempiere.base/src/org/compiere/model/MCashPlan.java, org.adempiere.base/src/org/compiere/model/MCommission.java, org.adempiere.base/src/org/compiere/model/MDepositBatch.java, org.adempiere.base/src/org/compiere/model/MDiscountSchema.java, org.adempiere.base/src/org/compiere/model/MDistribution.java, org.adempiere.base/src/org/compiere/model/MDistributionRun.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MInventory.java, org.adempiere.base/src/org/compiere/model/MJournal.java, org.adempiere.base/src/org/compiere/model/MMovement.java, org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/model/MProduction.java, org.adempiere.base/src/org/compiere/model/MProductionPlan.java, org.adempiere.base/src/org/compiere/model/MProject.java, org.adempiere.base/src/org/compiere/model/MProjectPhase.java, org.adempiere.base/src/org/compiere/model/MProjectTask.java, org.adempiere.base/src/org/compiere/model/MRMA.java, org.adempiere.base/src/org/compiere/model/MRequisition.java, org.adempiere.base/src/org/compiere/model/MRfQ.java, org.adempiere.base/src/org/compiere/model/MTimeExpense.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5061
=> IDEMPIERE-5061 Inconsistency in getLines Order By code

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4428
=> IDEMPIERE-4428 Wrong report parameters from window search

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/LoginWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5072
=> IDEMPIERE-5072 Blocking - Change Rol / IDEMPIERE-4782

org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MInvoice.java, org.adempiere.base/src/org/compiere/model/MPayment.java, org.adempiere.base/src/org/compiere/process/DocumentEngine.java, org.adempiere.base/src/org/compiere/process/IDocsPostProcess.java, org.idempiere.test/src/org/idempiere/test/model/InvoiceCustomerTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5081
=> IDEMPIERE-5081 add IDocsPostProcess interface

org.adempiere.base/src/org/compiere/wf/MWFNodeNext.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WFEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WFPopupItem.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5079
=> IDEMPIERE-5079 Improvements for Workflow Editor

org.adempiere.base/src/org/compiere/process/SvrProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5080
=> IDEMPIERE-5080 Dup key inserting in AD_PInstance_Log on certain workflows

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ProcessButtonPopup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WDocActionPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5077
=> IDEMPIERE-5077 Process (gear) button unusable when the workflow is suspended

org.adempiere.base/src/org/compiere/print/DataEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4871
=> IDEMPIERE-4871 Print Format Item Script Data Type Support (fix backward compatibility issue)

org.adempiere.base/src/org/compiere/model/MAttributeSet.java, org.adempiere.base/src/org/compiere/model/MAttributeUse.java, org.idempiere.test/src/org/idempiere/test/model/MAttributeSetTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5095
=> IDEMPIERE-5095 MAttributeSet: add getMAttributeUse method

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/FavouriteController.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3340?focusedCommentId=47780
fix Cross-tenant issue
=> IDEMPIERE-3340 Adaxa's User Favorite which allow user to organize their menu, create folders

org.adempiere.base/src/org/compiere/model/MCost.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5098
=> IDEMPIERE-5098 MCost.get: new MCost created without trxName

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPaySelect.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5092
=> IDEMPIERE-5092 Improvement to Payment Selection Manual form

org.adempiere.base/src/org/compiere/wf/MWFProcess.java, org.adempiere.base/src/org/compiere/wf/MWorkflow.java, org.adempiere.server/src/main/server/org/compiere/server/WorkflowProcessor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java, org.idempiere.test/src/org/idempiere/test/workflow/WFMaterialReceiptTest.java
fix Split Join = AND
https://idempiere.atlassian.net/browse/IDEMPIERE-4186
=> IDEMPIERE-4186 allow workflow to be suspended until after commit of actual  transaction

org.adempiere.base/src/org/compiere/model/MInvoiceLine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5099
=> IDEMPIERE-5099 Invoice Tax zero deleted wrongly when invoice line is updated before complete

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5074
=> IDEMPIERE-5074 Alt+Left Alt+Right not working when focus is lost

migration/i8.2z/oracle/202112161318_IDEMPIERE-4448.sql, migration/i8.2z/postgresql/202112161318_IDEMPIERE-4448.sql, org.adempiere.base/src/org/compiere/model/MLookupFactory.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4448
* Change 188 reftables to use the ID for display - this displays the reference based on the identifiers of the table, making it consistent with Search/Table without reference
* Use the MSysConfig.IDENTIFIER_SEPARATOR for the cases where reference is displaying value and another column
=> IDEMPIERE-4448 Autocomplete/Info Window doesn't work correctly with Search fields with Reference

org.adempiere.base/src/org/compiere/model/MLookup.java, org.adempiere.base/src/org/compiere/util/Env.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5104
=> IDEMPIERE-5104 MLookup: Inconsistent use of TabNo

org.adempiere.base/src/org/compiere/model/MTax.java, org.idempiere.test/src/org/idempiere/test/model/MTaxTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5103
=> IDEMPIERE-5103 Clear Parent Tax ID if a Tax Rate record is Summary

org.adempiere.base/src/org/compiere/model/MDocumentStatus.java, org.adempiere.base/src/org/compiere/model/MDocumentStatusAccess.java, org.idempiere.test/src/org/idempiere/test/base/DocumentStatusTest.java
peer review - fix multi-tenant issue
=> IDEMPIERE-4836 Adding Access tab on Document Status (Activity)

migration/i8.2z/oracle/202112181406_IDEMPIERE-5109_GWPeriods2022.sql, migration/i8.2z/postgresql/202112181406_IDEMPIERE-5109_GWPeriods2022.sql, org.adempiere.ui.zk/WEB-INF/src/web/js/jawwa/atmosphere/serverpush.js
fixes broken unit test InvoiceCustomerTest.testOpenAmt
https://idempiere.atlassian.net/browse/IDEMPIERE-5109
=> IDEMPIERE-5109 Release 9 Horizon / add year 2022 in GardenWorld

org.adempiere.base.process/src/org/compiere/process/PeriodStatus.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2901?focusedCommentId=47804
=> IDEMPIERE-2901 Period Control Management / improve cache management

org.adempiere.base/src/org/compiere/print/DataEngine.java
- have tested with several example scripts and all appears to be working well
=> IDEMPIERE-5111 Data type improvements to Print Format Item Script

org.adempiere.base/src/org/compiere/print/DataEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4709
=> IDEMPIERE-5112 NF8.2 Print Format Item Script not working on Oracle

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/CommonTranslationHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ImpFormatElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/MenuElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/PrintFormatElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/ReportViewElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/RoleElementHandler.java, org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/TabElementHandler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/action/ExportAction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5107
improve showing error messages
=> IDEMPIERE-5107 Can't 2pack zip for Window Role

migration/processes_post_migration/oracle/04_role_access_update.sql, migration/processes_post_migration/postgresql/04_role_access_update.sql, org.adempiere.base/src/org/compiere/model/MDocType.java, org.adempiere.base/src/org/compiere/model/MDocumentActionAccess.java, org.adempiere.base/src/org/compiere/model/MLanguage.java, org.adempiere.base/src/org/compiere/model/MPInstanceLog.java, org.adempiere.base/src/org/compiere/model/MRole.java
fix role access uuids
https://idempiere.atlassian.net/browse/IDEMPIERE-4262
=> IDEMPIERE-4262 on some condition, record insert by direct sql missing UUID

org.adempiere.pipo/src/org/adempiere/pipo2/PoExporter.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3476
=> IDEMPIERE-3476 2Pack: attribute set install is not reference by UUID

org.adempiere.base.process/src/org/compiere/process/InventoryCountCreate.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5115
=> IDEMPIERE-5115 Create Inventory Count List - Inventory Quantity = 0 - broken

migration/i8.2z/oracle/202112210930_IDEMPIERE-5110.sql, migration/i8.2z/postgresql/202112210930_IDEMPIERE-5110.sql
Added indexes for BOM. Rewritten virtual columns for m_productionline.
=> IDEMPIERE-5110 Manufacturing performance enhancements

org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/MInventory.java, org.adempiere.base/src/org/compiere/model/MMovement.java, org.adempiere.base/src/org/compiere/model/MProjectIssue.java, org.adempiere.base/src/org/compiere/model/MStorageOnHand.java, org.adempiere.base/src/org/eevolution/model/MDDOrder.java, org.idempiere.test/src/org/idempiere/test/model/MStorageOnHandTest.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5121
=> IDEMPIERE-5121 MStorageOnHand API enhancements

migration/i8.2z/oracle/202112210900_IDEMPIERE-5118.sql, migration/i8.2z/postgresql/202112210900_IDEMPIERE-5118.sql, org.adempiere.base/src/org/compiere/model/CalloutEngine.java, org.adempiere.base/src/org/compiere/model/MUOMConversion.java, org.idempiere.test/src/org/idempiere/test/model/MUOMConversionTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5118
=> IDEMPIERE-5118 MUOMConversion fix and improvements

migration/i8.2z/oracle/202107272210_IDEMPIERE-4882.sql, migration/i8.2z/postgresql/202107272210_IDEMPIERE-4882.sql, org.adempiere.base.callout/src/org/compiere/model/CalloutMovement.java, org.adempiere.base/src/org/compiere/model/I_M_Movement.java, org.adempiere.base/src/org/compiere/model/X_M_Movement.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocatorEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4882
=> IDEMPIERE-4882 On Inventory Move, Adding Warehouse and Warehouse To field on header

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/util/UserPreference.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5125
=> IDEMPIERE-5125 Opening/Close right panel cause DB Error

org.adempiere.base/src/org/compiere/model/MProduct.java, org.idempiere.test/src/org/idempiere/test/model/MProductTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5127
=> IDEMPIERE-5127 MProduct: add IsSerial method

org.adempiere.base/src/org/compiere/wf/MWFActivity.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5130
=> IDEMPIERE-5130 Set process summary as workflow activity message

org.adempiere.base/src/org/compiere/model/MYear.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4652
=> IDEMPIERE-4652 Remove Eclipse warnings

org.adempiere.base.process/src/org/idempiere/process/ChangeBaseLanguage.java, org.adempiere.base/src/org/compiere/install/Translation.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5131
=> IDEMPIERE-5131 Base language cannot be changed by process 'change base language'

migration/i9/oracle/202112291927_IDEMPIERE-5132.sql, migration/i9/postgresql/202112291927_IDEMPIERE-5132.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WCreateFromShipmentUI.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5132?focusedCommentId=47844
=> IDEMPIERE-5132 Enable filling Purchase Order in Material Receipt

org.adempiere.base/src/org/compiere/model/MOrg.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5133
=> IDEMPIERE-5133 Organization Window & Tab newly created records does not show on idempiere but its created in the database

org.adempiere.base/src/org/compiere/model/MProduct.java, org.idempiere.test/src/org/idempiere/test/model/MProductTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5134
=> IDEMPIERE-5134 Clean up storage records after deactivation of product

org.adempiere.server-feature/utils.unix/unix/DebianInstaller/etc/init.d/idempiere
improve message in the Debian installer
https://idempiere.atlassian.net/browse/IDEMPIERE-5137
=> IDEMPIERE-5137 Login page reload continuously using http

migration/i9/oracle/202201040800_IDEMPIERE-5139.sql, migration/i9/postgresql/202201040800_IDEMPIERE-5139.sql, org.adempiere.base/src/org/compiere/model/MProduct.java, org.idempiere.test/src/org/idempiere/test/model/MProductTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5139
=> IDEMPIERE-5139 BOM validation for Deactivation of Product

org.adempiere.base/src/org/compiere/model/MMatchInv.java, org.idempiere.test/src/org/idempiere/test/base/MatchInvTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5145
=> IDEMPIERE-5145 MMatchInv: add IsReversal method

org.adempiere.base.process/src/org/compiere/process/StorageCleanup.java, org.idempiere.test/src/org/idempiere/test/model/MStorageOnHandTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5138
=> IDEMPIERE-5138 Storage Cleanup Fixes

org.adempiere.base/src/org/compiere/model/MProduction.java, org.adempiere.base/src/org/compiere/model/MProductionLine.java, org.adempiere.base/src/org/compiere/model/MProductionPlan.java, org.idempiere.test/src/org/idempiere/test/model/ProductionTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4849
=> IDEMPIERE-4849 Nonsensical code in MProduction.createLines()

org.adempiere.base/src/org/compiere/process/SvrProcess.java
Fix assignment of boolean parameters.
=> IDEMPIERE-5025 Easier usage of process parameters

org.adempiere.base/src/org/compiere/install/Translation.java, org.adempiere.base/src/org/compiere/install/TranslationHandler.java, org.adempiere.base/src/org/idempiere/process/TranslationImpExp.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5149
=> IDEMPIERE-5149 Database lock in Translation Import/Export

org.adempiere.pipo.handlers/src/org/adempiere/pipo2/handler/GenericPOElementHandler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5148
=> IDEMPIERE-5148 PackOut DataSingle for Column doesn't create the column in the target database

org.adempiere.base/src/org/compiere/acct/Doc_Production.java, org.idempiere.test/src/org/idempiere/test/model/ProductionTest.java
- plus multiple improvements to production unit tests
Jira issue https://idempiere.atlassian.net/browse/IDEMPIERE-5159
=> IDEMPIERE-5159 Remove hard coded rounding in Doc_Production

org.compiere.db.postgresql.provider/src/org/compiere/dbPort/Convert_PostgreSQL.java, org.idempiere.test/src/org/idempiere/test/base/Convert_PostgreSQLTest.java
reverts partially f4894c4cb
https://idempiere.atlassian.net/browse/IDEMPIERE-4962
https://idempiere.atlassian.net/browse/IDEMPIERE-4465
Regression for problem solved at IDEMPIERE-4465 Native Postgres - Error on Convert Layer
Revert the changes on Convert_PostgreSQL and Convert_PostgreSQLTest
Fix the Convert_PostgreSQLTest to allow testing native and non-native cases
=> IDEMPIERE-4962 Performance: change PostgreSQL native dialect mode default to true

org.idempiere.test/src/org/idempiere/test/base/MatchInvTest.java, org.idempiere.test/src/org/idempiere/test/model/MProductTest.java
- Add MatchInv test using standard costing and check Invoice Price Variance 
- General improvements using assertEquals where appropriate and
comparing actual values rather than just >0
- minor fixes to MProduct test
=> IDEMPIERE-5063 Improve Unit Tests - MatchInv Tests

org.adempiere.base/src/org/compiere/acct/Doc_Invoice.java
Refer: https://idempiere.atlassian.net/browse/IDEMPIERE-5165
=> IDEMPIERE-5165 Remove references to deprecated services accounts

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4931
=> IDEMPIERE-4931 Running jobs never stop

org.adempiere.base/src/org/compiere/model/GridTable.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5171
Mattermost Discussion: https://mattermost.idempiere.org/idempiere/pl/encj8awdzbgt5jtf8y4hfxz1ay
=> IDEMPIERE-5171 GridTable duplicate WhereClause Fix

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5156
=> IDEMPIERE-5156 Editing a multi-line field in grid destroys the new line separator

org.adempiere.base/src/org/compiere/acct/Doc_MatchInv.java, org.adempiere.base/src/org/compiere/acct/FactLine.java, org.adempiere.base/src/org/compiere/model/MMatchInv.java, org.idempiere.test/src/org/idempiere/test/base/MatchInvTest.java
- also add unit tests
https://idempiere.atlassian.net/browse/IDEMPIERE-5173
=> IDEMPIERE-5173 fix Accounting fact quantity incorrect

migration/i9/oracle/202202061544_IDEMPIERE-4297.sql, migration/i9/postgresql/202202061544_IDEMPIERE-4297.sql
Coming from @cboecking review here:
https://mattermost.idempiere.org/idempiere/pl/y9rkthgmrjnt7npiai3dhukf4e
=> IDEMPIERE-4297 Improve test data / fix some wrong data in GardenWorld seed

org.idempiere.test/idempiere.unit.test.launch
https://idempiere.atlassian.net/browse/IDEMPIERE-5183
=> IDEMPIERE-5183 Update JUnit Test Coverage Configuration

migration/i9/oracle/202202072001_IDEMPIERE-4297.sql, migration/i9/postgresql/202202072001_IDEMPIERE-4297.sql
- Intercompany GL Journal Line has wrong Org
- Replace old ADempiere images & URL's with iDempiere
=> IDEMPIERE-4297 Improve test data / fixes for Garden World data

migration/iD10/oracle/202202072157_IDEMPIERE-5174.sql, migration/iD10/postgresql/202202072157_IDEMPIERE-5174.sql, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/zul/login/login-info.zul
https://idempiere.atlassian.net/browse/IDEMPIERE-5174
- change approach to replace System user instead of removing it
=> IDEMPIERE-5174 Disable System User

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/BreadCrumb.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/BusyDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/AutoComplete.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ConfirmPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/FolderBrowser.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/WAppsAction.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/factory/ButtonFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/theme/ThemeManager.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/adwindow.css.dsp, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/font-icons.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4561?focusedCommentId=48007
=> IDEMPIERE-4561 Font Icons not used in several points #3

org.adempiere.server-feature/utils.unix/unix/DebianInstaller/DEBIAN/control
https://idempiere.atlassian.net/browse/IDEMPIERE-5187
=> IDEMPIERE-5187 PostgreSQL 9.6 EOL

org.adempiere.base/src/org/compiere/model/MDocumentStatus.java, org.idempiere.test/src/org/idempiere/test/base/DocumentStatusTest.java
Fix wrong comparison changed in commit a9c4f7b - test case failing
Improve traceability of unit test
=> IDEMPIERE-5174 Disable System User (#1174)

org.adempiere.base/src/org/compiere/print/layout/HTMLElement.java, org.adempiere.base/src/org/compiere/print/layout/HTMLRenderer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4893
- Fix NPE trying to print any HTML content in PDF as form using internal engine
- Fix problem printing HTML content as plain text
=> IDEMPIERE-4893 NPE on PDF report of Test record

org.adempiere.base/src/org/compiere/dbPort/Convert.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5190
=> IDEMPIERE-5190 Improve migration script generator

migration/i9/oracle/202202151738_IDEMPIERE-2580.sql, migration/i9/postgresql/202202151738_IDEMPIERE-2580.sql, org.adempiere.base/src/org/compiere/model/MTax.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2580
=> IDEMPIERE-2580 Error with taxes and country groups

org.adempiere.base/src/org/adempiere/model/GenericZoomProvider.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5192
=> IDEMPIERE-5192 Expand Detailed Zoom Across button to more references

migration/i9/oracle/202202151115_IDEMPIERE-4297.sql, migration/i9/postgresql/202202151115_IDEMPIERE-4297.sql
- Fix missing account combinations and doctype in payment allocations
- Fix Tree Farm Vendor Liabilty posted to different account in euro schema
- Add equivalent Intercompany Journal to euro schema
I have placed the migration scripts in the i9 folder, if this is not correct I can move to iD10.
=> IDEMPIERE-4297 Fix GW accounting issues

org.adempiere.base.process/src/org/compiere/process/InventoryValue.java, org.adempiere.base/src/org/compiere/impexp/ImpFormat.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
IDEMPIERE-4962 IDEMPIERE-4724
https://idempiere.atlassian.net/browse/IDEMPIERE-5191
=> IDEMPIERE-5191 SEARCH FAILURE BY DATE AND HOUR

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
- Fix issue reported in IDEMPIERE-5195 saving wrongly Yes/No values as true/false
- Fix also wrong recover of timestamps just as dates (ignoring the time part)
- Fix also IDEMPIERE-4568 reopened, adding wrongly operators
https://idempiere.atlassian.net/browse/IDEMPIERE-5195
=> IDEMPIERE-5195 SEARCH FAILURE FOR SAVED QUERIES + IDEMPIERE-4658 #resolve

org.compiere.db.postgresql.provider/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-5196
=> IDEMPIERE-5196 PostgreSQL JDBC 42.3.3

org.adempiere.base/src/org/compiere/model/GridTable.java
Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5193
Added Limit on SQL Statement  additional to PreparedStatement setMaxRows() for better performance on Database Servers
=> IDEMPIERE-5193 GridTable MaxQueryRecords Limit - Performance

org.adempiere.ui/src/org/compiere/apps/IStatusBar.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5201
=> IDEMPIERE-5201 IStatusBar: Missing license header and javadoc

org.adempiere.base/src/org/compiere/model/MInOutLine.java
issue: when m_inout created programmatically locator is not set properly (atm works as callout)
clodempiere provide PR soon.
=> IDEMPIERE-5091 - Before Save Set Default Locator From Product Or Warehouse when creating m_inout programatically

org.adempiere.base/src/org/compiere/model/MRefList.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5204
Mattermost Topic: https://mattermost.idempiere.org/idempiere/pl/wh3fooer7b8ityc43edopuxmta
=> IDEMPIERE-5204 Cache the list/array of mreflist for AD_Reference_ID

org.adempiere.base/src/org/compiere/print/MPrintFormat.java, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5198
=> IDEMPIERE-5198 Print Format Cache do not reload Print Format Items

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WCtxHelpSuggestion.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5205
=> IDEMPIERE-5205 PO is Immutable: org.compiere.model.MCtxHelpMsg

migration/i9/oracle/202202241712_IDEMPIERE-4706.sql, migration/i9/postgresql/202202241712_IDEMPIERE-4706.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4706
=> IDEMPIERE-4706 New field "Dynamic Validation (Lookup)" in AD_Column>AD_Val_Rule_Lookup_ID not working

org.adempiere.base/src/org/compiere/process/MFAUnregister.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5212
=> IDEMPIERE-5212 Cross tenant PO writing in MFAUnregister

org.adempiere.base/src/org/compiere/model/DataStatusEvent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java
- Fix auto save sometimes not happening for string field update
https://idempiere.atlassian.net/browse/IDEMPIERE-5202
=> IDEMPIERE-5202 Implement auto save of current tab

migration/iD10/oracle/202203022014_IDEMPIERE-5213.sql, migration/iD10/postgresql/202203022014_IDEMPIERE-5213.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/MenuSearchController.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/AbstractMenuPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/MenuTreeFilterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/MenuTreePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/MenuTreeSearchPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/TreeSearchPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5213
=> IDEMPIERE-5213 Flat view improvement for menu tree

org.adempiere.base/src/org/compiere/print/ReportEngine.java
Jira issue: https://idempiere.atlassian.net/browse/IDEMPIERE-5216
=> IDEMPIERE-5216 - HTML Report - replace Record_ID with Identifier column

migration/i9/oracle/202203072105_IDEMPIERE-5222.sql, migration/i9/postgresql/202203072105_IDEMPIERE-5222.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkJRViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5222
=> IDEMPIERE-5222 Add Attach button to report viewer (similar to Archive but with Attachment)

org.adempiere.base/src/org/compiere/util/MimeType.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5223
=> IDEMPIERE-5223 Allow attachment preview for xml and json

migration/i9/oracle/202203031336_IDEMPIERE-4297.sql, migration/i9/postgresql/202203031336_IDEMPIERE-4297.sql
- Fix missing data in customer rma line (preventing completion of document) 
- Minor fixes to Order, Shipment & Invoice print formats (fit on one page)
(resubmit - pushed incorrect files in previous commit)
Just a few minor fixes for GW data. The Customer RMA has doc status In Progress, but could not be completed due to missing amount data in rma line. Also reduced font size on order, shipment & invoice print formats, so they are more likely to fit on one page accross. Plus other minor tidy ups.
=> IDEMIERE-4297 Improve test data

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WRecordInfo.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5218?focusedCommentId=48106
=> IDEMPIERE-5218 Add notification for visual feedback

migration/iD10/oracle/202203081457_IDEMPIERE-4586.sql, migration/iD10/postgresql/202203081457_IDEMPIERE-4586.sql, org.adempiere.base.process/src/org/compiere/process/AssetDelivery.java, org.adempiere.base.process/src/org/idempiere/process/MigrateStorageProvider.java, org.adempiere.base/src/org/adempiere/process/SalesOrderRateInquiryProcess.java, org.adempiere.base/src/org/compiere/model/MOrder.java, org.adempiere.base/src/org/compiere/model/MSetup.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/ModelValidationEngine.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.base/src/org/idempiere/process/MoveClient.java, org.adempiere.pipo/src/org/adempiere/pipo2/POFinder.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java, org.adempiere.replication/src/org/adempiere/model/ExportModelValidator.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/AbstractService.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4586
=> IDEMPIERE-4586 Update translation of Client to Tenant

org.adempiere.base/src/org/adempiere/base/DefaultLookupFactory.java, org.adempiere.base/src/org/compiere/model/MLocatorLookup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WCreateFromShipmentUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WTrxMaterial.java
- Replace M_Locator.get with MLocator ResultSet constructor
- Implement lazy loading for MLocatorLookup
=> IDEMPIERE-5224 Locator Field type Caching Improvement

org.adempiere.base.process/src/org/compiere/process/BankStatementPayment.java, org.adempiere.base/src/org/compiere/model/MInvoice.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5231
=> IDEMPIERE-5231 Create Payments from Bank Statement is not taking into account Discounts

migration/iD10/oracle/202203161513_IDEMPIERE-5225.sql, migration/iD10/postgresql/202203161513_IDEMPIERE-5225.sql, org.adempiere.base/META-INF/MANIFEST.MF, org.adempiere.base/build.properties, org.adempiere.base/pom.xml, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java
Jira ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5225
Using com.googlecode.htmlcompressor.compressor.HtmlCompressor
=> IDEMPIERE-5225 - HTML Report minification

migration/i9/oracle/202203170900_IDEMPIERE-5089.sql, migration/i9/postgresql/202203170900_IDEMPIERE-5089.sql, org.adempiere.base/src/org/compiere/model/MPayment.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.base/src/org/compiere/wf/MWFProcess.java, org.adempiere.base/src/org/compiere/wf/MWorkflow.java, org.idempiere.test/src/org/idempiere/test/model/BankStatementTest.java, org.idempiere.test/src/org/idempiere/test/model/MProductTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5089
=> IDEMPIERE-5089 Add MSysConfig.ALLOW_REVERSAL_OF_RECONCILED_PAYMENT

migration/i9/oracle/202203161342_IDEMPIERE-5221.sql, migration/i9/postgresql/202203161342_IDEMPIERE-5221.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5221
=> IDEMPIERE-5221 Performance - indexes on heavily used queries / FHCA-3486

org.adempiere.server-feature/utils.unix/oracle/AfterImport.sql, org.adempiere.server-feature/utils.windows/oracle/AfterImport.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5228
=> IDEMPIERE-5228 Too verbose oracle/AfterImport.sql

migration/iD10/oracle/202203211620_IDEMPIERE-5083.sql, migration/iD10/postgresql/202203211620_IDEMPIERE-5083.sql, org.adempiere.base.callout/src/org/adempiere/base/callout/InOutFreightCostRule.java, org.adempiere.base/src/org/adempiere/util/ShippingUtil.java, org.adempiere.base/src/org/compiere/model/I_C_BPartner.java, org.adempiere.base/src/org/compiere/model/I_C_Order.java, org.adempiere.base/src/org/compiere/model/I_M_InOut.java, org.adempiere.base/src/org/compiere/model/I_M_Movement.java, org.adempiere.base/src/org/compiere/model/I_RV_BPartner.java, org.adempiere.base/src/org/compiere/model/MInOut.java, org.adempiere.base/src/org/compiere/model/X_C_BPartner.java, org.adempiere.base/src/org/compiere/model/X_C_Order.java, org.adempiere.base/src/org/compiere/model/X_M_InOut.java, org.adempiere.base/src/org/compiere/model/X_M_Movement.java, org.adempiere.base/src/org/compiere/model/X_RV_BPartner.java, org.idempiere.test/src/org/idempiere/test/base/InOutTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5083
=> IDEMPIERE-5083 add FREIGHTCOSTRULE_CustomerAccount

migration/iD10/oracle/202203171454_IDEMPIERE-5056.sql, migration/iD10/postgresql/202203171454_IDEMPIERE-5056.sql, org.adempiere.base.callout/src/org/adempiere/model/CalloutRMA.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInvoice.java, org.adempiere.base.callout/src/org/compiere/model/CalloutInvoiceBatch.java, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base/OSGI-INF/org.adempiere.base.DefaultTaxLookup.xml, org.adempiere.base/src/org/adempiere/base/Core.java, org.adempiere.base/src/org/adempiere/base/DefaultTaxLookup.java, org.adempiere.base/src/org/adempiere/base/ITaxLookup.java, org.adempiere.base/src/org/compiere/model/MInvoiceLine.java, org.adempiere.base/src/org/compiere/model/MOrderLine.java, org.adempiere.base/src/org/compiere/model/MRMALine.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/Tax.java, org.idempiere.test/src/org/idempiere/test/model/MTaxTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5056
=> IDEMPIERE-5056 Order and Invoice: Tax lookup interface

migration/i9/oracle/202203260025_IDEMPIERE-3219.sql, migration/i9/postgresql/202203260025_IDEMPIERE-3219.sql, org.adempiere.base.process/src/org/compiere/process/FactAcctReset.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3219
=> IDEMPIERE-3219 Reset Accounting can't reset documents without fact acct

migration/i9/oracle/202203250046_IDEMPIERE-4669.sql, migration/i9/postgresql/202203250046_IDEMPIERE-4669.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-4669
=> IDEMPIERE-4669 Adding RfQ responses manually is prohibited, because the field for the RfQ is read only

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5249
=> IDEMPIERE-5249 product info window doesn't show list and standard price if pricelist selected when starting.

org.adempiere.base/src/org/compiere/print/DataEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5253
=> Implement @LINE@ script in print format item

org.adempiere.base/src/org/compiere/print/DataEngine.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5248
=> IDEMPIERE-5248 - Report View reference: list doesn't work

org.adempiere.base/src/org/compiere/model/MRole.java, org.adempiere.base/src/org/compiere/print/MPrintFormat.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5258
=> IDEMPIERE-5258 Importing a print format in the same packin as the table throws errors

org.adempiere.base/src/org/adempiere/util/AbstractDocumentSearch.java, org.adempiere.base/src/org/compiere/model/MLookupFactory.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/DocumentSearchController.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5266
Implementing changes from @igorpojzl XREF CLDE#314
=> IDEMPIERE-5266 - AD_Column Caching changes

org.adempiere.base/src/org/compiere/print/DataEngine.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5255
=> IDEMPIERE-5255 - Print format Script Column SQL parse broken by space

org.adempiere.base/src/org/compiere/model/MDocumentStatus.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java
Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5268
=> IDEMPIERE-5268  Cache PA_DocumentStatus

org.adempiere.base/src/org/compiere/model/MTable.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5254
=> IDEMPIERE-5254 - AD create postgres sequences and ad_sequence for views

org.adempiere.base/src/org/compiere/model/MSession.java, org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/process/ProcessInfo.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/AdempiereActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/Incremental2PackActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/PackInApplicationActivator.java, org.adempiere.plugin.utils/src/org/adempiere/plugin/utils/Version2PackActivator.java, org.adempiere.server/src/main/server/org/compiere/server/AdempiereServerMgr.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/session/SessionContextListener.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/CompiereService.java
Previous PR: https://github.com/idempiere/idempiere/pull/1282
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5256
=> IDEMPIERE-5256 Refactor

org.adempiere.base.callout/src/org/compiere/model/CalloutInOut.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5132
=> IDEMPIERE-5132 Enable filling Purchase Order in Material Receipt - fix issue with drop ship

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5269
=> IDEMPIERE-5269 Allow save a record in a read only search field

org.adempiere.base/src/org/compiere/model/Query.java, org.idempiere.p2.targetplatform/maven.locations.xml, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target, org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd, org.idempiere.test/META-INF/MANIFEST.MF, org.idempiere.test/idempiere.unit.test.launch, org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5014
Carlos requested a proof-of-concept - this is it.
=> IDEMPIERE-5014 Add stream interface to Query

org.adempiere.base/src/org/compiere/model/PO.java, org.adempiere.base/src/org/compiere/util/CacheMgt.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5279
https://mattermost.idempiere.org/idempiere/pl/89kadc1skidwxbe5khdafrtzmh
=> IDEMPIERE-5279 Improve PO to avoid calling cache reset unnecessarily

migration/iD10/oracle/202205031611_IDEMPIERE-5245.sql, migration/iD10/postgresql/202205031611_IDEMPIERE-5245.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5245
table: AD_Element
[req5245_ad_element.ods](https://github.com/idempiere/idempiere/files/8612150/req5245_ad_element.ods)
5
=> IDEMPIERE-5245 Fix typos in dictionary #resolve

migration/iD10/oracle/202204190945_IDEMPIERE-5261.sql, migration/iD10/postgresql/202204190945_IDEMPIERE-5261.sql, org.adempiere.base/src/org/compiere/model/I_AD_WF_Node.java, org.adempiere.base/src/org/compiere/model/MMailText.java, org.adempiere.base/src/org/compiere/model/X_AD_WF_Node.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.idempiere.test/src/org/idempiere/test/base/EnvTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5261
=> IDEMPIERE-5261 Workflow EMail notification enhancement

org.idempiere.test/src/org/idempiere/test/AbstractTestCase.java
- revert -> Close DB connections after each unit test class
- implement a different approach to close the transactions on tearDown even when not active
https://idempiere.atlassian.net/browse/IDEMPIERE-5063
=> IDEMPIERE-5063 Improve Unit Tests

migration/i9/oracle/202205101725_IDEMPIERE-5288.sql, migration/i9/postgresql/202205101725_IDEMPIERE-5288.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java, org.idempiere.keikai/src/org/idempiere/keikai/view/ExcelMediaView.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5288
=> IDEMPIERE-5288 org.zkoss.poi.POIXMLException attaching XLSX file

org.adempiere.base/src/org/compiere/util/CCache.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5267
=> IDEMPIERE-5267 Make Cache Max Size configurable via system property

migration/i9/oracle/202205121340_IDEMPIERE-5287.sql, migration/i9/postgresql/202205121340_IDEMPIERE-5287.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5287
=> IDEMPIERE-5287 Minor issue in 'sql where' from Window 'User Preference' (impact Report function) - thanks to Ken Longnan

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WCtxHelpSuggestion.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5205?focusedCommentId=48287
=> IDEMPIERE-5205 PO is Immutable #resolve

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-3294?jql=text%20~%20%22Process%20Audit%20generate%20unused%20AD_PInstance_Para%22
=> IDEMPIERE-3294 - Process Audit generate unused AD_PInstance_Para

migration/iD10/oracle/202203290700_IDEMPIERE-5057.sql
fix oracle script
https://idempiere.atlassian.net/browse/IDEMPIERE-5057
=> IDEMPIERE-5057 Implement Deductible and non deductible input tax for purchasing and costing

org.adempiere.pipo/src/org/adempiere/pipo2/PackInNotifier.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5289
=> IDEMPIERE-5289 Apply Packin from Folder is stopping when sending email throws error (FHCA-3601)

org.adempiere.base.process/src/org/compiere/process/ImportInvoice.java, org.adempiere.base.process/src/org/compiere/process/ImportOrder.java
[IDEMPIERE-5292 #resolve](https://idempiere.atlassian.net/browse/IDEMPIERE-5292?
=> IDEMPIERE-5292 Function dump not replaced for postgres

org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.base/src/org/compiere/model/MProcess.java, org.adempiere.base/src/org/compiere/report/FinReportJasper.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/Process.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-3294
We also found new use cases which should be fixed, and those are when process is starting from Scheduler, Workflow, Dashboard or Web Service
=> IDEMPIERE-3294 - check empty String parameter

org.adempiere.base/src/org/compiere/wf/MWFActivity.java
- Fix unit test error for RequisitionTest.testComplete()
=> IDEMPIERE-3294 Process Audit generate unused AD_PInstance_Para

org.adempiere.base/src/org/compiere/print/MPrintFormat.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5286
note: I use different approach from the ticket author's suggestion.
=> IDEMPIERE-5286 Fix ConcurrentModificationException in MPrintFormat.getAllItems Method

migration/iD10/oracle/202205261621_IDEMPIERE-5304.sql, migration/iD10/postgresql/202205261621_IDEMPIERE-5304.sql, org.adempiere.base/src/org/compiere/model/MPayment.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5304
=> IDEMPIERE-5304 - Missing Message from Payment

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADTabpanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4661
=> IDEMPIERE-4661 Fix Password fields show double context "Field Suggestions"

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WEMailDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WTextEditorDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4739?focusedCommentId=48341
=> IDEMPIERE-4739 Fix Height of HTML Text Editor not responsive

org.adempiere.base/src/org/compiere/print/ServerReportCtl.java, org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui/src/org/compiere/apps/AbstractProcessCtl.java, org.adempiere.ui/src/org/compiere/print/ReportCtl.java, org.idempiere.webservices/WEB-INF/src/org/idempiere/adinterface/Process.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4523
=> IDEMPIERE-4523 - Process Audit not mark AD_PInstance.IsProcessing on simple Reports

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/AttachmentItem.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/input-element.css.dsp
https://idempiere.atlassian.net/browse/IDEMPIERE-4740?focusedCommentId=48361
=> IDEMPIERE-4740 Fix EMail panel : Attachment is cut at bottom

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPostIt.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4543
=> IDEMPIERE-4543 Fix Post-it doesn't save/update from HTML tab

org.adempiere.base/src/org/compiere/print/DataEngine.java, org.adempiere.base/src/org/compiere/print/PrintDataElement.java, org.adempiere.base/src/org/compiere/print/PrintDataFunction.java, org.adempiere.base/src/org/compiere/print/PrintDataGroup.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5307
=> IDEMPIERE-5307 - Report Summary Functions Not Working Properly

migration/iD10/oracle/202205192100_IDEMPIERE-5245.sql, migration/iD10/postgresql/202205031611_IDEMPIERE-5245.sql, migration/iD10/postgresql/202205192100_IDEMPIERE-5245.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5245-ad_message
=> IDEMPIERE-5245-ad_message Fix typos in dictionary #resolve

org.adempiere.base/src/org/compiere/wf/MWFActivity.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPActivities.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/DPActivitiesModel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5315
- Found that DPActivities is deprecated, so deprecated too the DPActivitiesModel
- Also found that DefaultDesktop had a dependency to show the total of DPActivities, refactored to do the same with the new DPDocumentStatus
- Moved the query to MWFActivity to use where required
- Refactored JDBC to Query
=> IDEMPIERE-5315 Mismatch in queries WWFActivity.getWhereActivities and DPActivitiesModel.getWorkflowCount

org.adempiere.base/src/org/adempiere/model/ZoomInfoFactory.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5311
=> IDEMPIERE-5311 - Zoom Across Doesn't Allow Zoom from Different Windows of the Same Table

org.adempiere.pipo/src/org/adempiere/pipo/srv/PipoDictionaryService.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4723
=> IDEMPIERE-4723 - Remove unused method

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5317
=> IDEMPIERE-5317 Improvements for Workflow Activities

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/DetailPane.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5318
=> IDEMPIERE-5318 DetailPane ignore IAction.getIconSclass

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WColorEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5321
=> IDEMPIERE-5321 Color editor not working on Chrome

org.idempiere.p2.targetplatform.mirror.aggregator/README.md, org.idempiere.p2.targetplatform.mirror.aggregator/pom.xml, org.idempiere.p2.targetplatform.mirror.feature/.project, org.idempiere.p2.targetplatform.mirror.feature/README.md, org.idempiere.p2.targetplatform.mirror.feature/build.properties, org.idempiere.p2.targetplatform.mirror.feature/feature.xml, org.idempiere.p2.targetplatform.mirror.feature/pom.xml, org.idempiere.p2.targetplatform.mirror/.project, org.idempiere.p2.targetplatform.mirror/category.xml, org.idempiere.p2.targetplatform.mirror/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-5314
=> IDEMPIERE-5314 Add support to create local target platform mirror

migration/iD10/oracle/202205181247_IDEMPIERE-2058.sql, migration/iD10/postgresql/202205181247_IDEMPIERE-2058.sql, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Messagebox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-2058
Installed fix new report - we assumed that to adding new Copy Report is better
=> IDEMPIERE-2058 - ** New Report ** - improve for handling Forms too

migration/iD10/oracle/202206171231_IDEMPIERE-5319.sql, migration/iD10/postgresql/202206171231_IDEMPIERE-5319.sql, org.adempiere.base/src/org/compiere/model/GridTab.java, org.adempiere.base/src/org/compiere/model/GridTabVO.java, org.adempiere.base/src/org/compiere/model/I_AD_Tab.java, org.adempiere.base/src/org/compiere/model/I_AD_UserDef_Tab.java, org.adempiere.base/src/org/compiere/model/X_AD_Tab.java, org.adempiere.base/src/org/compiere/model/X_AD_UserDef_Tab.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Messagebox.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/IInputValidator.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FDialog.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5319
=> IDEMPIERE-5319 - Delete Record with Confirmation Logic

migration/i9/oracle/202206271645_IDEMPIERE-5331.sql, migration/i9/postgresql/202206271645_IDEMPIERE-5331.sql, org.adempiere.base.process/src/org/compiere/process/OrderCreateProduction.java, org.adempiere.base.process/src/org/compiere/process/OrderLineCreateProduction.java, org.adempiere.base/src/org/compiere/model/MProduction.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5331
=> IDEMPIERE-5331 Create Production from Order (all Lines)

org.adempiere.base/src/org/compiere/model/MArchive.java, org.adempiere.ui/src/org/compiere/apps/form/Archive.java, org.idempiere.test/src/org/idempiere/test/form/ArchiveViewerFormTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5332
=> IDEMPIERE-5332 Refactoring of Archive Viewer

org.adempiere.base/src/org/adempiere/base/event/EventHelper.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5340
=> IDEMPIERE-5340 Log the exception in EventHelper.addError for future use (FHCA-3426)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WCharge.java, org.adempiere.ui/src/org/compiere/apps/form/Charge.java, org.idempiere.test/src/org/idempiere/test/form/ChargeFormTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5337
=> IDEMPIERE-5337 Refactoring of Generate Charge from Account form

org.adempiere.base/src/org/compiere/process/ProcessInfo.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5347
=> IDEMPIERE-5347 Minor scheduler improvement

org.adempiere.base/src/org/compiere/util/Login.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5345
=> IDEMPIERE-5345 Login.getClients not validating role type

org.adempiere.ui/src/org/idempiere/apps/form/BOMDrop.java, org.idempiere.test/src/org/idempiere/test/form/BOMDropFormTest.java
=> IDEMPIERE-5327 Refactoring and clean up of BOM Drop form

org.adempiere.base.process/src/org/adempiere/process/InOutGenerateRMA.java, org.adempiere.base.process/src/org/compiere/process/InOutGenerate.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-1963
=> IDEMPIERE-1963 - additional fix

migration/iD10/oracle/202207211214_IDEMPIERE-5353.sql, migration/iD10/postgresql/202207211214_IDEMPIERE-5353.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5353
=> IDEMPIERE-5353 Entity type field in the Column tab becomes read-only when you enter a wrong value

org.adempiere.base.process/src/org/adempiere/process/InOutGenerateRMA.java, org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java
- add unit test for Vendor RMA
=> IDEMPIERE-1963 Implement Generate Shipments (manual) as Info Window

org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/util/Trx.java, org.adempiere.server/src/main/server/org/compiere/server/SystemInfo.java, org.adempiere.server/src/main/server/org/compiere/server/TrxInfo.java, org.adempiere.server/src/main/servlet/org/compiere/web/AdempiereMonitor.java, org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5355
=> IDEMPIERE-5355 Improve default trx name (FHCA-3765)

org.adempiere.base/src/org/compiere/model/MInventoryLine.java
- Fix always getting current cost from primary accounting schema.
=> IDEMPIERE-5153 Cost Adjument Line Before Save: Update current cost price

org.adempiere.base/src/org/compiere/model/MRefList.java
=> IDEMPIERE-5363 - fix MRefList cache

org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5356
=> IDEMPIERE-5356 - Add Printing Support to ProcessInfoDialog

org.adempiere.base/src/org/compiere/model/MTreeFavorite.java
https://idempiere.atlassian.net/browse/IDEMPIERE-3340?focusedCommentId=48595
=> IDEMPIERE-3340 Fix cross tenant in Favourites

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeDialog.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5362
=> IDEMPIERE-5362 - Attribute Dialog UX improvments 2022 aug

org.adempiere.base/src/org/compiere/model/MTreeFavorite.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5375
=> IDEMPIERE-5375 Read-only windows are not shown in Favourites dashboard

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5356
=> IDEMPIERE-5356 - Printing Support on ProcessInfoDialog - NPE fix

org.adempiere.base.callout/src/org/compiere/model/CalloutInvoice.java, org.adempiere.base.callout/src/org/compiere/model/CalloutOrder.java, org.adempiere.base.process/src/org/compiere/process/RoleAccessUpdate.java, org.adempiere.base/src/org/adempiere/base/PackInFolderApplication.java, org.adempiere.base/src/org/adempiere/base/PostMigrationApplication.java, org.adempiere.base/src/org/compiere/impexp/ImpFormat.java, org.adempiere.base/src/org/compiere/model/MSystem.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.base/src/org/compiere/report/FinReport.java, org.adempiere.base/src/org/compiere/util/DB.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.replication.server/src/org/compiere/server/ReplicationProcessor.java, org.adempiere.server/src/main/server/org/compiere/server/AcctProcessor.java, org.adempiere.server/src/main/server/org/compiere/server/AdempiereServer.java, org.adempiere.server/src/main/server/org/compiere/server/Scheduler.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WCreateFromDepositBatchUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WCreateFromStatementUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WInOutGen.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WInvoiceGen.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/dashboard/EventWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-236
=> IDEMPIERE-236 Centralization of hardcoded IDs

org.adempiere.base/src/org/compiere/db/CConnection.java, org.adempiere.base/src/org/compiere/util/DB.java, org.adempiere.base/src/org/idempiere/db/util/AutoCommitConnectionBroker.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5376
=> IDEMPIERE-5376 CConnection and DB clean up

org.adempiere.ui/src/org/compiere/grid/CreateFromShipment.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5377
=> IDEMPIERE-5377 Invoice stuck in "Create From" material receipt window

org.adempiere.base/src/org/compiere/process/MFARevokeDevice.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5381
=> IDEMPIERE-5381 System users cannot revoke MFA trusted devices in GardenWorld (FHCA-3824)

migration/i9/oracle/202208112323_IDEMPIERE-5382.sql, migration/i9/postgresql/202208112323_IDEMPIERE-5382.sql, org.adempiere.base/src/org/compiere/model/MMFARegistration.java, org.adempiere.base/src/org/compiere/process/MFARegister.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5382
=> IDEMPIERE-5382 Allow just one MFA registration per mechanism (FHCA-3822)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5378
=> IDEMPIERE-5378 MFA must allow to select the mechanism when the user has several registered (FHCA-3808)

org.adempiere.base/src/org/compiere/model/MRole.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5380
=> IDEMPIERE-5380 StackOverflowError when try to login in application with substitute user (FHCA-3828)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/WAttachment.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5385
=> IDEMPIERE-5385 PDF attachments cannot be displayed in firefox

org.adempiere.base/src/org/compiere/model/MTable.java, org.idempiere.test/idempiere.unit.test.parallel.launch, org.idempiere.test/src/org/idempiere/test/ConversionRateHelper.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/base/Convert_PostgreSQLTest.java, org.idempiere.test/src/org/idempiere/test/base/InOutTest.java, org.idempiere.test/src/org/idempiere/test/base/MatchInv2ndAcctSchemaTest.java, org.idempiere.test/src/org/idempiere/test/base/MatchInvTest.java, org.idempiere.test/src/org/idempiere/test/base/MatchInvTestIsolated.java, org.idempiere.test/src/org/idempiere/test/form/CreateFromInvoiceFormTest.java, org.idempiere.test/src/org/idempiere/test/form/CreateFromRMAFormTest.java, org.idempiere.test/src/org/idempiere/test/form/CreateFromShipmentFormTest.java, org.idempiere.test/src/org/idempiere/test/model/Allocation2ndAcctSchemaTest.java, org.idempiere.test/src/org/idempiere/test/model/AllocationTest.java, org.idempiere.test/src/org/idempiere/test/model/BankStatementTest.java, org.idempiere.test/src/org/idempiere/test/model/InventoryTest.java, org.idempiere.test/src/org/idempiere/test/model/InventoryTestIsolated.java, org.idempiere.test/src/org/idempiere/test/model/InvoiceCustomerTest.java, org.idempiere.test/src/org/idempiere/test/model/MStorageOnHandTest.java, org.idempiere.test/src/org/idempiere/test/model/MStorageOnHandTestIsolated.java, org.idempiere.test/src/org/idempiere/test/model/MTaxTest.java, org.idempiere.test/src/org/idempiere/test/model/ModelClassMappingTest.java, org.idempiere.test/src/org/idempiere/test/model/ProductionTest.java, org.idempiere.test/src/org/idempiere/test/model/ProductionTestIsolated.java, org.idempiere.test/src/org/idempiere/test/model/PurchaseOrderTest.java, org.idempiere.test/src/org/idempiere/test/model/SalesOrderTest.java, org.idempiere.test/src/org/idempiere/test/performance/CacheTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5391
=> IDEMPIERE-5391 Unit Test: Fix support for parallel execution of test

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5369
=> IDEMPIERE-5369 - Dashboard Cross Tenant Check

org.adempiere.ui.zk/pom.xml, org.idempiere.p2/pom.xml, org.idempiere.parent/pom.xml, org.idempiere.test/pom.xml, org.idempiere.test/src/org/idempiere/test/AbstractTestCase.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5392
=> IDEMPIERE-5392 Maven Build: add flag to skip auto clean

org.adempiere.base/src/org/compiere/report/core/RModelExcelExporter.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/acct/WAcctViewer.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5394
=> IDEMPIERE-5394 Export to XLSX in Info Windows and Account Viewer

migration/iD10/oracle/202208220922_IDEMPIERE-5393.sql, migration/iD10/postgresql/202208220922_IDEMPIERE-5393.sql, org.adempiere.base/src/org/compiere/model/I_PA_DashboardContent.java, org.adempiere.base/src/org/compiere/model/X_PA_DashboardContent.java, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5393
=> IDEMPIERE-5393 - Allow rendering status line as widget/gadget in dashboard

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxListEditor.java
Do not show Assistant for MultipleSelectionTable editors
Show Assistant for process parameters (use Business Partner Details > Credit Status to test)
=> IDEMPIERE-5265 : Wizard for Chosen Multiple Selection List editor - only for MultipleSelectionList editors / available for process parameters

migration/i9/oracle/202208282331_IDEMPIERE-5399.sql, migration/i9/postgresql/202208282331_IDEMPIERE-5399.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTimeEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5399
=> IDEMPIERE-5399 Data type Time is mostly useless

org.adempiere.base/src/org/compiere/model/MAuthorizationCredential.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5354
Comments at:
https://idempiere.atlassian.net/browse/IDEMPIERE-5354?focusedCommentId=48702
=> IDEMPIERE-5354 Manage use case for microsoft OAuth2 preferred_username (FHCA-3757)

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
Reopened JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5389
Adjust the additional row height to leave more space for the dashboard.
=> IDEMPIERE-5389-fix - additional row height fix

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JRIA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5406
=> IDEMPIERE-5406 - Define max-height to Charts in Dashboard Row Layout

migration/iD10/oracle/202209081125_IDEMPIERE-5400.sql, migration/iD10/postgresql/202209081125_IDEMPIERE-5400.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WPAWidget.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp, org.idempiere.zk.billboard/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.billboard/src/org/idempiere/zk/billboard/Version.java, org.idempiere.zk.billboard/src/web/js/zul/billboard/ext/billboard.gauge.js
JIRA Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5400
Added option to show/hide title similar as Chart - removes bottom title
Style Changes:
Before:
After:
=> IDEMPIERE-5400 - Gauge Indicator Style and Color Improvement

migration/iD10/oracle/202209080926_IDEMPIERE-5412.sql, migration/iD10/postgresql/202209080926_IDEMPIERE-5412.sql, org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusPanel.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/zul/calendar/calendar.css
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5412
=> IDEMPIERE-5412 - Improve Dashboard Theme Look

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WReportCustomization.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5413
=> IDEMPIERE-5413 PO is Immutable in Report Wizard

migration/iD10/oracle/202209101629_IDEMPIERE-5243.sql, migration/iD10/postgresql/202209101629_IDEMPIERE-5243.sql, org.adempiere.base/src/org/compiere/process/ProcessInfoUtil.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5415
=> IDEMPIERE-5415 Incomplete process log when output is > 2000 chars

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/ADWindowToolbar.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5416
=> IDEMPIERE-5416 Alt+A is used for Create+New - for usability would be good to use it also for New

org.idempiere.equinox.p2.director-feature/director/configuration/config.ini
https://idempiere.atlassian.net/browse/IDEMPIERE-5417
=> IDEMPIERE-5417 update.sh show unresolved package error

org.compiere.db.oracle.provider/src/org/compiere/db/DB_Oracle.java, org.compiere.db.postgresql.provider/src/org/compiere/db/DB_PostgreSQL.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5013
=> IDEMPIERE-5013 Implement HikariCP as a replacement for c3p0

org.adempiere.base/src/org/compiere/print/ReportEngine.java
https://idempiere.atlassian.net/browse/IDEMPIERE-2058
=> IDEMPIERE-2058 Fix problem reading wrong column

migration/i9/oracle/202209131507_IDEMPIERE-3340.sql, migration/i9/postgresql/202209131507_IDEMPIERE-3340.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-3340
=> IDEMPIERE-3340 Fix issue not allowing to delete a user

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5424
=> IDEMPIERE-5424 NPE when setting SysConfig BACKGROUND_JOB_ALLOWED=N

org.idempiere.parent/pom.xml
https://idempiere.atlassian.net/browse/IDEMPIERE-5427
=> IDEMPIERE-5427 Upgrade to Tycho 2.7.5

org.adempiere.base/src/org/compiere/model/MField.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5430
=> IDEMPIERE-5430 UPDATE generating unnecessary settings for null columns

org.adempiere.base/src/org/adempiere/util/IProcessUI.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AbstractProcessDialog.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPaySelect.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WPasswordEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/Dialog.java
Please read carefully the [Contributing to Core](https://wiki.idempiere.org/en/Contributing_to_Trunk) guidelines before starting the development. 
This is a list of the common issues, standards and guidelines when contributing to iDempiere's core. Following all the recommendations will make the merging process smoother for everyone involved.
Please ensure that information in JIRA is sufficient, it must contain a natural language description of the changes proposed, when relevant is important to add information about how to test and the possible collateral effects that the ticket can impact.
Please include here the link to the corresponding JIRA ticket in the description, this helps with navigating back and forth between JIRA and GitHub.
* Make sure the changes you want to commit pass all …
=> IDEMPIERE-2205 - Ask for secret input from within a process

migration/iD10/oracle/202209290713_IDEMPIERE-5434.sql, migration/iD10/postgresql/202209290713_IDEMPIERE-5434.sql, org.adempiere.base/src/org/compiere/model/I_AD_ViewComponent.java, org.adempiere.base/src/org/compiere/model/MViewComponent.java, org.adempiere.base/src/org/compiere/model/X_AD_ViewComponent.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5434
Please read carefully the [Contributing to Core](https://wiki.idempiere.org/en/Contributing_to_Trunk) guidelines before starting the development. 
This is a list of the common issues, standards and guidelines when contributing to iDempiere's core. Following all the recommendations will make the merging process smoother for everyone involved.
Please ensure that information in JIRA is sufficient, it must contain a natural language description of the changes proposed, when relevant is important to add information about how to test and the possible collateral effects that the ticket can impact.
Please include here the link to the corresponding JIRA ticket in the description, this helps with navigating back and forth between JIRA and …
=> IDEMPIERE-5434 : Allow to define db view component with DISTINCT

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WFactReconcile.java, org.adempiere.ui/src/org/compiere/apps/form/FactReconcile.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/form/FactReconcileFormTest.java
Please read carefully the [Contributing to Core](https://wiki.idempiere.org/en/Contributing_to_Trunk) guidelines before starting the development. 
This is a list of the common issues, standards and guidelines when contributing to iDempiere's core. Following all the recommendations will make the merging process smoother for everyone involved.
Please ensure that information in JIRA is sufficient, it must contain a natural language description of the changes proposed, when relevant is important to add information about how to test and the possible collateral effects that the ticket can impact.
Please include here the link to the corresponding JIRA ticket in the description, this helps with navigating back and forth between JIRA and GitHub.
* Make sure the changes you want to commit pass all …
=> IDEMPIERE-5439 Add unit test for Fact Reconciliation form

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WMatch.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java, org.adempiere.ui/src/org/compiere/apps/form/Match.java, org.idempiere.test/src/org/idempiere/test/base/MatchPOTest.java, org.idempiere.test/src/org/idempiere/test/form/MatchFormTest.java
Please read carefully the [Contributing to Core](https://wiki.idempiere.org/en/Contributing_to_Trunk) guidelines before starting the development. 
This is a list of the common issues, standards and guidelines when contributing to iDempiere's core. Following all the recommendations will make the merging process smoother for everyone involved.
Please ensure that information in JIRA is sufficient, it must contain a natural language description of the changes proposed, when relevant is important to add information about how to test and the possible collateral effects that the ticket can impact.
Please include here the link to the corresponding JIRA ticket in the description, this helps with navigating back and forth between JIRA and GitHub.
* Make sure the changes you want to commit pass all …
=> IDEMPIERE-5440 Add unit test for Matching form

migration/iD10/oracle/202209221920_IDEMPIERE-5408.sql, migration/iD10/postgresql/202209221920_IDEMPIERE-5408.sql, org.adempiere.base.process/src/org/adempiere/process/InitialClientSetup.java, org.adempiere.base/src/org/compiere/model/I_AD_Client.java, org.adempiere.base/src/org/compiere/model/MClient.java, org.adempiere.base/src/org/compiere/model/MSetup.java, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/MSystem.java, org.adempiere.base/src/org/compiere/model/X_AD_Client.java, org.adempiere.base/src/org/compiere/util/Login.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ChangePasswordPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/ValidateMFAPanel.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/LoginWindow.java
[IDEMPIERE-5408](https://idempiere.atlassian.net/browse/IDEMPIERE-5408)
- - [x] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it.
=> IDEMPIERE-5408 Allow or enforce login with specific tenant (FHCA-3823)

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java, org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/gadget.css.dsp
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5414
=> IDEMPIERE-5414 - Improve Dashboard Help Icon Behaviour

migration/i9/oracle/202210051347_IDEMPIERE-5396.sql, migration/i9/postgresql/202210051347_IDEMPIERE-5396.sql, org.adempiere.base/src/org/compiere/model/MColumn.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5396
- Fix Default AD_InfoWindow_ID value of AD_Column
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If …
=> IDEMPIERE-5396 Replace CreateFrom form with Info Window Process

org.idempiere.webservices/WEB-INF/src/org/idempiere/webservices/AbstractService.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5442 …
=> IDEMPIERE-5442 : Fix typos in code - varialbe -> variable

migration/iD10/oracle/202210051139_IDEMPIERE-5259.sql, migration/iD10/postgresql/202210051139_IDEMPIERE-5259.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5259?focusedCommentId=48773
=> IDEMPIERE-5259 fix "Msg.getMsg: NOT found: Label" error

migration/iD10/oracle/202209261211_IDEMPIERE-5432.sql, migration/iD10/postgresql/202209261211_IDEMPIERE-5432.sql, org.adempiere.base/src/org/compiere/model/MMeasureCalc.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5432
=> IDEMPIERE-5432 - Performance Measure Calculation - Improve SQL Definition

org.idempiere.test/idempiere.unit.test.parallel.launch
Update parallel unit test launch configuration
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, …
=> IDEMPIERE-5402 Replace Jfree Chart with Billboard

org.adempiere.base/src/org/compiere/model/GridFieldVO.java, org.adempiere.base/src/org/compiere/model/GridTabVO.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5444 …
=> IDEMPIERE-5444 Refactoring of GridTabVO and GridFieldVO

migration/iD10/oracle/202210111536_IDEMPIERE-5447.sql, migration/iD10/postgresql/202210111536_IDEMPIERE-5447.sql, org.adempiere.base/src/org/compiere/model/MBPartner.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WMerge.java, org.adempiere.ui/src/org/compiere/apps/form/Merge.java, org.idempiere.test/src/org/idempiere/test/form/MergeFormTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5447 …
=> IDEMPIERE-5447 Add unit test for Merge form

migration/i9/oracle/202210111720_IDEMPIERE-5445.sql, migration/i9/postgresql/202210111720_IDEMPIERE-5445.sql, org.adempiere.base/src/org/compiere/model/I_PA_ReportColumn.java, org.adempiere.base/src/org/compiere/model/I_PA_ReportLine.java, org.adempiere.base/src/org/compiere/model/X_PA_ReportColumn.java, org.adempiere.base/src/org/compiere/model/X_PA_ReportLine.java, org.adempiere.base/src/org/compiere/report/FinReport.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5445
=> IDEMPIERE-5445 Implement multiplier and rounding for financial reports

migration/i9/oracle/202210131724_IDEMPIERE-5450.sql, migration/i9/postgresql/202210131724_IDEMPIERE-5450.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WSQLProcess.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5450
=> IDEMPIERE-5450 Form SQL Process has security issues

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java
=> IDEMPIERE-5449 Performance: Avoid recount when clicking a process button

migration/i9/oracle/202210131930_IDEMPIERE-5451.sql, migration/i9/postgresql/202210131930_IDEMPIERE-5451.sql, org.adempiere.base/src/org/compiere/model/MSysConfig.java, org.adempiere.base/src/org/compiere/model/SystemIDs.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WSQLQuery.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5451
- - [x] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
=> IDEMPIERE-5451 Create a form SQL Query - similar to SQL process to execute queries (FHCA-3849)

migration/i9/oracle/202210191926_IDEMPIERE-2901.sql, migration/i9/postgresql/202210191926_IDEMPIERE-2901.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-2901?focusedCommentId=48805
=> IDEMPIERE-2901 Period Control Management / Change period status and docbasetype to multiple-selection list

org.adempiere.base/src/org/compiere/util/DB.java, org.adempiere.base/src/org/compiere/util/Msg.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/adwindow/AbstractADWindowContent.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5456
=> IDEMPIERE-5456 - Msg wrong arguments number Format

migration/iD10/oracle/202210191953_IDEMPIERE-5455.sql, migration/iD10/postgresql/202210191953_IDEMPIERE-5455.sql, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WChosenboxSearchEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5455
=> IDEMPIERE-5455 Use Multi-Select parameters in Info Windows

org.idempiere.zk.billboard/src/metainfo/zk/lang-addon.xml, org.idempiere.zk.billboard/src/web/js/zul/billboard/Billboard.js
https://idempiere.atlassian.net/browse/IDEMPIERE-5457 …
=> IDEMPIERE-5457 Billboard Charts can cause memory leaks

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/DateRangePicker.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5443 …
=> IDEMPIERE-5443 - Fix Date Range Filter Quick mode + update default version

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5443
- Fix issue with non-date field …
=> IDEMPIERE-5443 Date Range Filter Component

org.adempiere.base/src/org/compiere/model/MAssetAddition.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5475
=> IDEMPIERE-5475 Fixed Assets - NPE when creating an asset addition without invoice

migration/iD10/oracle/202211112147_IDEMPIERE-870.sql, migration/iD10/postgresql/202211112147_IDEMPIERE-870.sql, org.adempiere.base/src/org/compiere/model/MAssetAddition.java, org.adempiere.base/src/org/compiere/util/Env.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java
https://idempiere.atlassian.net/browse/IDEMPIERE-870
=> IDEMPIERE-870 Fixed Assets using non-existant context variable

org.adempiere.base/src/org/compiere/model/MRequest.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/WRequest.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/model/MRequestTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5476 …
=> IDEMPIERE-5476 Refactoring of WRequest and MRequest

org.adempiere.base/src/org/compiere/model/MArchive.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/WArchive.java, org.idempiere.test/src/org/idempiere/test/model/MArchiveTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5473 …
=> IDEMPIERE-5473 Refactoring of WArchive and MArchive

migration/i9/oracle/202211112236_IDEMPIERE-5474.sql, migration/i9/postgresql/202211112236_IDEMPIERE-5474.sql, org.adempiere.base/src/org/compiere/acct/Doc_AssetAddition.java, org.adempiere.base/src/org/compiere/model/I_A_Asset.java, org.adempiere.base/src/org/compiere/model/I_A_Asset_Change.java, org.adempiere.base/src/org/compiere/model/I_A_Asset_Group_Acct.java, org.adempiere.base/src/org/compiere/model/I_A_Depreciation_Workfile.java, org.adempiere.base/src/org/compiere/model/I_I_Asset.java, org.adempiere.base/src/org/compiere/model/MAsset.java, org.adempiere.base/src/org/compiere/model/MAssetAddition.java, org.adempiere.base/src/org/compiere/model/MAssetGroup.java, org.adempiere.base/src/org/compiere/model/MAssetGroupAcct.java, org.adempiere.base/src/org/compiere/model/X_A_Asset.java, org.adempiere.base/src/org/compiere/model/X_A_Asset_Change.java, org.adempiere.base/src/org/compiere/model/X_A_Asset_Group_Acct.java, org.adempiere.base/src/org/compiere/model/X_A_Depreciation_Workfile.java, org.adempiere.base/src/org/compiere/model/X_I_Asset.java, org.adempiere.base/src/org/idempiere/fa/feature/UseLifeImpl.java, org.adempiere.base/src/org/idempiere/fa/model/CalloutA_Depreciation_Workfile.java, org.adempiere.base/src/org/idempiere/fa/process/ImportFixedAsset.java, org.idempiere.test/src/org/idempiere/test/DictionaryIDs.java, org.idempiere.test/src/org/idempiere/test/model/FixedAssetsTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5474
=> IDEMPIERE-5474 Fixed Assets don't allow depreciation on 18 months

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/DateRangePicker.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5480 …
=> IDEMPIERE-5480 - Date Range Picker Mobile Support

db/postgresql/functions/nvl.sql, migration/i9/oracle/202211201304_IDEMPIERE-5484.sql, migration/i9/postgresql/202211201304_IDEMPIERE-5484.sql, org.idempiere.test/src/org/idempiere/test/base/DBTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5484
=> IDEMPIERE-5484 Import GL Journal fails with SQL error because of NVL

org.adempiere.base/src/org/compiere/model/MLocationLookup.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WLocationEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5494 …
=> # IDEMPIERE-5494 - enable zoom in WLocationEditor

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/wf/WWFActivity.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5492 …
=> # IDEMPIERE-5492 - reset workflow activities message-

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/AEnv.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WDrillReport.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WEditorPopupMenu.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java, org.adempiere.ui/src/org/compiere/print/DrillReportCtl.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5489 …
=> IDEMPIERE-5489 - Allow to Start Drill Assistant from Window Field Menu

migration/i9/oracle/202211281240_IDEMPIERE-5497.sql, migration/i9/postgresql/202211281240_IDEMPIERE-5497.sql
https://idempiere.atlassian.net/browse/IDEMPIERE-5497
=> IDEMPIERE-5497 Support User vs Roles - minor improvement - change Role to list (FHCA-4016)

org.adempiere.base/src/org/compiere/model/MInventory.java, org.adempiere.base/src/org/compiere/model/MStorageOnHand.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5483
Committing code by @igorpojzl 
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is …
=> IDEMPIERE-5483 - Physical Inventory Doesn't Update Last Inventory Date on Specific Cases

org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml, org.adempiere.ui.zk/css/report.css
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5499 …
=> IDEMPIERE-5499 - Report CSS - set width to 100%

org.adempiere.base/src/org/compiere/util/DisplayType.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5501
=> IDEMPIERE-5501 Misses in cache IDisplayTypeFactory

org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/editor/WTableDirEditor.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5500
=> IDEMPIERE-5500 Autorefresh of Table lists not working correctly

migration/iD10/oracle/202211290811_IDEMPIERE-5490.sql, migration/iD10/postgresql/202211290811_IDEMPIERE-5490.sql, org.adempiere.base/src/org/compiere/model/I_PA_DashboardContent.java, org.adempiere.base/src/org/compiere/model/X_PA_DashboardContent.java, org.adempiere.base/src/org/compiere/print/ReportEngine.java, org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/desktop/DashboardController.java
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5490 …
=> IDEMPIERE-5490 - Dashboard Content->Report -> Allow specify Print Format

migration/iD10/oracle/202211111143_IDEMPIERE-5371.sql, migration/iD10/postgresql/202211111143_IDEMPIERE-5371.sql, org.adempiere.base/src/org/compiere/model/I_AD_PInstance.java, org.adempiere.base/src/org/compiere/model/MPInstance.java, org.adempiere.base/src/org/compiere/model/X_AD_PInstance.java
replaces https://github.com/idempiere/idempiere/pull/1577
=> IDEMPIERE-5371 : Adding user session reference on Process Instance

org.adempiere.ui/src/org/compiere/grid/PaymentFormCreditCard.java, org.idempiere.test/src/org/idempiere/test/form/PaymentFormTest.java
https://idempiere.atlassian.net/browse/IDEMPIERE-5506 …
=> IDEMPIERE-5506 Oralce: PaymentFormTest hangs due to DB dead lock
